# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredworld',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.World'),
        ),
    ]
