# Generated by Django 3.2.25 on 2025-06-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_indevelopmentworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverworld',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='discoverworld',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='featuredworld',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='featuredworld',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='indevelopmentworld',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='indevelopmentworld',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
