WORLD_LIFECYCLE_NEW = 'new'
WORLD_LIFECYCLE_STARTING = 'starting'
WORLD_LIFECYCLE_RUNNING = 'running'
# Once a world moves into stopping, the only action it should be able to do is stop.
WORLD_LIFECYCLE_STOPPING = 'stopping'
WORLD_LIFECYCLE_STOPPED = 'stopped'
WORLD_LIFECYCLES = [
    WORLD_LIFECYCLE_NEW,
    WORLD_LIFECYCLE_STARTING,
    WORLD_LIFECYCLE_RUNNING,
    WORLD_LIFECYCLE_STOPPING,
    WORLD_LIFECYCLE_STOPPED,
]

WORLD_STATE_NEW = 'new'
#WORLD_STATE_LOADED = 'loaded' # Loaders have been run against this world
WORLD_STATE_BUILDING = 'building' # Kubernetes nexus is being built
WORLD_STATE_BUILT = 'built' # Kubernetes nexus has been built
WORLD_STATE_RUNNING = 'running' # World is up, live, loaded, out of sync
WORLD_STATE_ARCHIVED = 'archived'
WORLD_STATE_INITIALIZED = 'initialized'
WORLD_STATE_COMPLETE = 'complete' # SPW only
WORLD_STATE_STARTING = 'starting'
WORLD_STATE_ABORT = 'abort' # start or build failures
# SPW only states
WORLD_STATE_STORING = 'storing' # World is in the process of being extracted
WORLD_STATE_STORED = 'stored' # World has been extracted and is only in psql
# MPW only states
WORLD_STATE_RESTARTING = 'restarting'
WORLD_STATE_CLEAN = 'clean'
# World is marked as being in the process of stopping, which means
# new connections won't be accepted, loaders / merchants won't run
WORLD_STATE_STOPPING = 'stopping'
WORLD_STATE_STOPPED = 'stopped'
WORLD_STATE_QUEUED = 'queued'
WORLD_STATE_KILLING = 'killing'
WORLD_STATE_KILLED = 'killed'
WORLD_STATE_PENDING = 'pending'
WORLD_STATE_PENDING_CLEAN = 'pending_clean'
WORLD_STATE_CLEANING = 'cleaning'
WORLD_STATE_CLEAN_AND_START = 'clean_and_start'

"""
MPWs:
new > initialized > running > stored
SPWs:
new > running > stored
"""

WORLD_STATES = [
    WORLD_STATE_NEW,
    # Multiplayer worlds only, world has been wiped and loaders have been
    # run and the world is ready to have its initial animation done
    WORLD_STATE_INITIALIZED,
    WORLD_STATE_RUNNING,
    WORLD_STATE_STORED,
    # When archvied, a world should not be used for anything. The only state
    # that it should go to is stored, if it's ready to be re-used.
    WORLD_STATE_ARCHIVED,

    WORLD_STATE_STARTING,
    WORLD_STATE_RESTARTING,
    WORLD_STATE_STOPPING,
    WORLD_STATE_STOPPED,
    WORLD_STATE_QUEUED,
]

WORLD_REVIEW_STATUS_UNSUBMITTED = 'unsubmitted'
WORLD_REVIEW_STATUS_SUBMITTED = 'submitted'
WORLD_REVIEW_STATUS_APPROVED = 'approved'
WORLD_REVIEW_STATUS_REVIEWED = 'reviewed'
WORLD_REVIEW_STATUSES = [
    WORLD_REVIEW_STATUS_SUBMITTED,
    WORLD_REVIEW_STATUS_APPROVED,
    WORLD_REVIEW_STATUS_REVIEWED,
]

# For random items, spell out what kind of item to be
ITEM_SPECIFICATION_ARMOR = 'armor_only'
ITEM_SPECIFICATION_WEAPON = 'weapon_only'
ITEM_SPECIFICATION_WEAPON_1H = 'weapon_1h_only'
ITEM_SPECIFICATION_WEAPON_2H = 'weapon_2h_only'
ITEM_SPECIFICATION_SHIELD = 'shield_only'
ITEM_SPECIFICATION_WEAPON_OR_SHIELD = 'weapon_or_shield'
ITEM_SPECIFICATION_ARMOR_HEAVY = 'armor_heavy_only'
ITEM_SPECIFICATION_ARMOR_LIGHT = 'armor_light_only'
ITEM_SPECIFICATION_LIGHT_HEAD = 'armor_light_head'
ITEM_SPECIFICATION_LIGHT_BODY = 'armor_light_body'
ITEM_SPECIFICATION_LIGHT_ARMS = 'armor_light_arms'
ITEM_SPECIFICATION_LIGHT_HANDS = 'armor_light_hands'
ITEM_SPECIFICATION_LIGHT_WAIST = 'armor_light_waist'
ITEM_SPECIFICATION_LIGHT_LEGS = 'armor_light_legs'
ITEM_SPECIFICATION_LIGHT_FEET = 'armor_light_feet'
ITEM_SPECIFICATION_HEAVY_HEAD = 'armor_heavy_head'
ITEM_SPECIFICATION_HEAVY_BODY = 'armor_heavy_body'
ITEM_SPECIFICATION_HEAVY_ARMS = 'armor_heavy_arms'
ITEM_SPECIFICATION_HEAVY_HANDS = 'armor_heavy_hands'
ITEM_SPECIFICATION_HEAVY_WAIST = 'armor_heavy_waist'
ITEM_SPECIFICATION_HEAVY_LEGS = 'armor_heavy_legs'
ITEM_SPECIFICATION_HEAVY_FEET = 'armor_heavy_feet'
RANDOM_ITEM_SPECIFICATIONS = [
    ITEM_SPECIFICATION_ARMOR,
    ITEM_SPECIFICATION_WEAPON,
    ITEM_SPECIFICATION_WEAPON_1H,
    ITEM_SPECIFICATION_WEAPON_2H,
    ITEM_SPECIFICATION_SHIELD,
    ITEM_SPECIFICATION_WEAPON_OR_SHIELD,
    ITEM_SPECIFICATION_ARMOR_HEAVY,
    ITEM_SPECIFICATION_ARMOR_LIGHT,
    ITEM_SPECIFICATION_LIGHT_HEAD,
    ITEM_SPECIFICATION_LIGHT_BODY,
    ITEM_SPECIFICATION_LIGHT_ARMS,
    ITEM_SPECIFICATION_LIGHT_HANDS,
    ITEM_SPECIFICATION_LIGHT_WAIST,
    ITEM_SPECIFICATION_LIGHT_LEGS,
    ITEM_SPECIFICATION_LIGHT_FEET,
    ITEM_SPECIFICATION_HEAVY_HEAD,
    ITEM_SPECIFICATION_HEAVY_BODY,
    ITEM_SPECIFICATION_HEAVY_ARMS,
    ITEM_SPECIFICATION_HEAVY_HANDS,
    ITEM_SPECIFICATION_HEAVY_WAIST,
    ITEM_SPECIFICATION_HEAVY_LEGS,
    ITEM_SPECIFICATION_HEAVY_FEET,
]


TRANSFORMATION_TYPE_ATTR = 'attribute'
TRANSFORMATION_TYPES = [
    TRANSFORMATION_TYPE_ATTR,

]

PLAYER_EVENT_LOGIN = 'login'
PLAYER_EVENT_LOGOUT = 'logout'
PLAYER_EVENT_COMPLETE = 'complete'
PLAYER_EVENT_CREATE = 'create'
PLAYER_EVENTS = [
    PLAYER_EVENT_LOGIN,
    PLAYER_EVENT_LOGOUT,
    PLAYER_EVENT_COMPLETE,
    PLAYER_EVENT_CREATE,
]

MAX_RULE_SPAWNS = 15

# Sometimes the extraction tic runs right alongside the loading tic. Because
# the extraction tic does a population scan right before saving, the mob that's
# in the process of being loaded can get deleted by the cleanup process that
# comes with extraction.
# To help with this, we have a delay threshold for how long since a mob has
# been recorded missing before we delete them.
MOB_DELETION_DELAY = 20


USER_FLAG_NOCHAT = 'nochat'
USER_FLAG_NOTELL = 'notell'
USER_FLAG_NOPLAY = 'noplay'
USER_FLAGS = [
    USER_FLAG_NOCHAT,
    USER_FLAG_NOTELL,
    USER_FLAG_NOPLAY,
]

LEVEL_CAP = 20


FACT_SCHEDULE_SELECTION_DEFAULT = 'default'
FACT_SCHEDULE_SELECTION_CYCLE = 'cycle'
FACT_SCHEDULE_SELECTION_RANDOM = 'random'
FACT_SCHEDULE_SELECTIONS = [
    FACT_SCHEDULE_SELECTION_DEFAULT,
    FACT_SCHEDULE_SELECTION_CYCLE,
    FACT_SCHEDULE_SELECTION_RANDOM
]

FACT_SCHEDULE_SCHEDULE_INTERVAL = 'interval'
FACT_SCHEDULE_SCHEDULE_CRON = 'cron'
FACT_SCHEDULE_SCHEDULES = [
    FACT_SCHEDULE_SCHEDULE_INTERVAL,
    FACT_SCHEDULE_SCHEDULE_CRON
]

BUILDER_ACTION_WORLD_START = 'world_start'
BUILDER_ACTION_WORLD_STOP = 'world_stop'
BUILDER_ACTION_WORLD_KILL = 'world_kill'
BUILDER_ACTION_WORLD_CLEANUP = 'world_cleanup'
BUILDER_ACTIONS = [
    BUILDER_ACTION_WORLD_START,
    BUILDER_ACTION_WORLD_STOP,
    BUILDER_ACTION_WORLD_KILL,
]

NEXUS_STATE_ABSENT = 'absent'
NEXUS_STATE_BUILDING = 'building'
NEXUS_STATE_READY = 'ready'
NEXUS_STATE_DELETING = 'deleting'
NEXUS_STATE_ERROR = 'error'
NEXUS_STATES = [
    NEXUS_STATE_ABSENT,
    NEXUS_STATE_BUILDING,
    NEXUS_STATE_READY,
    NEXUS_STATE_DELETING,
    NEXUS_STATE_ERROR,
]

# How long after a user has not entered a command to mark them idle
IDLE_THRESHOLD = 5 * 60 # 5 minutes
# After how long to move a linkless player to the death room
LINKLESS_TIMEOUT = 8 * 60
# After how long to disconnect an idle player
IDLE_TIMEOUT = 10 * 60 # 10 minutes
BUILDER_IDLE_TIMEOUT = 2 * 60 * 60 # 2 hours

# WR2 MIGRATION: Legacy game constants
# Subset of legacy game constants used by backend modules.

DIRECTION_NORTH = 'north'

DIRECTION_EAST = 'east'

DIRECTION_SOUTH = 'south'

DIRECTION_WEST = 'west'

DIRECTION_UP = 'up'

DIRECTION_DOWN = 'down'

DIRECTIONS = (
    DIRECTION_NORTH,
    DIRECTION_EAST,
    DIRECTION_SOUTH,
    DIRECTION_WEST,
    DIRECTION_UP,
    DIRECTION_DOWN)

REVERSE_DIRECTIONS = {
    DIRECTION_NORTH: DIRECTION_SOUTH,
    DIRECTION_EAST: DIRECTION_WEST,
    DIRECTION_WEST: DIRECTION_EAST,
    DIRECTION_SOUTH: DIRECTION_NORTH,
    DIRECTION_UP: DIRECTION_DOWN,
    DIRECTION_DOWN: DIRECTION_UP,
}

DIR_COORD_DIFF = {
    'north': (0, 1, 0),
    'south': (0, -1, 0),
    'east': (1, 0, 0),
    'west': (-1, 0, 0),
    'up': (0, 0, 1),
    'down': (0, 0, -1),
}

EXIT_ACTION_MUTUAL = 'set_mutual_exit'

EXIT_ACTION_ONE_WAY = 'set_one_way'

EXIT_ACTION_NO_EXIT = 'set_no_exit'

EXIT_ACTION_CREATE = 'create_room'

EXIT_ACTION_MOVE = 'move'

EXIT_ACTIONS = [
    EXIT_ACTION_MUTUAL,
    EXIT_ACTION_ONE_WAY,
    EXIT_ACTION_NO_EXIT,
    EXIT_ACTION_CREATE,
    EXIT_ACTION_MOVE,
]

ROOM_TYPE_ROAD = 'road'

ROOM_TYPE_CITY = 'city'

ROOM_TYPE_INDOOR = 'indoor'

ROOM_TYPE_FIELD = 'field'

ROOM_TYPE_MOUNTAIN = 'mountain'

ROOM_TYPE_FOREST = 'forest'

ROOM_TYPE_DESERT = 'desert'

ROOM_TYPE_WATER = 'water'

ROOM_TYPE_SHALLOW = 'shallow'

ROOM_TYPE_TRAIL = 'trail'

ROOM_TYPES = (
    ROOM_TYPE_ROAD,
    ROOM_TYPE_CITY,
    ROOM_TYPE_INDOOR,
    ROOM_TYPE_FIELD,
    ROOM_TYPE_MOUNTAIN,
    ROOM_TYPE_FOREST,
    ROOM_TYPE_DESERT,
    ROOM_TYPE_WATER,
    ROOM_TYPE_SHALLOW,
    ROOM_TYPE_TRAIL)

ROOM_OWNERSHIP_TYPE_PRIVATE = 'private'

ROOM_OWNERSHIP_TYPE_PUBLIC = 'public'

ROOM_OWNERSHIP_TYPES = [
    ROOM_OWNERSHIP_TYPE_PRIVATE,
    ROOM_OWNERSHIP_TYPE_PUBLIC,
]

DOOR_STATE_OPEN = 'open'

DOOR_STATE_CLOSED = 'closed'

DOOR_STATE_LOCKED = 'locked'

DOOR_STATES = [
    DOOR_STATE_OPEN,
    DOOR_STATE_CLOSED,
    DOOR_STATE_LOCKED,
]

ROOM_CHECK_STATE_PASSED = 'passed'

ROOM_CHECK_STATE_FAILED = 'failed'

ROOM_CHECK_IN_INV = 'in_inv'

ROOM_CHECK_NOT_IN_INV = 'not_in_inv'

ROOM_CHECK_EQUIPPED = 'equipped'

ROOM_CHECK_NOT_EQUIPPED = 'not_equipped'

ROOM_CHECK_MOB_PRESENT = 'mob_is_present'

ROOM_CHECK_FACTION_BELOW = 'faction_below'

ROOM_CHECK_HEALTH_BELOW = 'health_below'

ROOM_CHECK_QUEST_COMPLETE = 'quest_complete'

ROOM_CHECK_QUEST_INCOMPLETE = 'quest_incomplete'

ROOM_CHECKS = [
    ROOM_CHECK_EQUIPPED,
    ROOM_CHECK_NOT_EQUIPPED,
    ROOM_CHECK_IN_INV,
    ROOM_CHECK_NOT_IN_INV,
    ROOM_CHECK_MOB_PRESENT,
    ROOM_CHECK_FACTION_BELOW,
    ROOM_CHECK_HEALTH_BELOW,
    ROOM_CHECK_QUEST_COMPLETE,
    ROOM_CHECK_QUEST_INCOMPLETE
]

CMD_CHECK_IN_INV = 'in_inv'

CMD_CHECK_CMD_ISSUED = 'cmd_issued'

CMD_CHECKS = [
    CMD_CHECK_IN_INV,
    CMD_CHECK_CMD_ISSUED,
]

ROOM_TRIGGER_ACTION_TRANSPORT = 'transport'

ROOM_TRIGGER_ACTION_MESSAGE = 'message'

ROOM_TRIGGER_ACTIONS = [
    ROOM_TRIGGER_ACTION_TRANSPORT,
    ROOM_TRIGGER_ACTION_MESSAGE,
]

TRIGGER_SCOPE_ROOM = 'room'

TRIGGER_SCOPE_ZONE = 'zone'

TRIGGER_SCOPE_WORLD = 'world'

TRIGGER_SCOPES = [
    TRIGGER_SCOPE_ROOM,
    TRIGGER_SCOPE_ZONE,
    TRIGGER_SCOPE_WORLD,
]

TRIGGER_KIND_COMMAND = 'command'

TRIGGER_KINDS = [
    TRIGGER_KIND_COMMAND,
]

ROOM_PREVENT_ALL = 'all'

ROOM_PREVENT_ENTER = 'enter'

ROOM_PREVENT_EXIT = 'exit'

ROOM_PREVENTS = [
    ROOM_PREVENT_ALL,
    ROOM_PREVENT_ENTER,
    ROOM_PREVENT_EXIT,
]

ROAM_ALL = 'all'

ROAM_STATIC = 'static'

ROAM_ZONE = 'zone'

ROAM_PATH = 'path'

ROAM_OPTIONS = [
    ROAM_ALL,
    ROAM_STATIC,
    ROAM_ZONE,
    ROAM_PATH,
]

ROOM_FLAG_NO_RIDE = 'no_ride'

ROOM_FLAG_NO_ROAM = 'no_roam'

ROOM_FLAG_DARK = 'dark'

ROOM_FLAG_NO_SPELL = 'no_spell'

ROOM_FLAG_PEACEFUL = 'peaceful'

ROOM_FLAG_INTEREST = 'interest'

ROOM_FLAG_WORKSHOP = 'workshop'

ROOM_FLAG_NO_QUIT = 'no_quit'

ROOM_FLAG_NO_LOAD = 'no_load'

ROOM_FLAG_FOUNTAIN = 'fountain'

ROOM_FLAG_TRAINER = 'trainer'

ROOM_FLAG_INN = 'inn'

ROOM_FLAG_EXP = 'exp'

ROOM_FLAG_HORSE = 'horse'

ROOM_FLAG_SHOP = 'shop'

ROOM_FLAG_FOOD = 'food'

ROOM_FLAG_CHOKE = 'choke'

ROOM_FLAG_SMOB = 'smob'

ROOM_FLAG_ACTION = 'action'

ROOM_FLAG_HERB = 'herb'

ROOM_FLAGS = [
    ROOM_FLAG_NO_RIDE,
    ROOM_FLAG_NO_LOAD,
    ROOM_FLAG_NO_ROAM,
    ROOM_FLAG_DARK,
    ROOM_FLAG_NO_SPELL,
    ROOM_FLAG_PEACEFUL,
    ROOM_FLAG_INTEREST,
    ROOM_FLAG_FOUNTAIN,
    ROOM_FLAG_TRAINER,
    ROOM_FLAG_INN,
    ROOM_FLAG_EXP,
    ROOM_FLAG_HORSE,
    ROOM_FLAG_SHOP,
    ROOM_FLAG_FOOD,
    ROOM_FLAG_CHOKE,
    ROOM_FLAG_SMOB,
    ROOM_FLAG_ACTION,
    ROOM_FLAG_HERB,
    ROOM_FLAG_WORKSHOP,
    ROOM_FLAG_NO_QUIT,
]

EXCLUDE_NAME_TOKENS = [
    'a', 'an', 'the', 'with', 'in', 'from', 'all', 'of', 'here', 'to',
]

GENDER_MALE = 'male'

GENDER_FEMALE = 'female'

GENDER_NON_BINARY = 'non_binary'

GENDERS = (GENDER_MALE, GENDER_FEMALE, GENDER_NON_BINARY)

MOB_TYPE_ABERRATION = 'aberration'

MOB_TYPE_BEAST = 'beast'

MOB_TYPE_CELESTIAL = 'celestial'

MOB_TYPE_CONSTRUCT = 'construct'

MOB_TYPE_DRAGON = 'dragon'

MOB_TYPE_ELEMENTAL = 'elemental'

MOB_TYPE_FEY = 'fey'

MOB_TYPE_FIEND = 'fiend'

MOB_TYPE_GIANT = 'giant'

MOB_TYPE_HUMANOID  ='humanoid'

MOB_TYPE_MONSTROSITY = 'monstrosity'

MOB_TYPE_OOZE = 'ooze'

MOB_TYPE_PLANT = 'plant'

MOB_TYPE_UNEAD = 'undead'

MOB_TYPES = (
    MOB_TYPE_ABERRATION,
    MOB_TYPE_BEAST,
    MOB_TYPE_CELESTIAL,
    MOB_TYPE_CONSTRUCT,
    MOB_TYPE_DRAGON,
    MOB_TYPE_ELEMENTAL,
    MOB_TYPE_FEY,
    MOB_TYPE_FIEND,
    MOB_TYPE_GIANT,
    MOB_TYPE_HUMANOID,
    MOB_TYPE_MONSTROSITY,
    MOB_TYPE_OOZE,
    MOB_TYPE_PLANT,
    MOB_TYPE_UNEAD,
)

MOB_AGGRESSION_PASSIVE = 'passive'

MOB_AGGRESSION_ALL = 'all'

MOB_AGGRESSION_PLAYERS = 'players'

MOB_AGGRESSION_NORMAL = 'normal'

MOB_AGGRESSION_FRIENDLY = 'friendly'

MOB_AGGRESSION_OPTIONS = [
    MOB_AGGRESSION_PASSIVE,
    MOB_AGGRESSION_ALL,
    MOB_AGGRESSION_PLAYERS,
    MOB_AGGRESSION_NORMAL,
    MOB_AGGRESSION_FRIENDLY,
    #MOB_AGGRESSION_ALIGNMENT_OPPOSITE,
    #MOB_AGGRESSION_ALIGNMENT_GOOD,
    #MOB_AGGRESSION_ALIGNMENT_EVIL,
    #MOB_AGGRESSION_ALIGNMENT_NEUTRAL,
]

ITEM_CURRENCY_GOLD = 'gold'

ITEM_CURRENCY_MEDAL = 'medal'

ITEM_CURRENCIES = [
    ITEM_CURRENCY_GOLD,
    ITEM_CURRENCY_MEDAL,
]

ITEM_TYPE_EQUIPPABLE = 'equippable'

ITEM_TYPE_CONSUMABLE = 'consumable'

ITEM_TYPE_FOOD = 'food'

ITEM_TYPE_LIGHT = 'light'

ITEM_TYPE_CONTAINER = 'container'

ITEM_TYPE_KEY = 'key'

ITEM_TYPE_INERT = 'inert'

ITEM_TYPE_CORPSE = 'corpse'

ITEM_TYPE_TRASH = 'trash'

ITEM_TYPE_QUEST = 'quest'

ITEM_TYPE_AMMUNITION = 'ammunition'

ITEM_TYPE_AUGMENT = 'augment'

ITEM_TYPES = [
    ITEM_TYPE_EQUIPPABLE,
    ITEM_TYPE_CONSUMABLE,
    ITEM_TYPE_FOOD,
    ITEM_TYPE_LIGHT,
    ITEM_TYPE_CONTAINER,
    ITEM_TYPE_KEY,
    ITEM_TYPE_INERT,
    ITEM_TYPE_CORPSE,
    ITEM_TYPE_TRASH,
    ITEM_TYPE_QUEST,
    ITEM_TYPE_AMMUNITION,
    ITEM_TYPE_AUGMENT,
]

ITEM_FOOD_TYPE_STAMINA = 'stamina'

ITEM_FOOD_TYPE_MANA = 'mana'

ITEM_FOOD_TYPE_HEALTH = 'health'

ITEM_FOOD_TYPES = [
    ITEM_FOOD_TYPE_STAMINA,
    ITEM_FOOD_TYPE_MANA,
    ITEM_FOOD_TYPE_HEALTH,
]

ITEM_QUALITY_NORMAL = 'normal'

ITEM_QUALITY_IMBUED = 'imbued'

ITEM_QUALITY_ENCHANTED = 'enchanted'

ITEM_QUALITIES = [
    ITEM_QUALITY_NORMAL,
    ITEM_QUALITY_IMBUED,
    ITEM_QUALITY_ENCHANTED,
]

EQUIPMENT_TYPE_WEAPON_1H = 'weapon_1h'

EQUIPMENT_TYPE_WEAPON_2H = 'weapon_2h'

EQUIPMENT_TYPE_SHIELD = 'shield'

EQUIPMENT_TYPE_HEAD = 'head'

EQUIPMENT_TYPE_BODY = 'body'

EQUIPMENT_TYPE_ARMS = 'arms'

EQUIPMENT_TYPE_HANDS = 'hands'

EQUIPMENT_TYPE_WAIST = 'waist'

EQUIPMENT_TYPE_LEGS = 'legs'

EQUIPMENT_TYPE_FEET = 'feet'

EQUIPMENT_TYPE_ACCESSORY = 'accessory'

EQUIPMENT_TYPES = (
    EQUIPMENT_TYPE_WEAPON_1H,
    EQUIPMENT_TYPE_WEAPON_2H,
    EQUIPMENT_TYPE_SHIELD,
    EQUIPMENT_TYPE_HEAD,
    EQUIPMENT_TYPE_BODY,
    EQUIPMENT_TYPE_ARMS,
    EQUIPMENT_TYPE_HANDS,
    EQUIPMENT_TYPE_WAIST,
    EQUIPMENT_TYPE_LEGS,
    EQUIPMENT_TYPE_FEET,
    EQUIPMENT_TYPE_ACCESSORY,
)

EQUIPMENT_ARMOR = (
    EQUIPMENT_TYPE_HEAD,
    EQUIPMENT_TYPE_BODY,
    EQUIPMENT_TYPE_ARMS,
    EQUIPMENT_TYPE_HANDS,
    EQUIPMENT_TYPE_WAIST,
    EQUIPMENT_TYPE_LEGS,
    EQUIPMENT_TYPE_FEET,
)

EQUIPMENT_SLOT_WEAPON = 'weapon'

EQUIPMENT_SLOT_OFFHAND = 'offhand'

EQUIPMENT_SLOT_HEAD = 'head'

EQUIPMENT_SLOT_BODY = 'body'

EQUIPMENT_SLOT_ARMS = 'arms'

EQUIPMENT_SLOT_HANDS = 'hands'

EQUIPMENT_SLOT_WAIST = 'waist'

EQUIPMENT_SLOT_LEGS = 'legs'

EQUIPMENT_SLOT_FEET = 'feet'

EQUIPMENT_SLOT_ACCESSORY = 'accessory'

EQUIPMENT_SLOTS = (
    EQUIPMENT_SLOT_WEAPON,
    EQUIPMENT_SLOT_OFFHAND,
    EQUIPMENT_SLOT_HEAD,
    EQUIPMENT_SLOT_BODY,
    EQUIPMENT_SLOT_ARMS,
    EQUIPMENT_SLOT_HANDS,
    EQUIPMENT_SLOT_WAIST,
    EQUIPMENT_SLOT_LEGS,
    EQUIPMENT_SLOT_FEET,
    #EQUIPMENT_SLOT_SHOULDERS,
    EQUIPMENT_SLOT_ACCESSORY,
)

def get_slot_constant(eq_type):
    if eq_type == EQUIPMENT_TYPE_WEAPON_2H:
        return 2.5
    elif eq_type in (
        EQUIPMENT_TYPE_WEAPON_1H,
        EQUIPMENT_TYPE_HEAD,
        EQUIPMENT_TYPE_BODY,
        EQUIPMENT_TYPE_LEGS):
        return 1.25
    elif eq_type:
        return 1
    return 0

WEAPON_GRIP_ONE_HAND = 'one_hand'

WEAPON_GRIP_TWO_HANDS = 'two_hands'

WEAPON_GRIPS = [
    WEAPON_GRIP_ONE_HAND,
    WEAPON_GRIP_TWO_HANDS,
]

WEAPON_TYPE_SWORD = 'sword'

WEAPON_TYPE_AXE = 'axe'

WEAPON_TYPE_CLUB = 'club'

WEAPON_TYPE_SPEAR = 'spear'

WEAPON_TYPE_STAFF = 'staff'

WEAPON_TYPE_DAGGER = 'dagger'

WEAPON_TYPE_POLEARM = 'polearm'

WEAPON_TYPE_BOW = 'bow'

WEAPON_TYPE_GUN = 'gun'

WEAPON_TYPES = [
    WEAPON_TYPE_SWORD,
    WEAPON_TYPE_AXE,
    WEAPON_TYPE_CLUB,
    WEAPON_TYPE_SPEAR,
    WEAPON_TYPE_STAFF,
    WEAPON_TYPE_POLEARM,
    WEAPON_TYPE_DAGGER,
    WEAPON_TYPE_BOW,
    WEAPON_TYPE_GUN
]

ARMOR_CLASS_LIGHT = 'light'

ARMOR_CLASS_HEAVY = 'heavy'

ARMOR_CLASSES = [
    ARMOR_CLASS_LIGHT,
    ARMOR_CLASS_HEAVY,
]

ARCHETYPE_CLASSLESS = ''

ARCHETYPE_WARRIOR = 'warrior'

ARCHETYPE_ASSASSIN = 'assassin'

ARCHETYPE_MAGE = 'mage'

ARCHETYPE_CLERIC = 'cleric'

ARCHETYPES = [
    ARCHETYPE_CLASSLESS,
    ARCHETYPE_WARRIOR,
    ARCHETYPE_ASSASSIN,
    ARCHETYPE_MAGE,
    ARCHETYPE_CLERIC,
]

ATTR_CON = 'constitution'

ATTR_STR = 'strength'

ATTR_DEX = 'dexterity'

ATTR_INT = 'intelligence'

ATTR_DODGE = 'dodge'

ATTR_RESILIENCE = 'resilience'

ATTR_AP = 'attack_power'

ATTR_SP = 'spell_power'

ATTR_CRIT = 'crit'

ATTR_MAX_HEALTH = 'health_max'

ATTR_REGEN_HEALTH = 'health_regen'

ATTR_MAX_MANA = 'mana_max'

ATTR_REGEN_MANA = 'mana_regen'

ATTR_MAX_STAMINA = 'stamina_max'

ATTR_REGEN_STAMINA = 'stamina_regen'

ATTRIBUTES = [
    ATTR_CON,
    ATTR_DEX,
    ATTR_INT,
    ATTR_STR,
    ATTR_AP,
    ATTR_SP,
    ATTR_CRIT,
    ATTR_DODGE,
    ATTR_RESILIENCE,
    ATTR_MAX_HEALTH,
    ATTR_MAX_MANA,
    ATTR_MAX_STAMINA,
    ATTR_REGEN_HEALTH,
    ATTR_REGEN_MANA,
    ATTR_REGEN_STAMINA,
]

PRIMARY_ATTRIBUTES = [
    ATTR_CON,
    ATTR_STR,
    ATTR_DEX,
    ATTR_INT,
]

ATTR_BUDGET = {
    # 100 pts
    ATTR_REGEN_STAMINA: 100,
    # 45 pts
    ATTR_MAX_STAMINA: 45,
    # 40 pts
    ATTR_REGEN_HEALTH: 40,
    ATTR_REGEN_MANA: 40,
    # 10 pts
    ATTR_CON: 10,
    ATTR_STR: 10,
    ATTR_DEX: 10,
    ATTR_INT: 10,
    # 4 pts
    ATTR_MAX_HEALTH: 4,
    ATTR_MAX_MANA: 4,
    ATTR_AP: 4,
    ATTR_SP: 4,
    ATTR_CRIT: 4,
    ATTR_RESILIENCE: 4,
    ATTR_DODGE: 4,
}

MAP_DIMENSIONS = dict( # Radii
    X=4,
    Y=4,
    Z=1
)

REWARD_TYPE_ITEM = 'item'

REWARD_TYPE_EXP = 'exp'

REWARD_TYPE_GOLD = 'gold'

REWARD_TYPE_FACTION = 'faction'

REWARD_TYPE_GLORY = 'glory'

REWARD_TYPE_CURRENCY = 'currency'

REWARD_TYPES = [
    REWARD_TYPE_ITEM,
    REWARD_TYPE_EXP,
    REWARD_TYPE_GOLD,
    REWARD_TYPE_FACTION,
    REWARD_TYPE_GLORY,
    REWARD_TYPE_CURRENCY,
]

OBJECTIVE_TYPE_ITEM = 'item'

OBJECTIVE_TYPE_MOB = 'mob'

OBJECTIVE_TYPE_GOLD = 'gold'

OBJECTIVE_TYPE_GLORY = 'glory'

OBJECTIVE_TYPE_MEDALS = 'medals'

OBJECTIVE_TYPE_CURRENCY = 'currency'

OBJECTIVE_TYPES = [
    OBJECTIVE_TYPE_ITEM,
    OBJECTIVE_TYPE_MOB,
    OBJECTIVE_TYPE_GOLD,
    OBJECTIVE_TYPE_GLORY,
    OBJECTIVE_TYPE_MEDALS,
    OBJECTIVE_TYPE_CURRENCY,
]

FACTION_CORE_HUMAN = 'human'

DEATH_MODE_LOSE_ALL = 'lose_all'

DEATH_MODE_LOSE_NONE = 'lose_none'

DEATH_MODE_LOSE_EQ = 'lose_eq'

DEATH_MODE_LOSE_GOLD = 'lose_gold'

DEATH_MODE_LOSE_INV = 'lose_inv'

DEATH_MODE_DESTROY_EQ = 'destroy_eq'

DEATH_MODES = [
    DEATH_MODE_LOSE_ALL,
    DEATH_MODE_LOSE_NONE,
    DEATH_MODE_LOSE_EQ,
    DEATH_MODE_DESTROY_EQ,
    DEATH_MODE_LOSE_GOLD,
    DEATH_MODE_LOSE_INV,
]

PVP_MODE_FFA = 'free_for_all'

PVP_MODE_DISABLED = 'disabled'

PVP_MODE_ZONE = 'zone'

PVP_MODES = [
    PVP_MODE_FFA,
    PVP_MODE_DISABLED,
    PVP_MODE_ZONE,
]

MOB_REACTION_EVENT_ENTERING = 'enter'

MOB_REACTION_EVENT_SAYING = 'say'

MOB_REACTION_EVENT_RECEIVE = 'receive'

MOB_REACTION_EVENT_PERIODIC = 'periodic'

MOB_REACTION_EVENT_CONNECT = 'connect'

MOB_REACTION_EVENT_LOAD = 'load'

MOB_REACTION_EVENT_DEATH = 'death'

MOB_REACTION_EVENT_HEALTH = 'health'

MOB_REACTION_EVENT_SOCIAL = 'social'

MOB_REACTION_EVENT_COMBAT_ENTER = 'combat_enter'

MOB_REACTION_EVENT_COMBAT_EXIT = 'combat_exit'

MOB_REACTION_EVENT_NEW_ROOM = 'new_room'

MOB_REACTION_EVENT_NOTIFY = 'notify'

MOB_REACTION_EVENTS = [
    MOB_REACTION_EVENT_ENTERING,
    MOB_REACTION_EVENT_SAYING,
    MOB_REACTION_EVENT_RECEIVE,
    MOB_REACTION_EVENT_PERIODIC,
    MOB_REACTION_EVENT_CONNECT,
    MOB_REACTION_EVENT_LOAD,
    MOB_REACTION_EVENT_DEATH,
    MOB_REACTION_EVENT_HEALTH,
    MOB_REACTION_EVENT_SOCIAL,
    MOB_REACTION_EVENT_COMBAT_ENTER,
    MOB_REACTION_EVENT_COMBAT_EXIT,
    MOB_REACTION_EVENT_NEW_ROOM,
    MOB_REACTION_EVENT_NOTIFY,
]

MOB_REACTION_CONDITION_HAS_COMPLETED = 'has_completed'

MOB_REACTION_CONDITION_HAS_NOT_COMPLETED = 'has_not_completed'

MOB_REACTION_CONDITION_ABOVE_LEVEL = 'above_level'

MOB_REACTION_CONDITION_BELOW_LEVEL = 'below_level'

MOB_REACTION_CONDITIONS = [
    MOB_REACTION_CONDITION_HAS_COMPLETED,
    MOB_REACTION_CONDITION_HAS_NOT_COMPLETED,
    MOB_REACTION_CONDITION_ABOVE_LEVEL,
    MOB_REACTION_CONDITION_BELOW_LEVEL
]

# meant to be looked up by code in one-off situations
FEAT_TYPE_GENERIC = 'generic'
FEAT_TYPE_STAT_MOD = 'stat_mod'
FEAT_TYPE_ATTACK_MOD = 'attack_mod'
FEAT_TYPE_ATTACK_PROC = 'attack_proc'
FEAT_TYPE_SPELL_PROC = 'spell_proc'
FEAT_TYPE_KILL_PROC = 'kill_proc'
FEAT_TYPE_DEBUFF_DURATION = 'debuff_duration'
FEAT_TYPE_BASE_RESILIENCE = 'base_resilience'
FEAT_TYPE_ENEMY_ARMOR = 'enemy_armor'
FEAT_TYPE_SKILL_MOD = 'skill_mod'
FEAT_TYPE_SKILL = 'skill'
FEAT_TYPE_SKILL_USE_PROC = 'skill_use_proc'
FEAT_TYPE_HEAL_MOD = 'heal_mod'
FEAT_TYPE_DAMAGE_TAKEN = 'damage_taken'
FEAT_TYPES = [
    FEAT_TYPE_GENERIC,
    FEAT_TYPE_STAT_MOD,
    FEAT_TYPE_ATTACK_MOD,
    FEAT_TYPE_ATTACK_PROC,
    FEAT_TYPE_SPELL_PROC,
    FEAT_TYPE_KILL_PROC,
    FEAT_TYPE_DEBUFF_DURATION,
    FEAT_TYPE_BASE_RESILIENCE,
    FEAT_TYPE_ENEMY_ARMOR,
    FEAT_TYPE_SKILL_MOD,
    FEAT_TYPE_SKILL,
    FEAT_TYPE_SKILL_USE_PROC,
    FEAT_TYPE_HEAL_MOD,
    FEAT_TYPE_DAMAGE_TAKEN,
]

WORLD_STATE_ONLINE = 'online'

QUEST_TYPE_FETCH = 'fetch'

QUEST_TYPE_DELIVER = 'deliver'

QUEST_TYPES = [
    QUEST_TYPE_FETCH,
    QUEST_TYPE_DELIVER,
]

DEATH_ROUTE_TOP_FACTION = 'top_faction'

DEATH_ROUTE_NEAR_ROOM = 'near_room'

DEATH_ROUTE_NEAREST_IN_ZONE = 'nearest_in_zone'

DEATH_ROUTE_FAR_ROOM = 'far_room'

DEATH_ROUTES = [
    DEATH_ROUTE_TOP_FACTION,
    DEATH_ROUTE_NEAR_ROOM,
    DEATH_ROUTE_FAR_ROOM,
    DEATH_ROUTE_NEAREST_IN_ZONE,
]

DAMAGE_TYPE_PHYSICAL = 'physical'

DAMAGE_TYPE_MAGICAL = 'magical'

DAMAGE_TYPES = [
    DAMAGE_TYPE_PHYSICAL,
    DAMAGE_TYPE_MAGICAL,
]

SKILL_COST_TYPE_MANA = 'mana'

SKILL_COST_TYPE_STAMINA = 'stamina'

SKILL_COST_TYPE_HEALTH = 'health'

SKILL_COST_TYPES = [
    SKILL_COST_TYPE_HEALTH,
    SKILL_COST_TYPE_STAMINA,
    SKILL_COST_TYPE_MANA
]

SKILL_EFFECT_DOT = 'dot'

SKILL_EFFECT_HOT = 'hot'

SKILL_EFFECT_STUN = 'stun'

SKILL_EFFECT_SLEEP = 'sleep'

SKILL_EFFECT_ABSORB = 'absorb'

SKILL_EFFECT_BUFF = 'buff'

SKILL_EFFECT_DEBUFF = 'debuff'

SKILL_EFFECT_HASTE = 'haste'

SKILL_EFFECT_INVISIBLITY = 'invisibility'

SKILL_EFFECT_STEALTH = 'stealth'

SKILL_EFFECT_THORNS = 'thorns'

SKILL_EFFECT_SUMMON = 'summon'

SKILL_EFFECT_DISPEL = 'dispel'

SKILL_EFFECT_PURGE = 'purge'

SKILL_EFFECTS = [
    SKILL_EFFECT_DOT,
    SKILL_EFFECT_HOT,
    SKILL_EFFECT_STUN,
    SKILL_EFFECT_SLEEP,
    SKILL_EFFECT_ABSORB,
    SKILL_EFFECT_BUFF,
    SKILL_EFFECT_DEBUFF,
    SKILL_EFFECT_HASTE,
    SKILL_EFFECT_INVISIBLITY,
    SKILL_EFFECT_STEALTH,
    SKILL_EFFECT_THORNS,
    SKILL_EFFECT_SUMMON,
    SKILL_EFFECT_DISPEL,
    SKILL_EFFECT_PURGE,
]

SKILL_COST_CALC_FIXED = 'fixed'

SKILL_COST_CALC_PERC_BASE = 'perc_base'

SKILL_COST_CALC_PERC_MAX = 'perc_max'

SKILL_COST_CALCS = [
    SKILL_COST_CALC_FIXED,
    SKILL_COST_CALC_PERC_BASE,
    SKILL_COST_CALC_PERC_MAX,
]

SKILL_DAMAGE_CALC_NORMAL = 'normal'

SKILL_DAMAGE_CALC_FIXED = 'fixed'

SKILL_DAMAGE_CALCS = [
    SKILL_DAMAGE_CALC_NORMAL,
    SKILL_DAMAGE_CALC_FIXED,
]

SKILL_INTENT_DAMAGE = 'damage'

SKILL_INTENT_HEALING = 'healing'

SKILL_INTENT_SELF_HEALING = 'self_healing'

SKILL_INTENTS = [
    SKILL_INTENT_DAMAGE,
    SKILL_INTENT_HEALING,
    SKILL_INTENT_SELF_HEALING
]

CLAN_RANK_MEMBER = 'member'

CLAN_RANK_MASTER = 'master'

CLAN_RANKS = [
    CLAN_RANK_MEMBER,
    CLAN_RANK_MASTER,
]

ITEM_NAME_TYPE_CLOTH = 'cloth'
ITEM_NAME_TYPE_METAL = 'metal'
ITEM_NAME_TYPE_BLUNT = 'blunt'
ITEM_NAME_TYPE_BLADE = 'blade'
ITEM_NAME_TYPE_CASTER = 'caster'
