[tox]
envlist=py313
[testenv]
deps = -r{toxinidir}/requirements.txt
changedir = {toxinidir}/backend
setenv =
    PYTHONPATH = {toxinidir}
commands = python manage.py test --settings=config.settings.testing --noinput --parallel {env:TEST_PARALLEL:4} --buffer
