# Generated by Django 2.0.4 on 2018-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_introconfig_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOTChar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('config', models.TextField(default='{}')),
                ('is_brief', models.BooleanField(default=False)),
                ('is_builder', models.BooleanField(default=False)),
                ('last_connection_ts', models.DateTimeField(blank=True, null=True)),
                ('target', models.TextField(blank=True, default='')),
                ('aliases', models.TextField(blank=True, default='{}')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
