# Generated by Django 2.0.4 on 2018-06-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_wotchar'),
    ]

    operations = [
        migrations.AddField(
            model_name='wotchar',
            name='vars',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
