# Generated by Django 2.0.4 on 2018-07-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_wotchar_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='wotchar',
            name='triggers',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
