# Generated by Django 2.0.4 on 2018-07-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_wotchar_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='wotchar',
            name='config_profile',
            field=models.CharField(blank=True, choices=[('', '-----'), ('french', 'French')], max_length=100, null=True),
        ),
    ]
