# Generated by Django 2.0.4 on 2018-12-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_wotchar_config_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wotchar',
            name='disconnection_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
