# Generated by Django 2.0.4 on 2019-04-15 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_wotchar_disconnection_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOTEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('event_type', models.TextField(choices=[('login', 'Login'), ('logout', 'Logout')], default='login')),
                ('ip', models.TextField()),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='system.WOTChar')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
