# Generated by Django 2.0.4 on 2019-04-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_wotevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wotevent',
            name='ip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
