# Generated by Django 2.0.4 on 2019-05-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20190419_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOTWhoSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('ls_count', models.IntegerField()),
                ('ds_count', models.IntegerField()),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
