# Generated by Django 2.0.4 on 2020-05-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_wotwhosnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOTStruggleSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('ls', models.IntegerField()),
                ('ds', models.IntegerField()),
                ('ss', models.IntegerField()),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
