# Generated by Django 3.1.1 on 2020-10-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0066_playerconfig_buffer_length'),
        ('system', '0011_wotstrugglesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdeusUniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('run_ts', models.DateTimeField()),
                ('assassin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assassin_uniques', to='spawns.player')),
                ('cleric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleric_uniques', to='spawns.player')),
                ('mage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mage_uniques', to='spawns.player')),
                ('warrior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warrior_uniques', to='spawns.player')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
