# Generated by Django 3.2.10 on 2022-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20211228_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wotevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wotstrugglesnapshot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wotwhosnapshot',
            options={},
        ),
        migrations.AddIndex(
            model_name='wotevent',
            index=models.Index(fields=['created_ts'], name='system_wote_created_9a8d10_idx'),
        ),
        migrations.AddIndex(
            model_name='wotstrugglesnapshot',
            index=models.Index(fields=['created_ts'], name='system_wots_created_144a00_idx'),
        ),
        migrations.AddIndex(
            model_name='wotwhosnapshot',
            index=models.Index(fields=['created_ts'], name='system_wotw_created_717905_idx'),
        ),
    ]
