# Generated by Django 3.2.10 on 2023-07-12 17:02

from django.db import migrations, models


def add_prod_controls(apps, schema_editor):
    SiteControl = apps.get_model('system', 'SiteControl')
    SiteControl.objects.create(name='prod')

class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20220901_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.RunPython(add_prod_controls),
    ]
