# Generated by Django 3.2.10 on 2024-01-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_sitecontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nexus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('state', models.TextField(choices=[('absent', 'Absent'), ('building', 'Building'), ('ready', 'Ready')], default='absent')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
