# Generated by Django 3.2.10 on 2024-02-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_nexus'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexus',
            name='last_activity_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nexus',
            name='state',
            field=models.TextField(choices=[('absent', 'Absent'), ('building', 'Building'), ('ready', 'Ready'), ('deleting', 'Deleting'), ('error', 'Error')], default='absent'),
        ),
    ]
