# Generated by Django 3.2.10 on 2024-02-13 22:24
from datetime import timedelta

from django.db import migrations
from django.utils import timezone

from config import constants as api_consts

def cleanup_data(apps, schema_editor):
    # Your data migration logic here
    # Use apps.get_model('app_name', 'ModelName') to work with models
    World = apps.get_model('worlds', 'World')

    # Mark Edeus, the Cave and Arzjin as tier 3
    World.objects.filter(id=1).update(tier=3)
    World.objects.filter(id=217).update(tier=3)
    World.objects.filter(id=189614).update(tier=3)

    # Demigods is tier 2
    World.objects.filter(id=12).update(tier=2)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20240201_2236'),
    ]

    operations = [
        migrations.RunPython(cleanup_data),
    ]
