# Generated by Django 3.2.25 on 2024-04-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_cluster_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('ip', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
