# Generated by Django 3.2.25 on 2024-07-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_ipban'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexus',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
