# Generated by Django 3.2.25 on 2024-07-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_nexus_maintenance_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wotevent',
            name='char',
        ),
        migrations.DeleteModel(
            name='WOTStruggleSnapshot',
        ),
        migrations.DeleteModel(
            name='WOTWhoSnapshot',
        ),
        migrations.DeleteModel(
            name='WOTChar',
        ),
        migrations.DeleteModel(
            name='WOTEvent',
        ),
    ]
