# Generated by Django 3.2.25 on 2025-06-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_auto_20240714_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edeusuniques',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='edeusuniques',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ipban',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ipban',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='nexus',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='nexus',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sitecontrol',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sitecontrol',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
