# Generated by Django 3.2.25 on 2025-06-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_auto_20250611_1619'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS blog_posttag CASCADE;
                DROP TABLE IF EXISTS blog_post CASCADE;
                DROP TABLE IF EXISTS blog_tag CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
