# Generated by Django 3.2.25 on 2025-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_drop_blog_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontrol',
            name='platform_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
