# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('relative_id', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.TextField(choices=[('road', 'Road'), ('city', 'City'), ('indoor', 'Indoor'), ('field', 'Field'), ('mountain', 'Mountain'), ('forest', 'Forest'), ('desert', 'Desert'), ('water', 'Water')], default='indoor')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('is_landmark', models.BooleanField(default=False)),
                ('down', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='down_exits', to='worlds.Room')),
                ('east', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='east_exits', to='worlds.Room')),
                ('north', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='north_exits', to='worlds.Room')),
                ('south', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='south_exits', to='worlds.Room')),
                ('up', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='up_exits', to='worlds.Room')),
                ('west', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='west_exits', to='worlds.Room')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('state', models.TextField(choices=[('new', 'New'), ('loaded', 'Loaded'), ('running', 'Running'), ('stored', 'Stored')], default='new')),
                ('is_multiplayer', models.BooleanField(default=False)),
                ('last_loader_run_ts', models.DateTimeField(blank=True, null=True)),
                ('last_extraction_ts', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to=settings.AUTH_USER_MODEL)),
                ('builders', models.ManyToManyField(related_name='builder_for', through='builders.WorldBuilder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_ts',),
            },
        ),
        migrations.CreateModel(
            name='WorldConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('has_corpse_decay', models.BooleanField(default=True)),
                ('never_reload', models.BooleanField(default=False)),
                ('death_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='death_room_for', to='worlds.Room')),
                ('starting_eq', models.ManyToManyField(related_name='starter_for', to='builders.ItemTemplate')),
                ('starting_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='start_room_for', to='worlds.Room')),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('relative_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='worlds.World')),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
        migrations.AddField(
            model_name='world',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configured_worlds', to='worlds.WorldConfig'),
        ),
        migrations.AddField(
            model_name='world',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spawned_worlds', to='worlds.World'),
        ),
        migrations.AddField(
            model_name='room',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='worlds.World'),
        ),
        migrations.AddField(
            model_name='room',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='worlds.Zone'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together=set([('world', 'relative_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('world', 'x', 'y', 'z'), ('world', 'relative_id')]),
        ),
    ]
