# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 17:36
from __future__ import unicode_literals

from django.db import migrations


def migrate_room_types(apps, schema_editor):
    Room = apps.get_model('worlds', 'Room')
    Room.objects.filter(type='plains').update(type='forest')

class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_room_types),
    ]
