# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_auto_20170602_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='state',
            field=models.TextField(choices=[('new', 'New'), ('loaded', 'Loaded'), ('running', 'Running'), ('stored', 'Stored'), ('archived', 'Archived')], default='new'),
        ),
    ]
