# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_add_archived_world_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='state',
            field=models.TextField(choices=[('new', 'New'), ('initialized', 'Initialized'), ('running', 'Running'), ('stored', 'Stored'), ('archived', 'Archived')], default='new'),
        ),
    ]
