# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0004_auto_20170705_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
