# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0005_room_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('code', models.TextField(choices=[('no_ride', 'No_ride'), ('no_load', 'No_load'), ('no_roam_in', 'No_roam_in'), ('no_roam_out', 'No_roam_out'), ('no_light', 'No_light'), ('interest', 'Interest'), ('interest_exp', 'Interest_exp'), ('interest_water', 'Interest_water'), ('interest_horse', 'Interest_horse'), ('interest_choke', 'Interest_choke')])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='worlds.Room')),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
    ]
