# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0006_roomflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='full_map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
