# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0007_world_full_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='worlds.Room'),
        ),
    ]
