# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0008_room_transfer_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='can_create_chars',
            field=models.BooleanField(default=True),
        ),
    ]
