# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0009_worldconfig_can_create_chars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomflag',
            name='code',
            field=models.TextField(choices=[('no_ride', 'No_ride'), ('no_load', 'No_load'), ('no_roam', 'No_roam'), ('dark', 'Dark'), ('no_spell', 'No_spell'), ('peaceful', 'Peaceful'), ('interest', 'Interest')]),
        ),
    ]
