# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-20 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0010_auto_20171112_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='large_background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worldconfig',
            name='small_background',
            field=models.TextField(blank=True, null=True),
        ),
    ]
