# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0011_auto_20180220_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='autoflee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worldconfig',
            name='death_mode',
            field=models.TextField(choices=[('lose_all', 'Lose_all'), ('lose_none', 'Lose_none'), ('lose_two', 'Lose_two')], default='lose_none'),
        ),
    ]
