# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0012_auto_20180314_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='built_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
