# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-29 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0013_worldconfig_built_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='starting_gold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
