# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0014_worldconfig_starting_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='state',
            field=models.TextField(choices=[('new', 'New'), ('initialized', 'Initialized'), ('running', 'Running'), ('stored', 'Stored'), ('archived', 'Archived'), ('starting', 'Starting'), ('restarting', 'Restarting'), ('stopping', 'Stopping'), ('stopped', 'Stopped')], default='new'),
        ),
    ]
