# Generated by Django 2.0.4 on 2018-04-26 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0015_auto_20180413_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='worlds.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='worlds.Zone'),
        ),
        migrations.AlterField(
            model_name='world',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worlds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='world',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_worlds', to='worlds.WorldConfig'),
        ),
    ]
