# Generated by Django 2.0.4 on 2018-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0016_auto_20180426_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='flee_to_unknown_rooms',
            field=models.BooleanField(default=True),
        ),
    ]
