# Generated by Django 2.0.4 on 2018-05-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0017_worldconfig_flee_to_unknown_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='auto_start',
            field=models.BooleanField(default=False),
        ),
    ]
