# Generated by Django 2.0.4 on 2018-07-30 16:10

from django.db import migrations, models


def set_bane_of_bluefinch_not_auto_eq(apps, schema_editor):
    WorldConfig = apps.get_model('worlds', 'WorldConfig')
    WorldConfig.objects.filter(pk=2).update(auto_equip=False)

class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0020_auto_20180717_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='auto_equip',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_bane_of_bluefinch_not_auto_eq)
    ]
