# Generated by Django 2.0.4 on 2018-10-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0022_auto_20180904_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_warzone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_data',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
