# Generated by Django 2.0.4 on 2018-12-16 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0023_auto_20181012_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centers_for', to='worlds.Room'),
        ),
    ]
