# Generated by Django 2.0.4 on 2019-03-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0024_zone_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
