# Generated by Django 2.0.4 on 2019-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0025_world_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
