# Generated by Django 2.0.4 on 2019-04-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0026_zone_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.TextField(choices=[('road', 'Road'), ('city', 'City'), ('indoor', 'Indoor'), ('field', 'Field'), ('mountain', 'Mountain'), ('forest', 'Forest'), ('desert', 'Desert'), ('water', 'Water'), ('trail', 'Trail')], default='indoor'),
        ),
    ]
