# Generated by Django 2.0.4 on 2019-04-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0099_housingblock'),
        ('worlds', '0027_auto_20190406_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='housing_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_rooms', to='builders.HousingBlock'),
        ),
        migrations.AddField(
            model_name='room',
            name='ownership_type',
            field=models.TextField(choices=[('private', 'Private'), ('public', 'Public')], default='private'),
        ),
    ]
