# Generated by Django 2.0.4 on 2019-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0028_auto_20190415_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomflag',
            name='code',
            field=models.TextField(choices=[('no_ride', 'No_ride'), ('no_load', 'No_load'), ('no_roam', 'No_roam'), ('dark', 'Dark'), ('no_spell', 'No_spell'), ('peaceful', 'Peaceful'), ('interest', 'Interest'), ('fountain', 'Fountain'), ('trainer', 'Trainer'), ('inn', 'Inn'), ('exp', 'Exp'), ('horse', 'Horse'), ('shop', 'Shop'), ('food', 'Food'), ('choke', 'Choke'), ('smob', 'Smob'), ('action', 'Action'), ('herb', 'Herb'), ('workshop', 'Workshop')]),
        ),
    ]
