# Generated by Django 2.0.4 on 2019-08-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0029_auto_20190520_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldconfig',
            name='death_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='death_room_for', to='worlds.Room'),
        ),
        migrations.AlterField(
            model_name='worldconfig',
            name='starting_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_room_for', to='worlds.Room'),
        ),
    ]
