# Generated by Django 2.0.4 on 2019-09-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0030_auto_20190829_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='can_select_faction',
            field=models.BooleanField(default=True),
        ),
    ]
