# Generated by Django 2.0.4 on 2019-10-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0031_worldconfig_can_select_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='allow_combat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worldconfig',
            name='allow_pvp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worldconfig',
            name='death_route',
            field=models.TextField(choices=[('top_faction', 'Top_faction'), ('near_room', 'Near_room'), ('far_room', 'Far_room')], default='top_faction'),
        ),
        migrations.AddField(
            model_name='worldconfig',
            name='players_can_set_title',
            field=models.BooleanField(default=True),
        ),
    ]
