# Generated by Django 2.0.4 on 2019-10-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0033_roomdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
