# Generated by Django 2.0.4 on 2019-10-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0034_roomdetail_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldconfig',
            name='death_route',
            field=models.TextField(choices=[('top_faction', 'Top_faction'), ('near_room', 'Near_room'), ('far_room', 'Far_room'), ('nearest_in_zone', 'Nearest_in_zone')], default='top_faction'),
        ),
    ]
