# Generated by Django 2.0.4 on 2019-12-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0119_auto_20191209_1312'),
        ('worlds', '0035_auto_20191024_0022'),
    ]

    operations = [
        # `WorldConfig.starting_eq` was initially introduced as a normal M2M in
        # 0001, which already creates `worlds_worldconfig_starting_eq` in the
        # database. Keep this migration as state-only so fresh clones do not
        # attempt to recreate the table.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='WorldsWorldconfigStartingEq',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('itemtemplate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='builders.ItemTemplate')),
                    ],
                    options={
                        'db_table': 'worlds_worldconfig_starting_eq',
                    },
                ),
                # migrations.AlterField(
                #     model_name='worldconfig',
                #     name='starting_eq',
                #     field=models.ManyToManyField(related_name='starter_for', through='worlds.WorldsWorldconfigStartingEq', to='builders.ItemTemplate'),
                # ),
                migrations.AddField(
                    model_name='worldsworldconfigstartingeq',
                    name='worldconfig',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worlds.WorldConfig'),
                ),
                migrations.AlterUniqueTogether(
                    name='worldsworldconfigstartingeq',
                    unique_together={('worldconfig', 'itemtemplate')},
                ),
            ],
        ),
    ]
