# Generated by Django 2.0.4 on 2019-12-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0119_auto_20191209_1312'),
        ('worlds', '0036_auto_20191221_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldsWorldconfigStartingEq',
            new_name='StartingEq',
        ),
    ]
