# Generated by Django 2.0.4 on 2019-12-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0037_auto_20191221_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='startingeq',
            name='archetype',
            field=models.TextField(blank=True, choices=[('warrior', 'Warrior'), ('assassin', 'Assassin'), ('mage', 'Mage'), ('cleric', 'Cleric')], null=True),
        ),
    ]
