# Generated by Django 2.0.4 on 2019-12-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0038_startingeq_archetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='startingeq',
            name='num',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
