# Generated by Django 2.0.4 on 2019-12-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0039_startingeq_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startingeq',
            name='itemtemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builders.ItemTemplate'),
        ),
        migrations.AlterField(
            model_name='startingeq',
            name='worldconfig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.WorldConfig'),
        ),
    ]
