# Generated by Django 2.0.4 on 2020-03-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0123_itemtemplate_currency'),
        ('worlds', '0040_auto_20191221_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('direction', models.TextField(choices=[('north', 'North'), ('east', 'East'), ('south', 'South'), ('west', 'West'), ('up', 'Up'), ('down', 'Down')])),
                ('name', models.TextField(default='door')),
                ('destroy_key', models.BooleanField(default=False)),
                ('default_state', models.TextField(choices=[('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], default='closed')),
                ('current_state', models.TextField(default='closed')),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors_from', to='worlds.Room')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_doors', to='builders.ItemTemplate')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors_to', to='worlds.Room')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
