# Generated by Django 2.0.4 on 2020-03-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0041_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='respawn_wait',
            field=models.IntegerField(default=300),
        ),
    ]
