# Generated by Django 2.0.4 on 2020-04-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0042_zone_respawn_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='last_respawn_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
