# Generated by Django 2.0.4 on 2020-04-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0043_zone_last_respawn_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.TextField(choices=[('road', 'Road'), ('city', 'City'), ('indoor', 'Indoor'), ('field', 'Field'), ('mountain', 'Mountain'), ('forest', 'Forest'), ('desert', 'Desert'), ('water', 'Water'), ('shallow', 'Shallow'), ('trail', 'Trail')], default='indoor'),
        ),
    ]
