# Generated by Django 3.0.6 on 2020-05-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0044_auto_20200405_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='current_state',
        ),
    ]
