# Generated by Django 3.0.6 on 2020-05-21 17:36

from django.db import migrations, models

from config import constants as adv_consts

def translate_pvp_preference(apps, schema_editor):
    WorldConfig = apps.get_model('worlds', 'WorldConfig')
    WorldConfig.objects.filter(
        allow_pvp=False
    ).update(pvp_mode=adv_consts.PVP_MODE_DISABLED)


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0045_remove_door_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='pvp_mode',
            field=models.TextField(choices=[('free_for_all', 'Free_for_all'), ('disabled', 'Disabled'), ('zone', 'Zone')], default='free_for_all'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pvp_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(translate_pvp_preference)
    ]
