# Generated by Django 3.0.6 on 2020-05-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0046_auto_20200521_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='can_select_gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worldconfig',
            name='default_gender',
            field=models.TextField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non_binary')], default='female'),
        ),
    ]
