# Generated by Django 3.0.6 on 2020-05-30 16:30

from django.db import migrations, models


def set_is_narrative(apps, schema_editor):
    WorldConfig = apps.get_model('worlds', 'WorldConfig')
    WorldConfig.objects.filter(
        allow_combat=False
    ).update(is_narrative=True)


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0047_auto_20200530_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='is_narrative',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_is_narrative),
    ]
