# Generated by Django 3.0.6 on 2020-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0048_worldconfig_is_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='death_gold_penalty',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='worldconfig',
            name='death_mode',
            field=models.TextField(choices=[('lose_all', 'Lose_all'), ('lose_none', 'Lose_none'), ('lose_eq', 'Lose_eq'), ('lose_gold', 'Lose_gold')], default='lose_none'),
        ),
    ]
