# Generated by Django 3.1.1 on 2020-10-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0049_auto_20200612_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='facts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
