# Generated by Django 3.1.1 on 2020-12-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0050_world_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='is_classless',
            field=models.BooleanField(default=False),
        ),
    ]
