# Generated by Django 3.1.1 on 2021-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0051_worldconfig_classless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startingeq',
            name='archetype',
            field=models.TextField(blank=True, choices=[('', ''), ('warrior', 'Warrior'), ('assassin', 'Assassin'), ('mage', 'Mage'), ('cleric', 'Cleric')], null=True),
        ),
    ]
