# Generated by Django 3.1.1 on 2021-02-25 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0052_auto_20210115_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='instance_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='worlds.world'),
        ),
    ]
