# Generated by Django 3.1.1 on 2021-02-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0053_world_instance_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='enters_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrances', to='worlds.world'),
        ),
    ]
