# Generated by Django 3.1.1 on 2021-03-05 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0054_room_enters_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='exits_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exits_for', to='worlds.room'),
        ),
    ]
