# Generated by Django 3.1.1 on 2021-03-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0055_worldconfig_exits_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='exits_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_exits_for', to='worlds.room'),
        ),
    ]
