# Generated by Django 3.1.1 on 2021-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0056_room_exits_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='tier',
            field=models.IntegerField(default=1),
        ),
    ]
