# Generated by Django 3.2.10 on 2022-03-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0058_auto_20211228_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='name_exclusions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
