# Generated by Django 3.2.10 on 2022-09-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0059_worldconfig_name_exclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='no_start',
            field=models.BooleanField(default=False),
        ),
    ]
