# Generated by Django 3.2.10 on 2022-11-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0060_world_no_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
