# Generated by Django 3.2.10 on 2023-08-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0062_worldurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='change_state_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='state',
            field=models.TextField(choices=[('new', 'New'), ('initialized', 'Initialized'), ('running', 'Running'), ('stored', 'Stored'), ('archived', 'Archived'), ('starting', 'Starting'), ('restarting', 'Restarting'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('queued', 'Queued')], default='new'),
        ),
    ]
