# Generated by Django 3.2.10 on 2024-01-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0063_auto_20230818_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='non_ascii_names',
            field=models.BooleanField(default=False),
        ),
    ]
