# Generated by Django 3.2.10 on 2024-02-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0173_alter_path_rooms'),
        ('worlds', '0064_worldconfig_non_ascii_names'),
    ]

    # AlterField on M2M with through= is not supported in Django 4+
    # This was a no-op migration anyway (field unchanged), so we skip it
    operations = []
