# Generated by Django 3.2.10 on 2024-01-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0065_alter_worldconfig_starting_eq'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='world',
            name='maintenance_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
