# Generated by Django 3.2.10 on 2024-01-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0066_maintenance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='is_clean',
            field=models.BooleanField(default=False),
        ),
    ]
