# Generated by Django 3.2.10 on 2024-01-29 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_nexus'),
        ('worlds', '0067_world_is_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='nexus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worlds', to='system.nexus'),
        ),
    ]
