# Generated by Django 3.2.10 on 2024-03-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0068_world_nexus'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='clan_registration_cost',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
