# Generated by Django 3.2.25 on 2024-05-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0069_worldconfig_clan_registration_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='clean_start_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
