# Generated by Django 3.2.25 on 2024-06-03 23:43

from django.db import migrations, models
import django.db.models.deletion


def create_locks_tables(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    WorldLocks = apps.get_model('worlds', 'WorldLocks')

    for world in World.objects.filter(context__isnull=False):
        WorldLocks.objects.create(world=world, clean_start_ts=None)


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0070_world_clean_start_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldLocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('clean_start_ts', models.DateTimeField(blank=True, null=True)),
                ('world', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.RunPython(create_locks_tables),
    ]
