# Generated by Django 3.2.25 on 2024-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0071_worldlocks')
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='save_start_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
