# Generated by Django 3.2.25 on 2024-07-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0072_world_save_start_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='motd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
