# Generated by Django 3.2.25 on 2024-07-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0073_world_motd'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='decay_glory',
            field=models.BooleanField(default=False),
        ),
    ]
