# Generated by Django 3.2.25 on 2024-08-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0091_mob_pending_deletion_ts'),
        ('worlds', '0074_worldconfig_decay_glory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_instances', to='worlds.world')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_instances', to='spawns.player')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
