# Generated by Django 3.2.25 on 2024-08-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0075_instanceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceassignment',
            name='transfer_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from_instances', to='worlds.room'),
        ),
    ]
