# Generated by Django 3.2.25 on 2024-08-27 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0091_mob_pending_deletion_ts'),
        ('worlds', '0076_instanceassignment_transfer_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceassignment',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_instances', to='spawns.player'),
        ),
    ]
