# Generated by Django 3.2.25 on 2024-09-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0077_instanceassignment_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldconfig',
            name='death_mode',
            field=models.TextField(choices=[('lose_all', 'Lose_all'), ('lose_none', 'Lose_none'), ('lose_eq', 'Lose_eq'), ('destroy_eq', 'Destroy_eq'), ('lose_gold', 'Lose_gold')], default='lose_none'),
        ),
    ]
