# Generated by Django 3.2.25 on 2024-09-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0078_alter_worldconfig_death_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='last_entered_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
