# Generated by Django 3.2.25 on 2024-10-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0079_world_last_entered_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='cross_race_cooldown',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
