# Generated by Django 3.2.25 on 2024-12-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0080_worldconfig_cross_race_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='state',
            field=models.TextField(choices=[('new', 'New'), ('initialized', 'Initialized'), ('running', 'Running'), ('stored', 'Stored'), ('archived', 'Archived'), ('starting', 'Starting'), ('restarting', 'Restarting'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('queued', 'Queued')], db_index=True, default='new'),
        ),
    ]
