# Generated by Django 3.2.25 on 2025-01-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0082_alter_roomflag_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='instance_ref',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
