# Generated by Django 3.2.25 on 2025-01-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0105_rename_currency_fk_item_currency'),
        ('worlds', '0083_world_instance_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceassignment',
            name='member_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_for', to='spawns.player'),
        ),
    ]
