# Generated by Django 3.2.25 on 2025-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0085_auto_20250611_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='globals_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='worldconfig',
            name='death_mode',
            field=models.TextField(choices=[('lose_all', 'Lose_all'), ('lose_none', 'Lose_none'), ('lose_eq', 'Lose_eq'), ('destroy_eq', 'Destroy_eq'), ('lose_gold', 'Lose_gold'), ('lose_inv', 'Lose_inv')], default='lose_none'),
        ),
    ]
