# Generated by Django 3.2.25 on 2025-06-11 18:30

from django.db import migrations, models


def map_world_lifecycle(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    valid_lifecycles = [
        'new',
        'starting',
        'running',
        'stopping',
        'stopped',
    ]
    World.objects.exclude(lifecycle__in=valid_lifecycles).update(
        lifecycle='stopped')


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0086_auto_20250611_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='state',
            new_name='lifecycle',
        ),
        migrations.RunPython(
            map_world_lifecycle,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='world',
            name='lifecycle',
            field=models.TextField(
                choices=[
                    ('new', 'New'),
                    ('starting', 'Starting'),
                    ('running', 'Running'),
                    ('stopping', 'Stopping'),
                    ('stopped', 'Stopped'),
                ],
                default='new',
                db_index=True,
            ),
        ),
    ]
