# Generated by Django 3.2.25 on 2026-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0087_world_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='lifecycle_change_ts',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
