# Generated by Django 3.2.25 on 2026-01-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0088_world_lifecycle_change_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='last_played_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
