# Generated by Django 2.0.4 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0206_state_only_room_checks_and_paths'),
        ('worlds', '0089_world_last_played_ts'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='worldconfig',
                    name='starting_eq',
                    field=models.ManyToManyField(
                        related_name='starter_for',
                        through='worlds.StartingEq',
                        to='builders.ItemTemplate',
                    ),
                ),
            ],
        ),
    ]
