# Generated by Django 5.2.12 on 2026-04-03 21:17

import json
import django.db.models.deletion
from django.db import migrations, models


def _safe_object(raw_value):
    if isinstance(raw_value, dict):
        return raw_value
    if not raw_value:
        return {}
    try:
        parsed = json.loads(raw_value)
    except (TypeError, ValueError):
        return {}
    if isinstance(parsed, dict):
        return parsed
    return {}


def backfill_scoped_state(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    Zone = apps.get_model('worlds', 'Zone')
    WorldState = apps.get_model('worlds', 'WorldState')
    ZoneState = apps.get_model('worlds', 'ZoneState')

    for world in World.objects.all().iterator():
        data = _safe_object(getattr(world, 'facts', None))
        if not data:
            continue
        WorldState.objects.update_or_create(
            world=world,
            defaults={'data': data},
        )

    for zone in Zone.objects.all().iterator():
        data = _safe_object(getattr(zone, 'zone_data', None))
        if not data:
            continue
        ZoneState.objects.update_or_create(
            zone=zone,
            defaults={'data': data},
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0090_state_only_worldconfig_starting_eq'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', models.JSONField(default=dict)),
                ('version', models.BigIntegerField(default=0)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_state', to='worlds.room')),
            ],
            options={
                'ordering': ['room_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', models.JSONField(default=dict)),
                ('version', models.BigIntegerField(default=0)),
                ('world', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_state', to='worlds.world')),
            ],
            options={
                'ordering': ['world_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', models.JSONField(default=dict)),
                ('version', models.BigIntegerField(default=0)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_state', to='worlds.zone')),
            ],
            options={
                'ordering': ['zone_id'],
                'abstract': False,
            },
        ),
        migrations.RunPython(backfill_scoped_state, noop_reverse),
    ]
