# Generated by Django 5.2.13 on 2026-05-18 21:09

import core.stat_system
from django.db import migrations, models


def seed_blank_stat_systems(apps, schema_editor):
    WorldConfig = apps.get_model('worlds', 'WorldConfig')
    default_stat_system = core.stat_system.default_stat_system()
    for config in WorldConfig.objects.all().iterator():
        if not config.stat_system:
            config.stat_system = default_stat_system
            config.save(update_fields=['stat_system'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0098_stats_attributes_naming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldconfig',
            name='stat_system',
            field=models.JSONField(default=core.stat_system.default_stat_system),
        ),
        migrations.RunPython(seed_blank_stat_systems, noop),
    ]
