# Generated by Django 5.2.14 on 2026-07-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0106_worldconfig_default_roam_chance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='startingeq',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='startingeq',
            name='itemtemplate',
        ),
        migrations.RemoveField(
            model_name='startingeq',
            name='worldconfig',
        ),
        migrations.RemoveField(
            model_name='worldconfig',
            name='starting_eq',
        ),
        migrations.AddField(
            model_name='worldconfig',
            name='starting_equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='StartingEq',
        ),
    ]
