# Generated by Django 5.2.14 on 2026-07-06 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0237_remove_legacy_template_model_fks'),
        ('worlds', '0107_alter_startingeq_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='last_loader_run_ts',
            new_name='last_spawn_plan_run_ts',
        ),
        migrations.AlterField(
            model_name='door',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_doors', to='builders.itemdefinition'),
        ),
    ]
