# Generated by Django 5.2.14 on 2026-07-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0108_alter_door_key_itemdefinition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='is_warzone',
        ),
    ]
