# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0109_remove_zone_is_warzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='center',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='centers_for',
                to='worlds.room',
            ),
        ),
    ]
