# Generated by Django 5.2.16 on 2026-07-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0112_remove_worldconfig_allow_pvp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='instanceparticipant',
            new_name='worlds_inst_player__f8ff2e_idx',
            old_name='worlds_inst_player__289221_idx',
        ),
        migrations.RenameIndex(
            model_name='instanceparticipant',
            new_name='worlds_inst_run_id_2559a4_idx',
            old_name='worlds_inst_run_id_337547_idx',
        ),
        migrations.RenameIndex(
            model_name='instanceparticipant',
            new_name='worlds_inst_role_6d83a0_idx',
            old_name='worlds_inst_role_011083_idx',
        ),
        migrations.RenameIndex(
            model_name='instancerun',
            new_name='worlds_inst_status_d22b1d_idx',
            old_name='worlds_inst_status_d92411_idx',
        ),
        migrations.RenameIndex(
            model_name='instancerun',
            new_name='worlds_inst_ref_236858_idx',
            old_name='worlds_inst_ref_9f3c6d_idx',
        ),
        migrations.RenameIndex(
            model_name='instancerun',
            new_name='worlds_inst_base_wo_a91058_idx',
            old_name='worlds_inst_base_wo_a61353_idx',
        ),
        migrations.RenameIndex(
            model_name='instancerun',
            new_name='worlds_inst_templat_e84a94_idx',
            old_name='worlds_inst_templat_95f85d_idx',
        ),
        migrations.AlterField(
            model_name='instanceparticipant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instancerun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomflag',
            name='code',
            field=models.TextField(choices=[('no_ride', 'No_ride'), ('no_load', 'No_load'), ('no_roam', 'No_roam'), ('dark', 'Dark'), ('no_spell', 'No_spell'), ('peaceful', 'Peaceful'), ('interest', 'Interest'), ('fountain', 'Fountain'), ('trainer', 'Trainer'), ('inn', 'Inn'), ('exp', 'Exp'), ('horse', 'Horse'), ('shop', 'Shop'), ('food', 'Food'), ('choke', 'Choke'), ('smob', 'Smob'), ('action', 'Action'), ('herb', 'Herb'), ('no_quit', 'No_quit')]),
        ),
    ]
