# Generated by Django 5.2.16 on 2026-07-17 20:29

import django.db.models.deletion
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0246_mobcurrencyreward_worldstartingcurrencybalance_and_more'),
        ('worlds', '0114_room_crafting_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldconfig',
            name='death_gold_penalty',
        ),
        migrations.RemoveField(
            model_name='worldconfig',
            name='starting_gold',
        ),
        migrations.AddField(
            model_name='world',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='default_for_worlds', to='builders.currency'),
        ),
        migrations.AddField(
            model_name='world',
            name='economy_revision',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worldconfig',
            name='clan_registration_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clan_registration_policies', to='builders.currency'),
        ),
        migrations.AddField(
            model_name='worldconfig',
            name='death_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='death_policies', to='builders.currency'),
        ),
        migrations.AddField(
            model_name='worldconfig',
            name='death_currency_penalty',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.2'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='worldconfig',
            name='clan_registration_cost',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9007199254740991)]),
        ),
        migrations.AlterField(
            model_name='worldconfig',
            name='death_mode',
            field=models.TextField(
                choices=[
                    ('lose_all', 'Lose_all'),
                    ('lose_none', 'Lose_none'),
                    ('lose_eq', 'Lose_eq'),
                    ('destroy_eq', 'Destroy_eq'),
                    ('destroy_all', 'Destroy_all'),
                    ('lose_currency', 'Lose_currency'),
                    ('lose_inv', 'Lose_inv'),
                ],
                default='lose_none',
            ),
        ),
        migrations.AddConstraint(
            model_name='worldconfig',
            constraint=models.CheckConstraint(condition=models.Q(('death_currency_penalty__gte', 0), ('death_currency_penalty__lte', 1)), name='worlds_death_currency_penalty_rate'),
        ),
        migrations.AddConstraint(
            model_name='worldconfig',
            constraint=models.CheckConstraint(condition=models.Q(('clan_registration_cost__gte', 0), ('clan_registration_cost__lte', 9007199254740991)), name='worlds_clan_registration_cost_safe'),
        ),
    ]
