# Generated by Django 5.2.17 on 2026-09-06 02:04

from django.db import migrations, models


def retain_paused_clocks(apps, schema_editor):
    # Existing WR2 controlled runs use virtual deadlines. Keep them frozen
    # until the normal recovery/reconnect path can atomically rebase timers.
    Run = apps.get_model('worlds', 'InstanceRun')
    Run.objects.filter(time_control=True, simulation_time__isnull=False).update(
        time_paused=True, pause_in_combat=True,
    )
    Encounter = apps.get_model('spawns', 'CombatEncounter')
    from datetime import timedelta
    for run in Run.objects.filter(time_control=True).select_related('base_world__config').iterator():
        interval = run.base_world.config.combat_resolution_interval
        Encounter.objects.filter(world_id=run.spawned_world_id, status='active').update(
            resolution_interval=interval,
            next_resolution_ts=(run.simulation_time + timedelta(seconds=max(0, interval))
                                if run.simulation_time and interval >= 0 else None),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0164_instance_clock_work'),
        ('worlds', '0131_instance_time_control'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='instancerun',
            name='worlds_run_clock_due_idx',
        ),
        migrations.RemoveField(
            model_name='instancerun',
            name='next_tick_at',
        ),
        migrations.RemoveField(
            model_name='instancerun',
            name='time_interval',
        ),
        migrations.RemoveField(
            model_name='instancerun',
            name='time_mode',
        ),
        migrations.AddField(
            model_name='instancerun',
            name='clock_offset_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='instancerun',
            name='pause_in_combat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instancerun',
            name='time_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='instancerun',
            index=models.Index(fields=['time_control', 'time_paused', 'status'], name='worlds_run_clock_pause_idx'),
        ),
        migrations.RunPython(retain_paused_clocks, migrations.RunPython.noop),
    ]
