# Generated by Django 5.2.17 on 2026-09-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0132_combat_pause_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfig',
            name='instance_goal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='InstanceGoalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_runtime_id', models.BigIntegerField(unique=True)),
                ('defeated_at', models.DateTimeField(null=True)),
                ('processed', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_members', to='worlds.instancerun')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceClearRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('template_name', models.TextField()),
                ('template_slug', models.TextField()),
                ('attempt_id', models.UUIDField(unique=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('clear_time_ms', models.PositiveBigIntegerField()),
                ('time_control', models.BooleanField(default=False)),
                ('goal_spec', models.JSONField(default=dict)),
                ('participants', models.JSONField(default=list)),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clear_records', to='worlds.instancerun')),
                ('template_world', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_clear_records', to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
                'indexes': [models.Index(fields=['template_world', 'time_control', 'clear_time_ms'], name='worlds_clear_ranking_idx')],
            },
        ),
    ]
