"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import datetime
import os

from corsheaders.defaults import default_headers


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.abspath(os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    '..'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',

    'builders.apps.BuildersConfig',
    'lobby.apps.LobbyConfig',
    'spawns.apps.SpawnsConfig',
    'system.apps.SystemConfig',
    'users.apps.UsersConfig',
    'worlds.apps.WorldsConfig',
]

RAVEN_CONFIG = {}


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_RATES': {
      'email': '2/min',
      'anon': '10/min',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'backend.config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ATOMIC_REQUESTS': True,
    }
}

TESTING = False

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ONE_DAY = 60 * 60 * 24 * 1
JWT_EXP = ONE_DAY * 7
JWT_REF = ONE_DAY * 14
SIMPLE_JWT = {
    'SIGNING_KEY': os.environ.get('JWT_SECRET'),
    'ALGORITHM': 'HS256',
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(seconds=JWT_EXP),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(seconds=JWT_REF),
    'AUTH_HEADER_TYPES': ('JWT', 'Bearer'),
}

LOGIN_LINK_TTL_SECONDS = 15 * 60

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# Custom Auth
AUTH_USER_MODEL = 'users.User'

# CORS
CORS_ORIGIN_ALLOW_ALL = True


CORS_ALLOW_HEADERS = default_headers + (
    'x-player-id',
)

# SES Integration / Email

AWS_ACCESS_KEY = os.environ.get('WR_AWS_ACCESS_KEY') #None
AWS_SECRET_KEY = os.environ.get('WR_AWS_SECRET_KEY') # None
SITE_BASE = os.environ.get('WR_SITE_BASE', 'http://localhost:5173')
SEND_EMAIL = False
# Whether, if SEND_EMAIL is False, to print the message that we would have
# wanted to mail if mail was enabled. Good to have a flag so we can turn it
# off in tests.
PRINT_UNSENT_EMAIL = True
SYSTEM_EMAIL_FROM = os.environ.get('SYSTEM_EMAIL_FROM', 'noreply@example.com')
SYSTEM_USER_EMAIL = os.environ.get('SYSTEM_USER_EMAIL', 'system@example.com')

MONITORING_EMAILS = [os.environ.get('MONITORING_EMAIL', '')] if os.environ.get('MONITORING_EMAIL') else []

AUTO_START_MPWS = False

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'realms_cache',
    }
}

USE_INJECTION = True
INJECTION_TIMESTAMPS = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = 'amqp://rabbitmq:5672'
CELERY_RESULT_BACKEND = 'redis://redis-celery:6379/0'

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')

#FORCE_SCRIPT_NAME = '/forge'

# Whether to integrate with an LLM for puzzle solving.
PUZZLE_LLM = False
