# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('name', models.TextField(default='Unnamed Item')),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.TextField(choices=[('equippable', 'Equippable'), ('consumable', 'Consumable'), ('light', 'Light'), ('container', 'Container'), ('key', 'Key'), ('inert', 'Inert'), ('corpse', 'Corpse')], default='inert')),
                ('quality', models.TextField(choices=[('normal', 'Normal'), ('imbued', 'Imbued'), ('enchanted', 'Enchanted')], default='normal')),
                ('is_boat', models.BooleanField(default=False)),
                ('equipment_type', models.TextField(blank=True, choices=[('weapon_1h', 'Weapon_1h'), ('weapon_2h', 'Weapon_2h'), ('shield', 'Shield'), ('head', 'Head'), ('body', 'Body'), ('arms', 'Arms'), ('hands', 'Hands'), ('waist', 'Waist'), ('legs', 'Legs'), ('feet', 'Feet')], null=True)),
                ('armor_class', models.TextField(choices=[('light', 'Light'), ('heavy', 'Heavy')], default='light')),
                ('weapon_grip', models.TextField(choices=[('one_hand', 'One_hand'), ('two_hands', 'Two_hands')], default='one_hand')),
                ('hit_msg_first', models.TextField(default='hit')),
                ('hit_msg_third', models.TextField(default='hits')),
                ('health_max', models.IntegerField(default=0)),
                ('health_regen', models.IntegerField(default=0)),
                ('mana_max', models.IntegerField(default=0)),
                ('mana_regen', models.IntegerField(default=0)),
                ('stamina_max', models.IntegerField(default=0)),
                ('stamina_regen', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('attack_power', models.IntegerField(default=0)),
                ('spell_power', models.IntegerField(default=0)),
                ('resilience', models.IntegerField(default=0)),
                ('dodge', models.IntegerField(default=0)),
                ('crit', models.IntegerField(default=0)),
                ('container_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('archetype', models.TextField(blank=True, choices=[('warrior', 'Warrior'), ('thief', 'Thief'), ('mage', 'Mage'), ('cleric', 'Cleric')], default='warrior', null=True)),
                ('gender', models.TextField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='female', null=True)),
                ('experience', models.IntegerField(default=1)),
                ('type', models.TextField(choices=[('humanoid', 'Humanoid'), ('beast', 'Beast'), ('unead', 'Unead'), ('plant', 'Plant')], default='beast')),
                ('exp_worth', models.PositiveIntegerField(default=1)),
                ('roaming_type', models.TextField(choices=[('all', 'All'), ('static', 'Static'), ('zone', 'Zone')], default='all')),
                ('alignment', models.IntegerField(default=0)),
                ('aggression', models.TextField(choices=[('passive', 'Passive'), ('all', 'All'), ('players', 'Players'), ('alignment:opposite', 'Alignment:opposite'), ('alignment:good', 'Alignment:good'), ('alignment:evil', 'Alignment:evil'), ('alignment:neutral', 'Alignment:neutral')], default='passive')),
                ('hit_msg_first', models.TextField(blank=True, default='hit')),
                ('hit_msg_third', models.TextField(blank=True, default='hits')),
                ('health_max', models.IntegerField(default=30)),
                ('health_regen', models.IntegerField(default=20)),
                ('stamina_max', models.IntegerField(default=50)),
                ('stamina_regen', models.IntegerField(default=20)),
                ('mana_max', models.IntegerField(default=1)),
                ('mana_regen', models.IntegerField(default=20)),
                ('armor', models.PositiveIntegerField(default=0)),
                ('dodge', models.PositiveIntegerField(default=0)),
                ('crit', models.PositiveIntegerField(default=0)),
                ('resilience', models.PositiveIntegerField(default=0)),
                ('attack_power', models.PositiveIntegerField(default=1)),
                ('spell_power', models.PositiveIntegerField(default=0)),
                ('drops_random_items', models.BooleanField(default=False)),
                ('num_items', models.PositiveIntegerField(default=1)),
                ('chance_normal', models.PositiveIntegerField(default=100)),
                ('chance_imbued', models.PositiveIntegerField(default=20)),
                ('chance_enchanted', models.PositiveIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('archetype', models.TextField(blank=True, choices=[('warrior', 'Warrior'), ('thief', 'Thief'), ('mage', 'Mage'), ('cleric', 'Cleric')], default='warrior', null=True)),
                ('gender', models.TextField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='female', null=True)),
                ('experience', models.IntegerField(default=1)),
                ('last_connection_ts', models.DateTimeField(blank=True, null=True)),
                ('in_game', models.BooleanField(default=False)),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='spawns.Equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
