# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
        ('builders', '0002_auto_20170426_1702'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spawns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='worlds.Room'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='viewed_rooms',
            field=models.ManyToManyField(related_name='visited_by', to='worlds.Room'),
        ),
        migrations.AddField(
            model_name='player',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='worlds.World'),
        ),
        migrations.AddField(
            model_name='mob',
            name='equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mob', to='spawns.Equipment'),
        ),
        migrations.AddField(
            model_name='mob',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobs', to='worlds.Room'),
        ),
        migrations.AddField(
            model_name='mob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builders.MobTemplate'),
        ),
        migrations.AddField(
            model_name='mob',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobs', to='worlds.World'),
        ),
        migrations.AddField(
            model_name='item',
            name='container_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='item',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builders.ItemTemplate'),
        ),
        migrations.AddField(
            model_name='item',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='worlds.World'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='arms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arms_equipped', to='spawns.Item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_equipped', to='spawns.Item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='feet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feet_equipped', to='spawns.Item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hands_equipped', to='spawns.Item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_equipped', to='spawns.Item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='legs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs_equipped', to='spawns.Item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='offhand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offhand_equipped', to='spawns.Item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='shoulders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoulders_equipped', to='spawns.Item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='waist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waist_equipped', to='spawns.Item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon_equipped', to='spawns.Item'),
        ),
    ]
