# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0002_auto_20170426_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='fights_back',
            field=models.BooleanField(default=True),
        ),
    ]
