# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0003_mob_fights_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hit_msg_first',
            field=models.TextField(blank=True, default='hit'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hit_msg_third',
            field=models.TextField(blank=True, default='hits'),
        ),
    ]
