# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
        ('builders', '0007_auto_20170515_1451'),
        ('spawns', '0004_auto_20170508_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCommandCheckState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('passed_ts', models.DateTimeField(blank=True, null=True)),
                ('cmd_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_cmd_check_states', to='builders.RoomCommandCheck')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_check_states', to='worlds.World')),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
    ]
