# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0005_roomcommandcheckstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='health',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mob',
            name='mana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mob',
            name='stamina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='mana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='stamina',
            field=models.IntegerField(default=0),
        ),
    ]
