# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0011_auto_20170615_1511'),
        ('spawns', '0006_auto_20170517_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('completion_ts', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_quests', to='spawns.Player')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_quests', to='builders.Quest')),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
        migrations.AlterField(
            model_name='mob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_mobs', to='builders.MobTemplate'),
        ),
    ]
