# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0007_auto_20170615_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='roaming_type',
            field=models.TextField(choices=[('all', 'All'), ('static', 'Static'), ('zone', 'Zone')], default='static'),
        ),
    ]
