# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0008_auto_20170622_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_pending_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
