# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0009_item_is_pending_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='container_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='container_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
