# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0010_auto_20170816_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='group_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='group_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
