# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0013_item_is_pickable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='room_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
