# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0008_room_transfer_to'),
        ('spawns', '0014_mob_room_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('name', 'world')]),
        ),
    ]
