# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0015_auto_20170919_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_immortal',
            field=models.BooleanField(default=False),
        ),
    ]
