# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0016_player_is_immortal'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mob',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
