# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0017_auto_20170927_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('match', models.TextField()),
                ('replacement', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='spawns.Player')),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
    ]
