# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0018_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
