# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0019_auto_20180112_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
