# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-26 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0020_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='glory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
