# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0021_player_glory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
