# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-13 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0022_auto_20180313_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mob',
            name='chance_enchanted',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='chance_imbued',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='chance_normal',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='drops_random_items',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='num_items',
        ),
    ]
