# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-22 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0023_auto_20180413_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.TextField(choices=[('equippable', 'Equippable'), ('consumable', 'Consumable'), ('light', 'Light'), ('container', 'Container'), ('key', 'Key'), ('inert', 'Inert'), ('corpse', 'Corpse'), ('trash', 'Trash'), ('quest', 'Quest')], default='inert'),
        ),
    ]
