# Generated by Django 2.0.4 on 2018-04-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0024_auto_20180422_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='container_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='item',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builders.ItemTemplate'),
        ),
        migrations.AlterField(
            model_name='mob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_mobs', to='builders.MobTemplate'),
        ),
    ]
