# Generated by Django 2.0.4 on 2018-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0026_mob_regen_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='health_regen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mob',
            name='mana_regen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mob',
            name='stamina_regen',
            field=models.IntegerField(default=0),
        ),
    ]
