# Generated by Django 2.0.4 on 2018-05-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0060_auto_20180504_1754'),
        ('spawns', '0027_auto_20180504_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builders.RandomItemProfile'),
        ),
    ]
