# Generated by Django 2.0.4 on 2018-05-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0028_item_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='use_abilities',
            field=models.BooleanField(default=False),
        ),
    ]
