# Generated by Django 2.0.4 on 2018-05-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0029_mob_use_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='aggression',
            field=models.TextField(choices=[('passive', 'Passive'), ('all', 'All'), ('players', 'Players'), ('normal', 'Normal')], default='passive'),
        ),
    ]
