# Generated by Django 2.0.4 on 2018-05-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0030_auto_20180510_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='language_proficiency',
            field=models.DecimalField(decimal_places=1, default='0.0', max_digits=2),
        ),
    ]
