# Generated by Django 2.0.4 on 2018-07-19 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0068_quest_complete_silently'),
        ('spawns', '0031_player_language_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTrophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('mob_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophy_entries', to='builders.MobTemplate')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophy_entries', to='spawns.Player')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
