# Generated by Django 2.0.4 on 2018-08-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0076_auto_20180826_1900'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('spawns', '0032_playertrophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='roams_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mob',
            name='roams_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='mob',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='builders.Rule'),
        ),
        migrations.AlterField(
            model_name='mob',
            name='roaming_type',
            field=models.TextField(choices=[('all', 'All'), ('static', 'Static'), ('zone', 'Zone'), ('path', 'Path')], default='static'),
        ),
    ]
