# Generated by Django 2.0.4 on 2018-09-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0033_auto_20180826_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
