# Generated by Django 2.0.4 on 2018-09-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0034_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='food_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.TextField(choices=[('equippable', 'Equippable'), ('consumable', 'Consumable'), ('food', 'Food'), ('light', 'Light'), ('container', 'Container'), ('key', 'Key'), ('inert', 'Inert'), ('corpse', 'Corpse'), ('trash', 'Trash'), ('quest', 'Quest')], default='inert'),
        ),
    ]
