# Generated by Django 2.0.4 on 2018-10-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0035_auto_20180921_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
