# Generated by Django 2.0.4 on 2018-10-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0036_mob_is_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='roam_chance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
