# Generated by Django 2.0.4 on 2018-10-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0038_mob_control_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mob',
            name='is_general',
        ),
    ]
