# Generated by Django 2.0.4 on 2019-01-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0039_remove_mob_is_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFlexSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('code', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex_skills', to='spawns.Player')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
