# Generated by Django 2.0.4 on 2019-05-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0041_playerfeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upgrade_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
