# Generated by Django 2.0.4 on 2019-06-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0043_playerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_persistent',
            field=models.BooleanField(default=False),
        ),
    ]
