# Generated by Django 2.0.4 on 2019-06-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0044_item_is_persistent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
