# Generated by Django 2.0.4 on 2019-07-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0045_item_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='builders.ItemTemplate'),
        ),
        migrations.AlterField(
            model_name='mob',
            name='type',
            field=models.TextField(choices=[('aberration', 'Aberration'), ('beast', 'Beast'), ('celestial', 'Celestial'), ('construct', 'Construct'), ('dragon', 'Dragon'), ('elemental', 'Elemental'), ('fey', 'Fey'), ('fiend', 'Fiend'), ('giant', 'Giant'), ('humanoid', 'Humanoid'), ('monstrosity', 'Monstrosity'), ('ooze', 'Ooze'), ('plant', 'Plant'), ('undead', 'Undead')], default='beast'),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='event',
            field=models.TextField(choices=[('login', 'Login'), ('logout', 'Logout'), ('complete', 'Complete'), ('create', 'Create')]),
        ),
    ]
