# Generated by Django 2.0.4 on 2019-08-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0105_auto_20190715_1641'),
        ('spawns', '0046_auto_20190715_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEnquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('enquire_ts', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_enquires', to='spawns.Player')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_enquires', to='builders.Quest')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
