# Generated by Django 2.0.4 on 2019-09-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0106_auto_20190829_2007'),
        ('spawns', '0047_playerenquire'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_rules', to='builders.Rule'),
        ),
    ]
