# Generated by Django 2.0.4 on 2019-10-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0048_item_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='is_invisible',
            field=models.BooleanField(default=False),
        ),
    ]
