# Generated by Django 2.0.4 on 2019-11-11 17:12

from django.db import migrations, models
from django.db.models import Q

from config import constants as adv_consts


def migrate_random_items(apps, schema_editor):
    Item = apps.get_model('spawns', 'Item')
    ItemTemplate = apps.get_model('builders', 'ItemTemplate')

    random_items = Item.objects.filter(
        template__isnull=True)

    # Swords
    random_items.filter(
        Q(name='a chipped shortsword')
        | Q(name='a heavy longsword')
        | Q(name='a honed broadsword')
        | Q(name='a glistening scimitar')
        | Q(name='a gleaming claymore')
    ).update(weapon_type=adv_consts.WEAPON_TYPE_SWORD)

    # Clubs
    random_items.filter(
        Q(name='a bronze-flanged mace')
        | Q(name='a brutal war maul')
    ).update(weapon_type=adv_consts.WEAPON_TYPE_CLUB)

    # Axes
    random_items.filter(
        name='a leather-hilted battleaxe'
    ).update(weapon_type=adv_consts.WEAPON_TYPE_AXE)

    # Staves
    random_items.filter(
        Q(name='a carved oaken staff')
        | Q(name='a staff of twisted sycamore')
        | Q(name='a faintly glowing greatstaff')
    ).update(weapon_type=adv_consts.WEAPON_TYPE_STAFF)

    # Daggers
    random_items.filter(
        Q(name='a sharp curved dagger')
    ).update(weapon_type=adv_consts.WEAPON_TYPE_DAGGER)

    # Spears
    random_items.filter(
        Q(name='a spear with a steel-bladed tip')
    ).update(weapon_type=adv_consts.WEAPON_TYPE_SPEAR)

    # Mattock
    random_items.filter(
        Q(name='a razor-sharp mattock')
    ).update(weapon_type=adv_consts.WEAPON_TYPE_POLEARM)

def migrate_item_templates(apps, schema_editor):
    ItemTemplate = apps.get_model('builders', 'ItemTemplate')

    ItemTemplate.objects.filter(
        name__icontains='sword'
    ).update(weapon_type=adv_consts.WEAPON_TYPE_SWORD)

    ItemTemplate.objects.filter(
        name__icontains='staff'
    ).update(weapon_type=adv_consts.WEAPON_TYPE_STAFF)

    ItemTemplate.objects.filter(
        name__icontains='axe'
    ).update(weapon_type=adv_consts.WEAPON_TYPE_AXE)

    ItemTemplate.objects.filter(
        name__icontains='club'
    ).update(weapon_type=adv_consts.WEAPON_TYPE_CLUB)

    ItemTemplate.objects.filter(
        name__icontains='spear'
    ).update(weapon_type=adv_consts.WEAPON_TYPE_SPEAR)

    ItemTemplate.objects.filter(
        name__icontains='dagger'
    ).update(weapon_type=adv_consts.WEAPON_TYPE_DAGGER)


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0050_auto_20191031_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weapon_type',
            field=models.TextField(blank=True, choices=[('sword', 'Sword'), ('axe', 'Axe'), ('club', 'Club'), ('spear', 'Spear'), ('staff', 'Staff')], null=True),
        ),
        migrations.RunPython(migrate_random_items),
        migrations.RunPython(migrate_item_templates),
    ]
