# Generated by Django 2.0.4 on 2019-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0051_item_weapon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weapon_type',
            field=models.TextField(blank=True, choices=[('sword', 'Sword'), ('axe', 'Axe'), ('club', 'Club'), ('spear', 'Spear'), ('staff', 'Staff'), ('polearm', 'Polearm'), ('dagger', 'Dagger')], null=True),
        ),
    ]
