# Generated by Django 2.0.4 on 2019-11-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0052_auto_20191121_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='archetype',
            field=models.TextField(blank=True, choices=[('warrior', 'Warrior'), ('assassin', 'Assassin'), ('mage', 'Mage'), ('cleric', 'Cleric')], default='warrior', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='archetype',
            field=models.TextField(blank=True, choices=[('warrior', 'Warrior'), ('assassin', 'Assassin'), ('mage', 'Mage'), ('cleric', 'Cleric')], default='warrior', null=True),
        ),
    ]
