# Generated by Django 2.0.4 on 2020-03-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0054_item_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.TextField(choices=[('gold', 'Gold'), ('medals', 'Medals')], default='gold'),
        ),
        migrations.AddField(
            model_name='player',
            name='medals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
