# Generated by Django 3.0.6 on 2020-05-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0055_auto_20200320_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='is_crafter',
            field=models.BooleanField(default=False),
        ),
    ]
