# Generated by Django 3.0.6 on 2020-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0056_mob_is_crafter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='craft_multiplier',
            field=models.FloatField(default=3),
        ),
    ]
