# Generated by Django 3.0.6 on 2020-05-20 18:21

from django.db import migrations, models
import django.db.models.deletion


def create_spw_door_states(apps, schema_editor):
    Door = apps.get_model('worlds', 'Door')
    DoorState = apps.get_model('spawns', 'DoorState')

    doors_qs = Door.objects.filter(
        from_room__world__is_multiplayer=False)
    for door in doors_qs:
        context_world = door.from_room.world
        for spawned_world in context_world.spawned_worlds.all():
            DoorState.objects.create(
                door=door,
                world=spawned_world,
                state=door.default_state)


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0044_auto_20200405_0035'),
        ('spawns', '0057_mob_craft_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], default='closed')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_states', to='worlds.Door')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_states', to='worlds.World')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.RunPython(create_spw_door_states),
    ]
