# Generated by Django 3.0.6 on 2020-06-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0059_auto_20200530_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='combat_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
