# Generated by Django 3.0.6 on 2020-06-06 15:08

from django.db import migrations, models
import django.db.models.deletion


def create_player_configs(apps, schema_editor):
    Player = apps.get_model('spawns', 'Player')
    PlayerConfig = apps.get_model('spawns', 'PlayerConfig')

    default_config = PlayerConfig.objects.create(
        room_brief=False,
        combat_brief=False)

    Player.objects.all().update(config=default_config)


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0060_mob_combat_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('room_brief', models.BooleanField(default=False)),
                ('combat_brief', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='spawns.PlayerConfig'),
        ),
        migrations.RunPython(create_player_configs),
    ]
