# Generated by Django 3.0.6 on 2020-07-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0061_auto_20200606_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='flags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
