# Generated by Django 3.0.6 on 2020-07-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0061_auto_20200606_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.TextField(choices=[('gold', 'Gold'), ('medal', 'Medal')], default='gold'),
        ),
    ]
