# Generated by Django 3.0.6 on 2020-07-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0063_mob_merchant_profit'),
        ('spawns', '0062_mob_flags'),
    ]

    operations = [
    ]
