# Generated by Django 3.0.6 on 2020-08-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0064_merge_20200724_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='skill_modifier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
