# Generated by Django 3.0.6 on 2020-08-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0065_item_skill_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerconfig',
            name='buffer_length',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
