# Generated by Django 3.1.1 on 2020-11-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0066_playerconfig_buffer_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerconfig',
            name='idle_logout',
            field=models.BooleanField(default=True),
        ),
    ]
