# Generated by Django 3.1.1 on 2021-01-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0067_playerconfig_idle_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.TextField(choices=[('equippable', 'Equippable'), ('consumable', 'Consumable'), ('food', 'Food'), ('light', 'Light'), ('container', 'Container'), ('key', 'Key'), ('inert', 'Inert'), ('corpse', 'Corpse'), ('trash', 'Trash'), ('quest', 'Quest'), ('ammunition', 'Ammunition')], default='inert'),
        ),
    ]
