# Generated by Django 3.1.1 on 2021-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0068_auto_20210112_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
