# Generated by Django 3.1.1 on 2021-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0069_auto_20210114_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='archetype',
            field=models.TextField(blank=True, choices=[('', ''), ('warrior', 'Warrior'), ('assassin', 'Assassin'), ('mage', 'Mage'), ('cleric', 'Cleric')], default='warrior'),
        ),
        migrations.AlterField(
            model_name='player',
            name='archetype',
            field=models.TextField(blank=True, choices=[('', ''), ('warrior', 'Warrior'), ('assassin', 'Assassin'), ('mage', 'Mage'), ('cleric', 'Cleric')], default='warrior'),
        ),
    ]
