# Generated by Django 3.1.1 on 2021-03-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0072_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weapon_type',
            field=models.TextField(blank=True, choices=[('sword', 'Sword'), ('axe', 'Axe'), ('club', 'Club'), ('spear', 'Spear'), ('staff', 'Staff'), ('polearm', 'Polearm'), ('dagger', 'Dagger'), ('bow', 'Bow'), ('gun', 'Gun')], null=True),
        ),
    ]
