# Generated by Django 3.1.1 on 2021-04-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0073_auto_20210324_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerconfig',
            name='display_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playerconfig',
            name='display_connect',
            field=models.BooleanField(default=False),
        ),
    ]
