# Generated by Django 3.2.10 on 2022-02-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0075_auto_20211228_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_action_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
