# Generated by Django 3.2.10 on 2022-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0076_player_last_action_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mute_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
