# Generated by Django 3.2.10 on 2022-05-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0077_player_mute_list'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['container_id'], name='spawns_item_contain_4ce544_idx'),
        ),
    ]
