# Generated by Django 3.2.10 on 2022-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0078_item_spawns_item_contain_4ce544_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['type'], name='spawns_item_type_bc0835_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_pending_deletion'], name='spawns_item_is_pend_63c972_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['container_type'], name='spawns_item_contain_61a5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_persistent'], name='spawns_item_is_pers_313559_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_ts'], name='spawns_item_created_b30799_idx'),
        ),
        migrations.AddIndex(
            model_name='mob',
            index=models.Index(fields=['created_ts'], name='spawns_mob_created_1d0794_idx'),
        ),
    ]
