# Generated by Django 3.2.10 on 2023-01-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0079_auto_20220901_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='is_pending_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
