# Generated by Django 3.2.10 on 2023-01-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0080_mob_is_pending_deletion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mob',
            index=models.Index(fields=['is_pending_deletion'], name='spawns_mob_is_pend_637a6e_idx'),
        ),
    ]
