# Generated by Django 3.2.10 on 2023-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0081_mob_spawns_mob_is_pend_637a6e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='aggression',
            field=models.TextField(choices=[('passive', 'Passive'), ('all', 'All'), ('players', 'Players'), ('normal', 'Normal'), ('friendly', 'Friendly')], default='passive'),
        ),
    ]
