# Generated by Django 3.2.10 on 2023-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0083_auto_20230807_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_invisible',
            field=models.BooleanField(default=False),
        ),
    ]
