# Generated by Django 3.2.10 on 2024-03-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0069_worldconfig_clan_registration_cost'),
        ('spawns', '0084_player_is_invisible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('password', models.TextField(blank=True, null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clans', to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='channels',
            field=models.TextField(blank=True, default='chat'),
        ),
        migrations.CreateModel(
            name='ClanMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('rank', models.TextField(choices=[('member', 'Member'), ('master', 'Master')], default='member')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spawns.clan')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_memberships', to='spawns.player')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
