# Generated by Django 3.2.25 on 2024-04-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0085_auto_20240303_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerevent',
            name='ip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
