# Generated by Django 3.2.25 on 2024-04-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0086_playerevent_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='nochat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='noplay',
            field=models.BooleanField(default=False),
        ),
    ]
