# Generated by Django 3.2.25 on 2024-05-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0087_auto_20240425_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pending_deletion_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
