# Generated by Django 3.2.25 on 2024-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0088_item_pending_deletion_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='save_start_ts',
            field=models.DateField(blank=True, null=True),
        ),
    ]
