# Generated by Django 3.2.25 on 2024-07-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0090_playerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='pending_deletion_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
