# Generated by Django 3.2.25 on 2024-09-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0091_mob_pending_deletion_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='traits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
