# Generated by Django 3.2.25 on 2024-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0092_mob_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerconfig',
            name='mobile_map_width',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
