# Generated by Django 3.2.25 on 2024-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0093_playerconfig_mobile_map_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pending_deletion_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
