# Generated by Django 3.2.25 on 2024-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0095_auto_20240912_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='upgrade_success_chance',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
