# Generated by Django 3.2.25 on 2024-09-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0096_alter_mob_upgrade_success_chance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mob',
            name='upgrade_success_chance',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='upgrade_success_cmd',
        ),
    ]
