# Generated by Django 3.2.25 on 2024-09-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0097_auto_20240917_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='augment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='augment_items', to='spawns.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='on_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.TextField(choices=[('equippable', 'Equippable'), ('consumable', 'Consumable'), ('food', 'Food'), ('light', 'Light'), ('container', 'Container'), ('key', 'Key'), ('inert', 'Inert'), ('corpse', 'Corpse'), ('trash', 'Trash'), ('quest', 'Quest'), ('ammunition', 'Ammunition'), ('augment', 'Augment')], default='inert'),
        ),
    ]
