# Generated by Django 3.2.25 on 2024-09-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0098_auto_20240922_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='on_use',
            new_name='on_use_cmd',
        ),
        migrations.AddField(
            model_name='item',
            name='on_use_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
