# Generated by Django 3.2.25 on 2024-09-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0099_auto_20240922_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_equipped', to='spawns.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='equipment_type',
            field=models.TextField(blank=True, choices=[('weapon_1h', 'Weapon_1h'), ('weapon_2h', 'Weapon_2h'), ('shield', 'Shield'), ('head', 'Head'), ('body', 'Body'), ('arms', 'Arms'), ('hands', 'Hands'), ('waist', 'Waist'), ('legs', 'Legs'), ('feet', 'Feet'), ('accessory', 'Accessory')], null=True),
        ),
    ]
