# Generated by Django 3.2.25 on 2024-09-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0100_auto_20240922_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cooldowns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
