# Generated by Django 3.2.25 on 2024-11-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0195_auto_20241122_1929'),
        ('spawns', '0102_item_on_use_equipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builders.currency'),
        ),
        migrations.AddField(
            model_name='player',
            name='currencies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
