# Generated by Django 3.2.25 on 2024-11-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0103_auto_20241122_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
    ]
