# Generated by Django 3.2.25 on 2024-11-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0104_remove_item_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='currency_fk',
            new_name='currency',
        ),
    ]
