# Generated by Django 3.2.25 on 2025-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0106_auto_20250611_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='effects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
