# Generated by Django 5.2.12 on 2026-04-03 21:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_character_state(apps, schema_editor):
    CharacterState = apps.get_model('spawns', 'CharacterState')
    Mark = apps.get_model('spawns', 'Mark')

    mark_map: dict[int, dict[str, str]] = {}
    for mark in Mark.objects.all().iterator():
        mark_map.setdefault(mark.player_id, {})[str(mark.name or '')] = mark.value

    for player_id, data in mark_map.items():
        if not data:
            continue
        CharacterState.objects.update_or_create(
            player_id=player_id,
            defaults={'data': data},
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0107_player_effects'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', models.JSONField(default=dict)),
                ('version', models.BigIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character_state_record', to='spawns.player')),
            ],
            options={
                'ordering': ['player_id'],
                'abstract': False,
            },
        ),
        migrations.RunPython(backfill_character_state, noop_reverse),
    ]
