# Generated by Django 5.2.12 on 2026-04-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0092_worldconfig_combat_resolution_interval'),
        ('spawns', '0108_characterstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.TextField(choices=[('active', 'Active'), ('finished', 'Finished')], db_index=True, default='active')),
                ('resolution_interval', models.FloatField(default=0)),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('next_resolution_ts', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_resolution_ts', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_encounters', to='spawns.mob')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_encounters', to='spawns.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_encounters', to='worlds.room')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_encounters', to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='combatencounter',
            index=models.Index(fields=['status', 'next_resolution_ts'], name='spawns_comb_status_731ded_idx'),
        ),
        migrations.AddIndex(
            model_name='combatencounter',
            index=models.Index(fields=['player', 'status'], name='spawns_comb_player__8f98ad_idx'),
        ),
        migrations.AddIndex(
            model_name='combatencounter',
            index=models.Index(fields=['mob', 'status'], name='spawns_comb_mob_id_de4421_idx'),
        ),
    ]
