# Generated by Django 5.2.13 on 2026-05-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0113_player_ability_hotkeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerflexskill',
            name='player',
        ),
        migrations.RemoveField(
            model_name='item',
            name='skill_modifier',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='teaches',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='teaching_conditions',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='unlearn_cost',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='unlearns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='skills',
        ),
        migrations.DeleteModel(
            name='PlayerFeat',
        ),
        migrations.DeleteModel(
            name='PlayerFlexSkill',
        ),
    ]
