# Generated by Django 5.2.12 on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spawns", "0121_rename_player_is_immortal_to_is_builder"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="state",
            field=models.TextField(
                choices=[
                    ("standing", "standing"),
                    ("resting", "resting"),
                    ("combat", "combat"),
                ],
                default="standing",
            ),
        ),
    ]
