# Generated by Codex on 2026-06-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0229_spawn_plans'),
        ('spawns', '0127_player_active_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='spawn_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='builders.spawnplacement'),
        ),
        migrations.AddField(
            model_name='mob',
            name='spawn_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobs', to='builders.spawnplacement'),
        ),
    ]
