# Generated by Django 5.2.14 on 2026-07-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0133_mob_loot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerenquire',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerenquire',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='playerquest',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerquest',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='playertrophy',
            name='mob_template',
        ),
        migrations.RemoveField(
            model_name='playertrophy',
            name='player',
        ),
        migrations.DeleteModel(
            name='PlayerEnquire',
        ),
        migrations.DeleteModel(
            name='PlayerQuest',
        ),
        migrations.DeleteModel(
            name='PlayerTrophy',
        ),
    ]
