# Generated by Django 5.2.14 on 2026-07-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0134_remove_playerenquire_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='item',
            name='template',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='mob',
            name='template',
        ),
    ]
