# Generated by Django 5.2.16 on 2026-07-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0140_delete_roomcommandcheckstate'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Migration 0138 renamed these indexes in PostgreSQL, but its
            # parallel migration branch did not retain the updated names in
            # the merged Django state. Synchronize state without renaming the
            # already-correct database indexes a second time.
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='merchantbuybackentry',
                    new_name='spawns_merc_status_3eb40a_idx',
                    old_name='spawns_merc_status_985e44_idx',
                ),
                migrations.RenameIndex(
                    model_name='merchantbuybackentry',
                    new_name='spawns_merc_created_6b63f2_idx',
                    old_name='spawns_merc_created_f04798_idx',
                ),
                migrations.RenameIndex(
                    model_name='merchantruntime',
                    new_name='spawns_merc_is_acti_74e933_idx',
                    old_name='spawns_merc_is_acti_b52214_idx',
                ),
                migrations.RenameIndex(
                    model_name='merchantruntime',
                    new_name='spawns_merc_next_re_81e3c7_idx',
                    old_name='spawns_merc_next_re_c8c461_idx',
                ),
                migrations.RenameIndex(
                    model_name='merchantstockentry',
                    new_name='spawns_merc_status_b5674d_idx',
                    old_name='spawns_merc_status_1b18bf_idx',
                ),
                migrations.RenameIndex(
                    model_name='merchantstockentry',
                    new_name='spawns_merc_bundle__880136_idx',
                    old_name='spawns_merc_bundle__606b91_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='food_type',
            field=models.TextField(blank=True, choices=[('stamina', 'Stamina'), ('energy', 'Energy'), ('health', 'Health')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.TextField(choices=[('standing', 'Standing'), ('resting', 'Resting'), ('combat', 'Combat')], default='standing'),
        ),
    ]
