# Generated by Django 5.2.16 on 2026-07-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0246_mobcurrencyreward_worldstartingcurrencybalance_and_more'),
        ('spawns', '0142_player_material_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mob',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='player',
            name='currencies',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='player',
            name='medals',
        ),
        migrations.AddField(
            model_name='player',
            name='wallet_revision',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerCurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_balances', to='builders.currency')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_balances', to='spawns.player')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('player', 'currency'), name='spawns_currency_balance_unique'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='spawns_currency_balance_nonnegative'), models.CheckConstraint(condition=models.Q(('amount__lte', 9007199254740991)), name='spawns_currency_balance_safe_integer')],
            },
        ),
    ]
