# Generated by Django 5.2.16 on 2026-07-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0246_mobcurrencyreward_worldstartingcurrencybalance_and_more'),
        ('spawns', '0143_remove_mob_gold_remove_player_currencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantbuybackentry',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='merchant_buyback_entries', to='builders.currency'),
        ),
        migrations.AddField(
            model_name='merchantruntime',
            name='settlement_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='merchant_runtimes', to='builders.currency'),
        ),
        migrations.AddField(
            model_name='merchantstockentry',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='merchant_stock_entries', to='builders.currency'),
        ),
        migrations.AddField(
            model_name='mob',
            name='currency_reward_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='builders.currency'),
        ),
        migrations.AlterField(
            model_name='merchantbuybackentry',
            name='buyback_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='merchantbuybackentry',
            name='sold_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='merchantruntime',
            name='remaining_purchase_budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchantstockentry',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='merchantruntime',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_purchase_budget__isnull', True), models.Q(('remaining_purchase_budget__gte', 0), ('remaining_purchase_budget__lte', 9007199254740991)), _connector='OR'), name='spawns_merchant_budget_safe'),
        ),
        migrations.AddConstraint(
            model_name='merchantstockentry',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('price__lte', 9007199254740991)), name='spawns_merchant_stock_price_safe'),
        ),
        migrations.AddConstraint(
            model_name='merchantbuybackentry',
            constraint=models.CheckConstraint(condition=models.Q(('buyback_price__gte', 0), ('buyback_price__lte', 9007199254740991), ('sold_price__gte', 0), ('sold_price__lte', 9007199254740991)), name='spawns_merchant_buyback_price_safe'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cost__isnull', True), ('currency__isnull', True)), models.Q(('cost__gte', 0), ('cost__lte', 9007199254740991), ('currency__isnull', False)), _connector='OR'), name='spawns_item_money_pair'),
        ),
    ]
