# Generated by Django 5.2.16 on 2026-07-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0144_merchantbuybackentry_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='profile',
        ),
    ]
