# Generated by Django 5.2.16 on 2026-07-18 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0145_remove_item_profile'),
        ('worlds', '0115_remove_worldconfig_death_gold_penalty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(condition=models.Q(('in_game', True)), fields=['world', 'room', 'id'], name='spawn_player_world_room_live'),
        ),
    ]
