# Generated by Django 5.2.16 on 2026-07-19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0251_trigger_steps_and_error_policy'),
        ('spawns', '0146_player_spawn_player_world_room_live'),
        ('worlds', '0115_remove_worldconfig_death_gold_penalty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTriggerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('actor_type', models.TextField()),
                ('actor_id', models.PositiveBigIntegerField()),
                ('actor_key', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('bindings', models.JSONField(blank=True, default=dict)),
                ('next_step_index', models.PositiveIntegerField(default=0)),
                ('next_run_ts', models.DateTimeField()),
                ('started_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.TextField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active')),
                ('on_step_error', models.TextField(default='cancel')),
                ('failure_code', models.TextField(blank=True, default='')),
                ('last_error', models.TextField(blank=True, default='')),
                ('completed_ts', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_trigger_runs', to='worlds.room')),
                ('runtime_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_trigger_runs', to='worlds.world')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_runs', to='builders.trigger')),
            ],
            options={
                'ordering': ['created_ts'],
                'indexes': [models.Index(fields=['status', 'next_run_ts', 'id'], name='spawn_trigger_run_due_idx'), models.Index(fields=['status', 'modified_ts', 'id'], name='spawn_trigger_run_prune_idx'), models.Index(condition=models.Q(('status', 'active')), fields=['runtime_world', 'actor_type', 'actor_id'], name='spawn_trigger_actor_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('trigger', 'runtime_world', 'room', 'actor_type', 'actor_id'), name='spawn_trigger_actor_active_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(condition=models.Q(('is_pending_deletion', False)), fields=['world', 'container_type', 'container_id', 'definition'], name='spawn_item_live_container_def'),
        ),
    ]
