# Generated by Django 5.2.16 on 2026-07-25 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0149_mob_state'),
        ('worlds', '0117_worldconfig_announce_duel_results_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuelParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('role', models.TextField(choices=[('contestant', 'Contestant'), ('spectator', 'Spectator')], db_index=True, default='contestant')),
                ('team', models.PositiveSmallIntegerField(default=1)),
                ('result', models.TextField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='pending')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('team', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('pending_ability', models.JSONField(blank=True, default=dict)),
                ('pending_flee', models.JSONField(blank=True, default=dict)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='spawns.combatencounter')),
                ('mob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_participations', to='spawns.mob')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_participations', to='spawns.player')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DuelMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('base_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_matches', to='worlds.world')),
                ('challenged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_challenges_received', to='spawns.player')),
                ('challenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_challenges_sent', to='spawns.player')),
                ('entrance_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_matches_started_here', to='worlds.room')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_match_losses', to='spawns.player')),
                ('run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_match', to='worlds.instancerun')),
                ('template_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_template_matches', to='worlds.world')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_match_wins', to='spawns.player')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='combatencounter',
            name='duel_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_encounters', to='spawns.duelmatch'),
        ),
        migrations.AddIndex(
            model_name='combatencounter',
            index=models.Index(fields=['duel_match', 'status'], name='spawns_comb_duel_ma_fa3eda_idx'),
        ),
        migrations.AddConstraint(
            model_name='combatencounter',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('duel_match__isnull', False)), fields=('duel_match',), name='spawns_duel_one_active_encounter'),
        ),
        migrations.AddField(
            model_name='duelparticipant',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='spawns.duelmatch'),
        ),
        migrations.AddField(
            model_name='duelparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_participations', to='spawns.player'),
        ),
        migrations.AddIndex(
            model_name='combatparticipant',
            index=models.Index(fields=['encounter', 'is_active', 'team'], name='spawns_comb_encount_ad5355_idx'),
        ),
        migrations.AddIndex(
            model_name='combatparticipant',
            index=models.Index(fields=['player', 'is_active'], name='spawns_comb_player__a9e9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='combatparticipant',
            index=models.Index(fields=['mob', 'is_active'], name='spawns_comb_mob_id_1be4f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='combatparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mob__isnull', True), ('player__isnull', False)), models.Q(('mob__isnull', False), ('player__isnull', True)), _connector='OR'), name='spawns_combat_participant_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='combatparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('team__gte', 1)), name='spawns_combat_participant_team_positive'),
        ),
        migrations.AddConstraint(
            model_name='combatparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('encounter', 'player'), name='spawns_combat_unique_player'),
        ),
        migrations.AddConstraint(
            model_name='combatparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('mob__isnull', False)), fields=('encounter', 'mob'), name='spawns_combat_unique_mob'),
        ),
        migrations.AddIndex(
            model_name='duelmatch',
            index=models.Index(fields=['status', 'expires_at'], name='spawns_duel_status_ce5656_idx'),
        ),
        migrations.AddIndex(
            model_name='duelmatch',
            index=models.Index(fields=['challenger', 'status'], name='spawns_duel_challen_d20ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='duelmatch',
            index=models.Index(fields=['challenged', 'status'], name='spawns_duel_challen_88e0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='duelmatch',
            index=models.Index(fields=['base_world', 'status'], name='spawns_duel_base_wo_f8a9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='duelmatch',
            index=models.Index(fields=['template_world', 'status'], name='spawns_duel_templat_a784bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='duelmatch',
            constraint=models.CheckConstraint(condition=models.Q(('challenger__isnull', True), ('challenged__isnull', True), models.Q(('challenger', models.F('challenged')), _negated=True), _connector='OR'), name='spawns_duel_distinct_challengers'),
        ),
        migrations.AddIndex(
            model_name='duelparticipant',
            index=models.Index(fields=['match', 'role', 'team'], name='spawns_duel_match_i_c3cb80_idx'),
        ),
        migrations.AddIndex(
            model_name='duelparticipant',
            index=models.Index(fields=['player', 'role'], name='spawns_duel_player__f9248c_idx'),
        ),
        migrations.AddConstraint(
            model_name='duelparticipant',
            constraint=models.UniqueConstraint(fields=('match', 'player'), name='spawns_duel_unique_participant'),
        ),
        migrations.AddConstraint(
            model_name='duelparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('team__gte', 1)), name='spawns_duel_team_positive'),
        ),
    ]
