# Generated by Django 5.2.16 on 2026-07-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0253_mob_initial_state'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('spawns', '0150_duelparticipant_combatparticipant_duelmatch_and_more'),
        ('worlds', '0117_worldconfig_announce_duel_results_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mob',
            index=models.Index(condition=models.Q(('is_pending_deletion', False)), fields=['world', 'room', 'id'], name='spawn_mob_world_room_live'),
        ),
    ]
