# Generated by Django 5.2.16 on 2026-07-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0151_mob_spawn_mob_world_room_live'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='combatparticipant',
            name='spawns_comb_player__a9e9b6_idx',
        ),
        migrations.AddIndex(
            model_name='combatparticipant',
            index=models.Index(condition=models.Q(('is_active', True), ('player__isnull', False)), fields=['player', 'encounter'], name='spawn_combat_player_active'),
        ),
    ]
