# Generated by Django 5.2.17 on 2026-09-04 23:47

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone


def drain_transient_combat(apps, schema_editor):
    """End current WR2 fights; live combat state is not converted to the new model."""
    Encounter = apps.get_model('spawns', 'CombatEncounter')
    Participant = apps.get_model('spawns', 'CombatParticipant')
    Effect = apps.get_model('spawns', 'ActiveEffect')
    Player = apps.get_model('spawns', 'Player')
    refunds = {}
    for player_id, pending in Encounter.objects.filter(duel_match__isnull=True, status='active').values_list('player_id', 'pending_flee'):
        if player_id:
            refunds[player_id] = refunds.get(player_id, 0) + max(0, int((pending or {}).get('movement_cost') or 0))
    for player_id, pending in Participant.objects.filter(is_active=True, player__isnull=False).values_list('player_id', 'pending_flee'):
        refunds[player_id] = refunds.get(player_id, 0) + max(0, int((pending or {}).get('movement_cost') or 0))
    for player_id, amount in refunds.items():
        if amount:
            Player.objects.filter(pk=player_id).update(stamina=models.F('stamina') + amount)
    Effect.objects.filter(scope='encounter').delete()
    Effect.objects.filter(scope='character', remaining_rounds__gt=0).update(next_tick_ts=timezone.now())
    Participant.objects.filter(is_active=True).update(is_active=False, pending_ability={}, pending_flee={})
    Encounter.objects.exclude(status='finished').update(status='finished', next_resolution_ts=None,
        pending_player_ability={}, pending_mob_ability={}, pending_flee={})


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0159_gameeventoutbox_depends_on_batch_id'),
        ('worlds', '0130_zone_default_roam_chance'),
    ]

    operations = [
        migrations.RunPython(drain_transient_combat, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CombatRewardReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('mob_runtime_id', models.PositiveBigIntegerField(unique=True)),
                ('mob_snapshot', models.JSONField(default=dict)),
                ('awards', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatRoomState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('dirty_generation', models.PositiveBigIntegerField(default=0)),
                ('applied_generation', models.PositiveBigIntegerField(default=0)),
                ('frozen_generation', models.PositiveBigIntegerField(default=0)),
                ('changed_actors', models.JSONField(default=list)),
                ('frozen_actors', models.JSONField(default=list)),
                ('cursor', models.JSONField(default=dict)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('next_run_ts', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatSideRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('relation', models.CharField(default='hostile', max_length=8)),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='combatparticipant',
            name='spawns_combat_participant_one_actor',
        ),
        migrations.AddField(
            model_name='combatencounter',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_encounters', to='spawns.combatencounter'),
        ),
        migrations.AddField(
            model_name='combatencounter',
            name='npc_active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatencounter',
            name='random_seed',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='combatencounter',
            name='schedule_generation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combatencounter',
            name='state_revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='actor_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='contributions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='current_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by', to='spawns.combatparticipant'),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='exit_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='first_eligible_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='initiative',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='intent_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='combatencounter',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_encounters', to='spawns.player'),
        ),
        migrations.AlterField(
            model_name='combatencounter',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished')], db_index=True, default='active'),
        ),
        migrations.AlterField(
            model_name='combatparticipant',
            name='mob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_participations', to='spawns.mob'),
        ),
        migrations.AlterField(
            model_name='combatparticipant',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_participations', to='spawns.player'),
        ),
        migrations.AddField(
            model_name='combatrewardreceipt',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spawns.combatencounter'),
        ),
        migrations.AddField(
            model_name='combatroomstate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.room'),
        ),
        migrations.AddField(
            model_name='combatroomstate',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world'),
        ),
        migrations.AddField(
            model_name='combatside',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sides', to='spawns.combatencounter'),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='spawns.combatside'),
        ),
        migrations.AddConstraint(
            model_name='combatparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mob__isnull', True), ('player__isnull', False)), models.Q(('mob__isnull', False), ('player__isnull', True)), models.Q(('is_active', False), ('mob__isnull', True), ('player__isnull', True)), _connector='OR'), name='spawns_combat_participant_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='combatparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('player__isnull', False)), fields=('player',), name='combat_player_one_active'),
        ),
        migrations.AddConstraint(
            model_name='combatparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('mob__isnull', False)), fields=('mob',), name='combat_mob_one_active'),
        ),
        migrations.AddField(
            model_name='combatsiderelation',
            name='higher_side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='higher_relations', to='spawns.combatside'),
        ),
        migrations.AddField(
            model_name='combatsiderelation',
            name='lower_side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lower_relations', to='spawns.combatside'),
        ),
        migrations.AddConstraint(
            model_name='combatroomstate',
            constraint=models.UniqueConstraint(fields=('world', 'room'), name='combat_room_scope_unique'),
        ),
        migrations.AddConstraint(
            model_name='combatside',
            constraint=models.UniqueConstraint(fields=('encounter', 'position'), name='combat_side_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='combatside',
            constraint=models.CheckConstraint(condition=models.Q(('position__in', [1, 2])), name='combat_side_two_teams'),
        ),
        migrations.AddConstraint(
            model_name='combatsiderelation',
            constraint=models.UniqueConstraint(fields=('lower_side', 'higher_side'), name='combat_relation_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='combatsiderelation',
            constraint=models.CheckConstraint(condition=models.Q(('lower_side__lt', models.F('higher_side'))), name='combat_relation_ordered'),
        ),
        migrations.AddConstraint(
            model_name='combatsiderelation',
            constraint=models.CheckConstraint(condition=models.Q(('relation', 'hostile')), name='combat_relation_hostile'),
        ),
    ]
