# Generated by Django 5.2.17 on 2026-09-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0160_participant_combat'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='combatparticipant',
            name='spawns_combat_unique_player',
        ),
        migrations.RemoveConstraint(
            model_name='combatparticipant',
            name='spawns_combat_unique_mob',
        ),
        migrations.AddConstraint(
            model_name='combatparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('side__isnull', False), _connector='OR'), name='combat_active_member_has_side'),
        ),
    ]
