# Generated by Django 5.2.17 on 2026-09-05 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0162_combat_scope_constraints'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='combatencounter',
            name='spawns_comb_player__8f98ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='combatencounter',
            name='spawns_comb_mob_id_de4421_idx',
        ),
        migrations.RemoveField(
            model_name='combatencounter',
            name='faceoff_override',
        ),
        migrations.RemoveField(
            model_name='combatencounter',
            name='initiative_order',
        ),
        migrations.RemoveField(
            model_name='combatencounter',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='combatencounter',
            name='pending_flee',
        ),
        migrations.RemoveField(
            model_name='combatencounter',
            name='pending_mob_ability',
        ),
        migrations.RemoveField(
            model_name='combatencounter',
            name='pending_player_ability',
        ),
        migrations.RemoveField(
            model_name='combatencounter',
            name='player',
        ),
    ]
