# Generated by Django 5.2.17 on 2026-09-13 14:24

import spawns.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0164_instance_clock_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatparticipant',
            name='mob',
            field=models.ForeignKey(blank=True, null=True, on_delete=spawns.deletion.deactivate_combat_actor, related_name='combat_participations', to='spawns.mob'),
        ),
        migrations.AlterField(
            model_name='combatparticipant',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=spawns.deletion.deactivate_combat_actor, related_name='combat_participations', to='spawns.player'),
        ),
    ]
