# Generated by Django 5.2.17 on 2026-09-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0165_combat_actor_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='rip_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
