# Generated by Django 5.2.17 on 2026-10-04 23:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0168_mob_talkable'),
        ('worlds', '0136_world_entry_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationSession',
            fields=[
                ('world', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='communication_session', serialize=False, to='worlds.world')),
                ('generation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('next_question_number', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='channels',
            field=models.TextField(blank=True, default='ask'),
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField()),
                ('world_id', models.PositiveBigIntegerField()),
                ('room_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('channel', models.CharField(max_length=32)),
                ('sender_type', models.CharField(max_length=16)),
                ('sender_id', models.PositiveBigIntegerField()),
                ('sender_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sender_name', models.TextField()),
                ('target_type', models.CharField(blank=True, max_length=16)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_name', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('session', models.UUIDField(blank=True, null=True)),
                ('question_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('answer_to_question_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('in_reply_to_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_ts', '-id'],
                'indexes': [models.Index(fields=['expires_at', 'id'], name='comm_expiry_idx'), models.Index(fields=['-created_ts', '-id'], name='comm_time_idx'), models.Index(fields=['world_id', '-created_ts'], name='comm_world_time_idx'), models.Index(fields=['world_id', 'channel', '-created_ts'], name='comm_channel_time_idx'), models.Index(fields=['sender_user_id', '-created_ts'], name='comm_sender_user_time_idx'), models.Index(fields=['target_user_id', '-created_ts'], name='comm_target_user_time_idx'), models.Index(fields=['sender_type', 'sender_id', '-created_ts'], name='comm_sender_time_idx'), models.Index(fields=['target_type', 'target_id', '-created_ts'], name='comm_target_time_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('channel', 'ask')), fields=('world_id', 'session', 'question_number'), name='comm_world_session_question_uniq')],
            },
        ),
    ]
