# Generated by Django 5.2.18 on 2026-10-08 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0169_communication_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantstockentry',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_stock_entry', to='spawns.item'),
        ),
    ]
