# Generated by Django 3.2.25 on 2026-03-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0090_state_only_worldconfig_starting_eq'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestArcTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('journal_policy', models.JSONField(default=dict)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_arc_templates', to='worlds.world')),
            ],
            options={
                'ordering': ['name', 'created_ts'],
                'unique_together': {('world', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='QuestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.TextField()),
                ('quest_type', models.TextField(choices=[('questlet', 'Questlet'), ('quest', 'Quest'), ('contract', 'Contract'), ('world_event', 'World_event')], default='quest')),
                ('scope', models.TextField(choices=[('player', 'Player'), ('party', 'Party'), ('guild', 'Guild'), ('world', 'World')], default='player')),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft')),
                ('repeatability_mode', models.TextField(choices=[('never', 'Never'), ('cooldown', 'Cooldown'), ('always', 'Always')], default='never')),
                ('repeatability_cooldown_seconds', models.PositiveIntegerField(default=0)),
                ('max_active', models.PositiveIntegerField(default=1)),
                ('discovery_policy', models.JSONField(default=dict)),
                ('slot_schema', models.JSONField(default=dict)),
                ('graph', models.JSONField(default=dict)),
                ('reward_policy', models.JSONField(default=dict)),
                ('manifest_version', models.TextField(default='v1alpha1')),
                ('arc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_templates', to='quests.questarctemplate')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_templates', to='worlds.world')),
            ],
            options={
                'ordering': ['name', 'created_ts'],
                'unique_together': {('world', 'slug')},
            },
        ),
    ]
