# Generated by Django 5.2.16 on 2026-07-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_drop_questlet_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='questinstance',
            new_name='quests_ques_player__b99121_idx',
            old_name='quests_ques_player__8dbf78_idx',
        ),
        migrations.RenameIndex(
            model_name='questinstance',
            new_name='quests_ques_templat_ceb79d_idx',
            old_name='quests_ques_templat_ac9a47_idx',
        ),
        migrations.RenameIndex(
            model_name='questinstance',
            new_name='quests_ques_world_i_1afa45_idx',
            old_name='quests_ques_world_i_4f4a2a_idx',
        ),
        migrations.AlterField(
            model_name='questinstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questjournalentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questobjectivestate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questofferstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
