# Generated by Django 5.2.17 on 2026-10-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0010_quest_daily_repeatability'),
        ('spawns', '0168_mob_talkable'),
        ('worlds', '0136_world_entry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='questinstance',
            name='interaction_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questinstance',
            name='interaction_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='questinstance',
            index=models.Index(condition=models.Q(('interaction_due_at__isnull', False)), fields=['interaction_due_at', 'id'], name='quests_interaction_due'),
        ),
        migrations.AddIndex(
            model_name='questinstance',
            index=models.Index(condition=models.Q(('interaction_due_at__isnull', False)), fields=['world', 'interaction_due_at'], name='quests_world_interaction_due'),
        ),
    ]
