# Generated by Django 2.0.4 on 2018-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180426_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
