# Generated by Django 2.0.4 on 2019-02-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_send_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_grapevine',
            field=models.BooleanField(default=False),
        ),
    ]
