# Generated by Django 2.0.4 on 2019-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_use_grapevine'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='multiplayer_worlds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='name_recognition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='player_housing',
            field=models.BooleanField(default=False),
        ),
    ]
