# Generated by Django 2.0.4 on 2019-06-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190415_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessibility_mode',
            field=models.BooleanField(default=False),
        ),
    ]
