# Generated by Django 2.0.4 on 2019-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_accessibility_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invalid',
            field=models.BooleanField(default=False),
        ),
    ]
