# Generated by Django 2.0.4 on 2019-12-21 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userflag',
            options={},
        ),
        migrations.AlterField(
            model_name='userflag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userflag',
            unique_together={('user', 'code')},
        ),
    ]
