# Generated by Django 2.0.4 on 2020-03-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200101_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nochat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='noplay',
            field=models.BooleanField(default=False),
        ),
    ]
