# Generated by Django 3.2.10 on 2023-11-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211228_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
