# Generated by Django 3.2.10 on 2023-12-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cod_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
