# Generated by Django 3.2.25 on 2024-04-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_cod_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
