# Generated by Django 3.2.25 on 2025-06-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userflag',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userflag',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
