# Generated by Django 3.2.25 on 2025-06-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20250611_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('used_ts', models.DateTimeField(blank=True, null=True)),
                ('expires_ts', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_link_requests', to='users.user')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
