# Generated by Django 5.2.17 on 2026-09-19 02:06

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def check_email_uniqueness(apps, schema_editor):
    User = apps.get_model('users', 'User')
    duplicates = (User.objects.using(schema_editor.connection.alias)
                  .annotate(email_upper=django.db.models.functions.text.Upper('email'))
                  .values('email_upper').annotate(total=models.Count('pk'))
                  .filter(total__gt=1))
    if duplicates.exists():
        raise RuntimeError('Resolve case-insensitive duplicate Core emails before applying users.0022; accounts are never merged automatically.')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0021_loginlinkrequest'),
        ('worlds', '0135_lobby_leaderboards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('issuer', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WR1SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('browser_hash', models.CharField(db_index=True, max_length=64)),
                ('verifier', models.CharField(max_length=128)),
                ('issuer', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=128)),
                ('redirect_uri', models.CharField(max_length=2048)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('expires_ts', models.DateTimeField(db_index=True)),
                ('subject', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_proved', models.BooleanField(default=False)),
                ('proof_hash', models.CharField(blank=True, max_length=64)),
                ('proof_sent_ts', models.DateTimeField(blank=True, null=True)),
                ('proof_attempts', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(check_email_uniqueness, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('email'), name='users_email_ci_unique'),
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wr1signin',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world'),
        ),
        migrations.AddConstraint(
            model_name='externalidentity',
            constraint=models.UniqueConstraint(fields=('issuer', 'subject'), name='users_external_identity_unique'),
        ),
    ]
