# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldbuilder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_builders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worldbuilder',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_builders', to='worlds.World'),
        ),
        migrations.AddField(
            model_name='rule',
            name='loader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='builders.Loader'),
        ),
        migrations.AddField(
            model_name='rule',
            name='target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_types', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='rule',
            name='template_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_types', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='roomgettrigger',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_triggers', to='worlds.Room'),
        ),
        migrations.AddField(
            model_name='roomcommandtrigger',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmd_triggers', to='worlds.Room'),
        ),
        migrations.AddField(
            model_name='roomcommandcheck',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmd_checks', to='worlds.Room'),
        ),
        migrations.AddField(
            model_name='mobtemplateinventory',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builders.MobTemplate'),
        ),
        migrations.AddField(
            model_name='mobtemplateinventory',
            name='item_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mob_inventory', to='builders.ItemTemplate'),
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mob_templates', to='worlds.World'),
        ),
        migrations.AddField(
            model_name='mobreaction',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='builders.MobTemplate'),
        ),
        migrations.AddField(
            model_name='loader',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaders', to='worlds.World'),
        ),
        migrations.AddField(
            model_name='loader',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_loaders', to='worlds.Zone'),
        ),
        migrations.AddField(
            model_name='lastviewedroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_viewed_for', to='worlds.Room'),
        ),
        migrations.AddField(
            model_name='lastviewedroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_viewed_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lastviewedroom',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_viewed_for', to='worlds.World'),
        ),
        migrations.AddField(
            model_name='itemtemplateinventory',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builders.ItemTemplate'),
        ),
        migrations.AddField(
            model_name='itemtemplateinventory',
            name='item_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_inventory', to='builders.ItemTemplate'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_templates', to='worlds.World'),
        ),
        migrations.AlterUniqueTogether(
            name='lastviewedroom',
            unique_together=set([('world', 'user')]),
        ),
    ]
