# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0003_mobtemplate_fights_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplate',
            name='hit_msg_first',
            field=models.TextField(blank=True, default='hit'),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='hit_msg_third',
            field=models.TextField(blank=True, default='hits'),
        ),
    ]
