# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0004_auto_20170505_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcommandcheck',
            name='argument',
            field=models.TextField(blank=True),
        ),
    ]
