# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
        ('builders', '0005_auto_20170508_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('prevent', models.TextField(choices=[('all', 'All'), ('enter', 'Enter'), ('exit', 'Exit')])),
                ('check', models.TextField(choices=[('equipped', 'Equipped'), ('in_inv', 'In_inv'), ('is_look', 'Is_look')])),
                ('argument', models.TextField(blank=True)),
                ('failure_msg', models.TextField()),
                ('state', models.TextField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed')], null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_checks', to='worlds.Room')),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
    ]
