# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0006_roomcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcommandcheck',
            name='track_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomcheck',
            name='check',
            field=models.TextField(choices=[('equipped', 'Equipped'), ('in_inv', 'In_inv'), ('is_look', 'Is_look'), ('cmd_issued', 'Cmd_issued')]),
        ),
        migrations.AlterField(
            model_name='roomcommandcheck',
            name='check',
            field=models.TextField(choices=[('equipped', 'Equipped'), ('in_inv', 'In_inv'), ('is_look', 'Is_look'), ('cmd_issued', 'Cmd_issued')]),
        ),
    ]
