# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0007_auto_20170515_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcommandcheck',
            name='state',
        ),
        migrations.RemoveField(
            model_name='roomcommandcheck',
            name='success_msg',
        ),
    ]
