# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0009_auto_20170517_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcommandcheck',
            name='hint_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
