# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('worlds', '0002_auto_20170602_1736'),
        ('builders', '0010_roomcommandcheck_hint_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('type', models.TextField(choices=[('item', 'Item'), ('mob', 'Mob')])),
                ('qty', models.IntegerField(default=1)),
                ('template_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('relative_id', models.IntegerField(blank=True, null=True)),
                ('enquire_msg', models.TextField(blank=True, null=True)),
                ('completion_msg', models.TextField(blank=True, null=True)),
                ('incomplete_msg', models.TextField(blank=True, null=True)),
                ('repeatable', models.IntegerField(default=0)),
                ('mob_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_quests', to='builders.MobTemplate')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_quests', to='worlds.World')),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('type', models.TextField(choices=[('item', 'Item'), ('exp', 'Exp'), ('gold', 'Gold')])),
                ('qty', models.IntegerField(default=1)),
                ('template_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='builders.Quest')),
                ('template_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_rewards', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'ordering': ['created_ts'],
            },
        ),
        migrations.AddField(
            model_name='objective',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='builders.Quest'),
        ),
        migrations.AddField(
            model_name='objective',
            name='template_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_objectives', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='quest',
            unique_together=set([('world', 'relative_id')]),
        ),
    ]
