# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 18:37
from __future__ import unicode_literals

from django.db import migrations

from config import constants as adv_consts

def build(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')

    World = apps.get_model('worlds', 'World')
    Room = apps.get_model('worlds', 'Room')

    ItemTemplate = apps.get_model('builders', 'ItemTemplate')
    MobTemplate = apps.get_model('builders', 'MobTemplate')
    Quest = apps.get_model('builders', 'Quest')
    Objective = apps.get_model('builders', 'Objective')
    Reward = apps.get_model('builders', 'Reward')
    Loader = apps.get_model('builders', 'Loader')
    Rule = apps.get_model('builders', 'Rule')

    try:
        world = World.objects.get(pk=3)
    except World.DoesNotExist:
        return

    mob_template_ct = ContentType.objects.get(model='mobtemplate')
    room_ct = ContentType.objects.get(model='room')
    item_template_ct = ContentType.objects.get(model='itemtemplate')

    MobTemplate.objects.filter(id__in=[1, 69,70]).update(
        aggression=adv_consts.MOB_AGGRESSION_PLAYERS)

    cave_loader = Loader.objects.get(pk=1)
    cave_loader.zone_id = 2
    cave_loader.save()
    # young spider in room.6
    Rule.objects.create(
        loader=cave_loader,
        template_type=mob_template_ct,
        template_id=1,
        target_type=room_ct,
        target_id=372,
        order=4)
    # 2 aggro small spiders in room.7
    Rule.objects.create(
        loader=cave_loader,
        template_type=mob_template_ct,
        template_id=69,
        target_type=room_ct,
        target_id=373,
        num_copies=2,
        order=5)
    # giant spider in room.8
    Rule.objects.create(
        loader=cave_loader,
        template_type=mob_template_ct,
        template_id=70,
        target_type=room_ct,
        target_id=374,
        order=6)

    william = MobTemplate.objects.create(
        type=adv_consts.MOB_TYPE_HUMANOID,
        name='William Larker',
        roaming_type=adv_consts.ROAM_STATIC,
        world=world,
        level=10,
        health_max=130,
        attack_power=52,
        crit=65,
        dodge=13,
        resilience=39,
        experience=313)

    larker_loader = Loader.objects.create(
        world=world,
        name='Larker Farm loads',
        zone_id=49)
    Rule.objects.create(
        loader=larker_loader,
        template_type=mob_template_ct,
        template_id=william.id,
        target_type=room_ct,
        target_id=458)

    dagger_template = ItemTemplate.objects.create(
        name='a ruby-hilted dagger',
        world=world,
        level=5,
        type=adv_consts.ITEM_TYPE_EQUIPPABLE,
        equipment_type=adv_consts.EQUIPMENT_TYPE_WEAPON_1H,
        hit_msg_first='slice',
        hit_msg_third='slices')

    bear_template = ItemTemplate.objects.create(
        name='a carved wooden bear',
        world=world,
        level=1,
        type=adv_consts.ITEM_TYPE_INERT)

    # bear in room.8
    Rule.objects.create(
        loader=cave_loader,
        template_type=item_template_ct,
        template_id=bear_template.id,
        target_type=room_ct,
        target_id=374,
        order=7)

    quest = Quest.objects.create(
        world=world,
        mob_template=william,
        enquire_msg=(
            "My poor Billy! Where could he be... "
            "One second he was playing outside with his carved wooden bear "
            "and the second, he's gone! Just gone..."),
        completion_msg=(
            "Oh my, you've found... the carved bear, but not the boy? "
            "A giant spider you say? Oh, oh..."),
        incomplete_msg=("I don't know where Billy is! I am freaking out!"))

    objective = Objective.objects.create(
        quest=quest,
        type=adv_consts.OBJECTIVE_TYPE_ITEM,
        template_type=item_template_ct,
        template_id=bear_template.id)

    reward = Reward.objects.create(
        quest=quest,
        type=adv_consts.REWARD_TYPE_ITEM,
        template_type=item_template_ct,
        template_id=dagger_template.id)

    # Landmark rooms
    room_rids = [14, 15, 16, 19, 21, 22]
    rooms = Room.objects.filter(world=world, relative_id__in=room_rids)
    rooms.update(is_landmark=True)


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0011_auto_20170615_1511'),
        #('worlds', '0002_auto_20170602_1736'),
    ]

    operations = [
        migrations.RunPython(build),
    ]
