# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 16:20
from __future__ import unicode_literals

from django.db import migrations

from config import constants as adv_consts


def build(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    try:
        world = World.objects.get(pk=3)
        world.short_description = ("Introduction world. Escape the trap laid by the giant spider. Take your revenge.")
        world.description = ("You name is Lana, a young farmer and aspiring adventurer. You have been tracking down several disappearences, including a young boy in a farm out west of your cabin. While exploring the forest, you venture into a creepy cave tucked behind a mossy waterfall. After taking no more than a few steps into the damp space, your vision becomes blurry and your head groggy. As you slump to the ground, the last sound you hear is your torch hitting the wet ground...")
        world.save()
    except World.DoesNotExist:
        return

    Zone = apps.get_model('worlds', 'Zone')
    # Zones to create:
    # trail, upper forest, lower forest
    Room = apps.get_model('worlds', 'Room')

    ItemTemplate = apps.get_model('builders', 'ItemTemplate')
    MobTemplate = apps.get_model('builders', 'MobTemplate')
    Loader = apps.get_model('builders', 'Loader')
    Rule = apps.get_model('builders', 'Rule')
    RoomGetTrigger = apps.get_model('builders', 'RoomGetTrigger')

    ContentType = apps.get_model('contenttypes', 'ContentType')
    mob_template_ct = ContentType.objects.get(model='mobtemplate')
    room_ct = ContentType.objects.get(model='room')

    # ==== Zones ====

    # Convert upper forest zone
    upper_forest_zone = Zone.objects.get(pk=49)
    upper_forest_zone.name = 'Upper Forest'
    upper_forest_zone.save()
    Room.objects.filter(
        id__in=[377, 452, 453, 454]
    ).update(zone_id=upper_forest_zone.id)

    # Lower forest
    lower_forest_zone = Zone.objects.create(
        world=world,
        name='Lower Forest',
        relative_id=3)
    Room.objects.filter(
        id__in=[523, 520, 521, 522, 518]
    ).update(zone_id=lower_forest_zone.id)

    # Trail
    trail_zone = Zone.objects.create(
        world=world,
        name='Trail',
        relative_id=4)
    Room.objects.filter(
        id__in=[548, 457, 455, 456, 458, 459, 460, 461, 462, 519, 524, 566, 567]
    ).update(zone_id=trail_zone.id)


    # ==== Mob Templates ====

    # Toad, turtle

    rabbit_template = MobTemplate.objects.create(
        name='a fluffy-eared rabbit',
        description=("Long, fluffy ears droop on each side of this chubby rabbit's head. It looks so soft that you can barely resist the urge to run your hand through its fur, though you are aware that it would probably just hop away from you if you tried."),
        world=world,
        level=1,
        health_max=9,
        attack_power=22,
        crit=28,
        dodge=6,
        resilience=17,
        exp_worth=16,
        roaming_type=adv_consts.ROAM_ZONE)

    squirrel_template = MobTemplate.objects.create(
        name='a brown squirrel',
        description=("Manically munching on a nut held between its two little hands, this squirrel seems always to be anxiously staring at you, as well as everything else."),
        world=world,
        level=2,
        health_max=19,
        attack_power=25,
        crit=32,
        dodge=7,
        resilience=19,
        exp_worth=25,
        roaming_type=adv_consts.ROAM_ZONE)

    chicken_template = MobTemplate.objects.create(
        name='a pecking chicken',
        description=("Always moving in sudden jerks and eyeing you sideways, this chicken is mostly brown except for its red comb and yellow feet."),
        world=world,
        level=2,
        health_max=19,
        attack_power=25,
        crit=32,
        dodge=7,
        resilience=19,
        exp_worth=25)

    cat_template = MobTemplate.objects.create(
        name='a gray cat',
        description=("This cat cares not at all for your presence, or for the very concept of you to begin with. Rarely on the move except when looking for an even more comfortable spot to sleep on, this little beast is nevertheless quite convinced of its own ferocity."),
        world=world,
        level=2,
        health_max=19,
        attack_power=25,
        crit=32,
        dodge=7,
        resilience=19,
        exp_worth=25)

    toad_template = MobTemplate.objects.create(
        name='a green toad',
        description=("This small frog pauses between leaps to look at you through protruding slitted orbs. Limbs folded underneath its body, it is ready to leap away at a moment's notice."),
        world=world,
        level=2,
        health_max=19,
        attack_power=25,
        crit=32,
        dodge=7,
        resilience=19,
        exp_worth=25)

    turtle_template = MobTemplate.objects.create(
        name='a box turtle',
        description=("Head barely peeking out of its shell, this box turtle still has tufts of fresh grass hanging from the side of its mouth. Oblivious to your presence, it hobbles around looking for anything edible."),
        world=world,
        level=3,
        health_max=31,
        attack_power=27,
        crit=34,
        dodge=7,
        resilience=20,
        exp_worth=40)

    sheep_template = MobTemplate.objects.create(
        name='a black-faced sheep',
        description=("Other than for its black face, this sheep is completely covered in a thick layer of gray wool so long that it brushes against the ground underneath its belly."),
        world=world,
        level=3,
        health_max=31,
        attack_power=27,
        crit=34,
        dodge=7,
        resilience=20,
        exp_worth=40,
        roaming_type=adv_consts.ROAM_ZONE)

    pig_template = MobTemplate.objects.create(
        name='a wild pig',
        description=("This pig is leaner than the ones you've seen in the nearby farms, and seems less concerned with finding food than eyeing your every move. You're not entirely sure how close to it you should get. "),
        world=world,
        level=4,
        health_max=45,
        attack_power=30,
        crit=38,
        dodge=8,
        resilience=22,
        exp_worth=61,
        roaming_type=adv_consts.ROAM_ZONE)

    doe_template = MobTemplate.objects.create(
        name='a nervous doe',
        world=world,
        level=4,
        health_max=45,
        attack_power=30,
        crit=38,
        dodge=8,
        resilience=22,
        exp_worth=61,
        roaming_type=adv_consts.ROAM_ZONE)

    ram_template = MobTemplate.objects.create(
        name='a large-horned ram',
        description=("The head of this male sheep is adorned by a pair of large horns, sure to be quite painful should they find their way into your flesh."),
        world=world,
        level=5,
        health_max=63,
        attack_power=33,
        crit=42,
        dodge=9,
        resilience=25,
        exp_worth=88,
        roaming_type=adv_consts.ROAM_ZONE)

    buck_template = MobTemplate.objects.create(
        name='a young buck',
        world=world,
        level=5,
        health_max=63,
        attack_power=33,
        crit=42,
        dodge=9,
        resilience=25,
        exp_worth=88,
        roaming_type=adv_consts.ROAM_ZONE)

    stag_template = MobTemplate.objects.create(
        name='a prancing stag',
        world=world,
        level=6,
        health_max=81,
        attack_power=36,
        crit=45,
        dodge=9,
        resilience=27,
        exp_worth=121,
        roaming_type=adv_consts.ROAM_ZONE)

    randall_template = MobTemplate.objects.create(
        name='Randall Soran',
        world=world,
        level=10,
        health_max=130,
        attack_power=52,
        crit=65,
        dodge=13,
        resilience=39,
        exp_worth=313)

    # ==== Loaders ====

    upper_forest_loader = Loader.objects.create(
        world=world,
        zone=upper_forest_zone,
        name='Upper forest loads')
    # 1x rabbit
    Rule.objects.create(
        loader=upper_forest_loader,
        order=1,
        template_type=mob_template_ct,
        template_id=rabbit_template.id)
    # 3x sheep
    Rule.objects.create(
        loader=upper_forest_loader,
        order=2,
        template_type=mob_template_ct,
        template_id=sheep_template.id,
        num_copies=3)
    # 1x squirrel
    Rule.objects.create(
        loader=upper_forest_loader,
        order=3,
        template_type=mob_template_ct,
        template_id=squirrel_template.id)
    # 1x ram
    Rule.objects.create(
        loader=upper_forest_loader,
        order=4,
        template_type=mob_template_ct,
        template_id=ram_template.id,
        num_copies=1)
    # 2x pig
    Rule.objects.create(
        loader=upper_forest_loader,
        order=5,
        template_type=mob_template_ct,
        template_id=pig_template.id,
        num_copies=2)

    lower_forest_loader = Loader.objects.create(
        world=world,
        zone=lower_forest_zone,
        name='Lower forest loads')
    # 1x turtle (pond)
    Rule.objects.create(
        loader=lower_forest_loader,
        order=1,
        template_type=mob_template_ct,
        template_id=turtle_template.id,
        num_copies=1,
        target_type=room_ct,
        target_id=522)
    # 1x toad (pond)
    Rule.objects.create(
        loader=lower_forest_loader,
        order=2,
        template_type=mob_template_ct,
        template_id=toad_template.id,
        num_copies=1,
        target_type=room_ct,
        target_id=522)
    # 2x doe
    Rule.objects.create(
        loader=lower_forest_loader,
        order=3,
        template_type=mob_template_ct,
        template_id=doe_template.id,
        num_copies=2)
    # 3x buck
    Rule.objects.create(
        loader=lower_forest_loader,
        order=4,
        template_type=mob_template_ct,
        template_id=buck_template.id,
        num_copies=3)
    # 2x stag
    Rule.objects.create(
        loader=lower_forest_loader,
        order=5,
        template_type=mob_template_ct,
        template_id=stag_template.id,
        num_copies=2)

    # Farm:
    # 2x chicken (room.17)
    farm_loader = Loader.objects.get(pk=39)
    farm_loader.name = 'Farm loads'
    farm_loader.zone = trail_zone
    farm_loader.save()
    Rule.objects.create(
        loader=farm_loader,
        order=2,
        template_type=mob_template_ct,
        template_id=chicken_template.id,
        target_type=room_ct,
        target_id=457,
        num_copies=2)

    # Cabin:
    cabin_loader = Loader.objects.create(
        world=world,
        zone=trail_zone,
        name='Cabin loads')
    # 1x cat
    Rule.objects.create(
        loader=cabin_loader,
        order=1,
        template_id=cat_template.id,
        template_type=mob_template_ct,
        target_type=room_ct,
        target_id=462)
    # 1x randall
    Rule.objects.create(
        loader=cabin_loader,
        order=2,
        template_id=randall_template.id,
        template_type=mob_template_ct,
        target_type=room_ct,
        target_id=462)


    # ==== Work on items / quests ====



    torch_template = ItemTemplate.objects.get(pk=70)
    torch_template.description = 'It is a lit torch, good for a few hours...'
    torch_template.save()

    bear_template = ItemTemplate.objects.get(pk=72)
    bear_template.description = "This was probably Billy's bear! Bring it to Sam and type 'give bear Sam'."
    bear_template.save()
    print('here!!')

    knife_get_trigger = RoomGetTrigger.objects.get(pk=1)
    knife_get_trigger.message = ("You use the knife to slice through the silk. As the web weakens, your weight tears through the rest of the fabric and you fall to the ground with a loud thump!\nWincing in pain, you try to familiarize yourself with your surroundings.")
    knife_get_trigger.save()

    bear_get_trigger = RoomGetTrigger.objects.create(
        name="Instruction when picking up the bear",
        room_id=374,
        argument=72,
        action='message',
        message=("This was probably Billy's bear! Bring the bear to Sam and type 'give bear Sam'."))


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0013_auto_20170622_1956'),
    ]

    operations = [
        migrations.RunPython(build),
    ]
