# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0014_world_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
