# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0015_quest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplateinventory',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_inventories', to='builders.ItemTemplate'),
        ),
        migrations.AlterField(
            model_name='itemtemplateinventory',
            name='item_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_for_items', to='builders.ItemTemplate'),
        ),
        migrations.AlterField(
            model_name='mobtemplateinventory',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_inventories', to='builders.MobTemplate'),
        ),
        migrations.AlterField(
            model_name='mobtemplateinventory',
            name='item_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_for_mobs', to='builders.ItemTemplate'),
        ),
    ]
