# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0016_auto_20170726_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='loader',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='group_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
