# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0017_auto_20170828_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='assists',
            field=models.BooleanField(default=False),
        ),
    ]
