# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0018_mobtemplate_assists'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='ground_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='type',
            field=models.TextField(choices=[('equippable', 'Equippable'), ('consumable', 'Consumable'), ('light', 'Light'), ('container', 'Container'), ('key', 'Key'), ('inert', 'Inert'), ('corpse', 'Corpse'), ('trash', 'Trash')], default='inert'),
        ),
    ]
