# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0019_auto_20170831_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='is_pickable',
            field=models.BooleanField(default=True),
        ),
    ]
