# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0008_room_transfer_to'),
        ('builders', '0021_mobtemplate_room_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('room', models.ManyToManyField(related_name='blocks', to='worlds.Room')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
