# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0022_roomblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomblock',
            old_name='room',
            new_name='rooms',
        ),
    ]
