# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0024_auto_20170927_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='entrance_cmds',
            field=models.TextField(blank=True, null=True),
        ),
    ]
