# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0025_quest_entrance_cmds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='repeatable',
            new_name='repeatable_after',
        ),
        migrations.AddField(
            model_name='quest',
            name='repeat_entrance_cmd_after',
            field=models.IntegerField(default=10),
        ),
    ]
