# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0026_auto_20171019_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='completion_msg',
            new_name='completion_cmds',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='enquire_msg',
            new_name='enquire_cmds',
        ),
    ]
