# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0027_auto_20171025_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomItemProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('chance_imbued', models.PositiveIntegerField(default=20)),
                ('chance_enchanted', models.PositiveIntegerField(default=5)),
                ('restriction', models.TextField(blank=True, choices=[('armor_only', 'Armor_only'), ('weapon_only', 'Weapon_only'), ('armor_heavy_only', 'Armor_heavy_only'), ('armor_light_only', 'Armor_light_only')], null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='roomcheck',
            name='state',
        ),
    ]
