# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('builders', '0028_auto_20171110_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='template_id',
            new_name='profile_id',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='template_type',
        ),
        migrations.AddField(
            model_name='reward',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_rewards', to='contenttypes.ContentType'),
        ),
    ]
