# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0029_auto_20171110_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomitemprofile',
            name='restriction',
            field=models.TextField(blank=True, choices=[('armor_only', 'Armor_only'), ('weapon_only', 'Weapon_only'), ('shield_only', 'Shield_only'), ('weapon_or_shield', 'Weapon_or_shield'), ('armor_heavy_only', 'Armor_heavy_only'), ('armor_light_only', 'Armor_light_only')], null=True),
        ),
    ]
