# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0030_auto_20171112_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='wait_until_cmds',
            field=models.TextField(blank=True, null=True),
        ),
    ]
