# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0031_quest_wait_until_cmds'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('level', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.TextField(choices=[('weapon', 'Weapon'), ('offhand', 'Offhand'), ('head', 'Head'), ('body', 'Body'), ('arms', 'Arms'), ('hands', 'Hands'), ('waist', 'Waist'), ('legs', 'Legs'), ('feet', 'Feet'), ('shoulders', 'Shoulders')])),
                ('level', models.PositiveIntegerField(default=0)),
                ('is_heavy', models.BooleanField(default=False)),
                ('chance_imbued', models.PositiveIntegerField(default=20)),
                ('chance_enchanted', models.PositiveIntegerField(default=5)),
                ('item_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builders.ItemTemplate')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='builders.EquipmentProfile')),
            ],
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='eq_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builders.EquipmentProfile'),
        ),
    ]
