# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0032_auto_20171204_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobEquipmentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='mobtemplate',
            name='eq_profile',
        ),
        migrations.AddField(
            model_name='mobequipmentprofile',
            name='mob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_profiles', to='builders.MobTemplate'),
        ),
        migrations.AddField(
            model_name='mobequipmentprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobprofiles', to='builders.EquipmentProfile'),
        ),
    ]
