# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-15 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('worlds', '0010_auto_20171112_1737'),
        ('builders', '0033_auto_20171204_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('is_core', models.BooleanField(default=False)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_factions', to='worlds.World')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactionAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(default=0)),
                ('member_id', models.PositiveIntegerField(blank=True, null=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_for', to='builders.Faction')),
                ('member_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faction_assignments', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('standing', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='builders.Faction')),
                ('towards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='builders.Faction')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='chance_enchanted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='chance_imbued',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
