# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-15 20:45
from __future__ import unicode_literals

from django.db import migrations


def create_core_factions(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    if not World.objects.filter(id=1).exists():
        return

    Faction = apps.get_model('builders', 'Faction')
    Faction.objects.create(world_id=1,
                           name='human',
                           is_core=True)
    Faction.objects.create(world_id=1,
                           name='orc',
                           is_core=True)
    Faction.objects.create(world_id=1,
                           name='lifeless',
                           is_core=True)

class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0034_auto_20171215_2044'),
    ]

    operations = [
        migrations.RunPython(create_core_factions)
    ]
