# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-17 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0035_auto_20171215_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
