# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-22 19:44
from __future__ import unicode_literals

from django.db import migrations, models


def add_core_faction_codes(apps, schem_editor):
    Faction = apps.get_model('builders', 'Faction')
    Faction.objects.filter(world_id=1, name='human').update(code='human')
    Faction.objects.filter(world_id=1, name='orc').update(code='orc')
    Faction.objects.filter(world_id=1, name='lifeless').update(code='lifeless')


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0036_equipmentprofile_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(add_core_faction_codes)
    ]
