# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0038_auto_20171222_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='randomitemprofile',
            name='restriction',
            field=models.TextField(blank=True, choices=[('armor_only', 'Armor_only'), ('weapon_only', 'Weapon_only'), ('weapon_1h_only', 'Weapon_1h_only'), ('weapon_2h_only', 'Weapon_2h_only'), ('shield_only', 'Shield_only'), ('weapon_or_shield', 'Weapon_or_shield'), ('armor_heavy_only', 'Armor_heavy_only'), ('armor_light_only', 'Armor_light_only')], null=True),
        ),
    ]
