# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0039_auto_20180112_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=1)),
                ('item_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builders.ItemTemplate')),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_inv', to='builders.MobTemplate')),
                ('random_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builders.RandomItemProfile')),
            ],
        ),
    ]
