# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0040_merchantinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
