# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0041_itemtemplate_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantinventory',
            old_name='random_item',
            new_name='random_profile',
        ),
    ]
