# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0010_auto_20171112_1737'),
        ('builders', '0042_auto_20180116_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='death_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='death_room_for_factions', to='worlds.Room'),
        ),
    ]
