# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-22 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0043_faction_death_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
