# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0044_quest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
