# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-19 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0045_mobtemplate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.TextField(choices=[('item', 'Item'), ('exp', 'Exp'), ('gold', 'Gold'), ('faction', 'Faction')]),
        ),
    ]
