# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-19 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0046_auto_20180319_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
