# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0047_auto_20180319_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='option',
        ),
        migrations.AddField(
            model_name='quest',
            name='enquire_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
