# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0048_auto_20180323_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobreaction',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobreaction',
            name='event',
            field=models.TextField(choices=[('entering', 'Entering'), ('saying', 'Saying')]),
        ),
    ]
