# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-27 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0049_auto_20180326_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobreaction',
            name='event',
            field=models.TextField(choices=[('enter', 'Enter'), ('say', 'Say'), ('receive', 'Receive'), ('periodic', 'Periodic')]),
        ),
    ]
