# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0050_auto_20180327_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='completion_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
