# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-29 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0051_quest_completion_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='completion_cmd_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='enquire_cmd_available',
            field=models.BooleanField(default=True),
        ),
    ]
