# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0052_auto_20180329_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loader',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_loaders', to='worlds.Zone'),
        ),
    ]
