# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-02 19:49
from __future__ import unicode_literals

from django.db import migrations, models


def populate_loader_orders(apps, schema_editor):
    Loader = apps.get_model('builders', 'Loader')
    Zone = apps.get_model('worlds', 'Zone')
    for zone_id in Loader.objects.values_list('zone', flat=True).distinct():
        i = 1
        loaders = Loader.objects.filter(
            zone_id=zone_id
        ).order_by('created_ts')
        for loader in loaders:
            loader.order = i
            loader.save()
            i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0053_auto_20180402_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='loader',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(populate_loader_orders)
    ]
