# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0054_loader_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='load_specification',
            field=models.TextField(blank=True, choices=[('armor_only', 'Armor_only'), ('weapon_only', 'Weapon_only'), ('weapon_1h_only', 'Weapon_1h_only'), ('weapon_2h_only', 'Weapon_2h_only'), ('shield_only', 'Shield_only'), ('weapon_or_shield', 'Weapon_or_shield'), ('armor_heavy_only', 'Armor_heavy_only'), ('armor_light_only', 'Armor_light_only')], null=True),
        ),
        migrations.AlterField(
            model_name='loader',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaders', to='worlds.Zone'),
        ),
    ]
