# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-18 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0055_auto_20180413_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='requires_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='requires_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prereq_quests', to='builders.Quest'),
        ),
    ]
