# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-23 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0056_auto_20180422_0131'),
        ('builders', '0056_auto_20180418_1617'),
    ]

    operations = [
    ]
