# Generated by Django 2.0.4 on 2018-04-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0057_merge_20180423_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcommandtrigger',
            name='room',
        ),
        migrations.AlterField(
            model_name='faction',
            name='death_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_room_for_factions', to='worlds.Room'),
        ),
        migrations.AlterField(
            model_name='loader',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loaders', to='worlds.Zone'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='template_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_objectives', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='mob_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_quests', to='builders.MobTemplate'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='requires_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prereq_quests', to='builders.Quest'),
        ),
        migrations.DeleteModel(
            name='RoomCommandTrigger',
        ),
    ]
