# Generated by Django 2.0.4 on 2018-05-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0058_auto_20180426_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='regen_rate',
            field=models.IntegerField(default=4),
        ),
    ]
