# Generated by Django 2.0.4 on 2018-05-04 17:54

from django.db import migrations, models


def set_regens(apps, schema_editor):
    MobTemplate = apps.get_model('builders', 'MobTemplate')
    MobTemplate.objects.all().update(
        health_regen=0,
        mana_regen=0,
        stamina_regen=0)


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0059_mobtemplate_regen_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobtemplate',
            name='health_regen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mobtemplate',
            name='mana_regen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mobtemplate',
            name='stamina_regen',
            field=models.IntegerField(default=0),
        ),

        migrations.RunPython(set_regens),
    ]
