# Generated by Django 2.0.4 on 2018-05-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0060_auto_20180504_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='use_abilities',
            field=models.BooleanField(default=False),
        ),
    ]
