# Generated by Django 2.0.4 on 2018-05-10 22:56

from django.db import migrations, models


def set_aggression(apps, schema_editor):
    MobTemplate = apps.get_model('builders', 'MobTemplate')
    MobTemplate.objects.filter(aggression='passive').update(aggression='normal')


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0061_mobtemplate_use_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobtemplate',
            name='aggression',
            field=models.TextField(choices=[('passive', 'Passive'), ('all', 'All'), ('players', 'Players'), ('normal', 'Normal')], default='passive'),
        ),

        migrations.RunPython(set_aggression),
    ]
