# Generated by Django 2.0.4 on 2018-05-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0062_auto_20180510_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='type',
            field=models.TextField(choices=[('item', 'Item'), ('mob', 'Mob'), ('gold', 'Gold')]),
        ),
    ]
