# Generated by Django 2.0.4 on 2018-05-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0063_auto_20180515_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='completion_despawn',
            field=models.IntegerField(default=0),
        ),
    ]
