# Generated by Django 2.0.4 on 2018-05-20 22:43

from django.db import migrations


def change_loaders(apps, schema_editor):
    Rule = apps.get_model('builders', 'Rule')
    rules_qs = Rule.objects.filter(target_id__isnull=True)
    for rule in rules_qs:
        print('rule %s' % rule)
        rule.target_type_id = 27
        rule.target_id = rule.loader.zone_id
        rule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0064_quest_completion_despawn'),
    ]

    operations = [
        migrations.RunPython(change_loaders),
    ]
