# Generated by Django 2.0.4 on 2018-05-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0065_auto_20180520_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
