# Generated by Django 2.0.4 on 2018-05-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0066_quest_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='default_stats',
            field=models.BooleanField(default=False),
        ),
    ]
