# Generated by Django 2.0.4 on 2018-06-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0067_mobtemplate_default_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='complete_silently',
            field=models.BooleanField(default=False),
        ),
    ]
