# Generated by Django 2.0.4 on 2018-07-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0068_quest_complete_silently'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='completion_entrance_cmds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='repeat_completion_entrance_cmds_after',
            field=models.IntegerField(default=10),
        ),
    ]
