# Generated by Django 2.0.4 on 2018-07-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0069_auto_20180723_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcheck',
            name='direction',
            field=models.TextField(blank=True, choices=[('north', 'North'), ('east', 'East'), ('south', 'South'), ('west', 'West'), ('up', 'Up'), ('down', 'Down')], null=True),
        ),
        migrations.AlterField(
            model_name='roomcheck',
            name='check',
            field=models.TextField(choices=[('equipped', 'Equipped'), ('not_equipped', 'Not_equipped'), ('in_inv', 'In_inv'), ('not_in_inv', 'Not_in_inv'), ('mob_is_present', 'Mob_is_present'), ('faction_below', 'Faction_below'), ('health_below', 'Health_below')]),
        ),
        migrations.AlterField(
            model_name='roomcommandcheck',
            name='check',
            field=models.TextField(choices=[('equipped', 'Equipped'), ('not_equipped', 'Not_equipped'), ('in_inv', 'In_inv'), ('not_in_inv', 'Not_in_inv'), ('mob_is_present', 'Mob_is_present'), ('faction_below', 'Faction_below'), ('health_below', 'Health_below')]),
        ),
    ]
