# Generated by Django 2.0.4 on 2018-07-30 15:02

from django.db import migrations


def migrate_room_checks(apps, schema_editor):
    RoomCheck = apps.get_model('builders', 'RoomCheck')
    RoomCheck.objects.all().update(check='not_in_inv')


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0070_auto_20180730_0229'),
    ]

    operations = [
        migrations.RunPython(migrate_room_checks),
    ]
