# Generated by Django 2.0.4 on 2018-07-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0071_dm_migrate_room_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcommandcheck',
            name='check',
            field=models.TextField(choices=[('in_inv', 'In_inv'), ('cmd_issued', 'Cmd_issued')]),
        ),
    ]
