# Generated by Django 2.0.4 on 2018-07-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0072_auto_20180730_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcheck',
            name='failure_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
