# Generated by Django 2.0.4 on 2018-08-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0073_auto_20180730_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='completion_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
