# Generated by Django 2.0.4 on 2018-08-23 14:33

from django.db import migrations, models
import django.db.models.deletion


def add_cutpurse_path(apps, schema_editor):
    Path = apps.get_model('builders', 'Path')
    Room = apps.get_model('worlds', 'Room')

    path = Path.objects.create(
        name='Renise cutpurse path',
        world_id=1)

    room_ids = [6148, 6147, 6146, 6145, 6144, 6143, 6152, 6153, 6154]
    rooms = Room.objects.filter(pk__in=room_ids)
    for room in rooms:
        path.rooms.add(room)

class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0021_worldconfig_auto_equip'),
        ('builders', '0074_quest_completion_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('relative_id', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('max_per_room', models.PositiveIntegerField(blank=True, null=True)),
                ('max_per_path', models.PositiveIntegerField(blank=True, null=True)),
                ('rooms', models.ManyToManyField(to='worlds.Room')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.World')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='path',
            unique_together={('world', 'relative_id')},
        ),

        #migrations.RunPython(add_cutpurse_path),
    ]
