# Generated by Django 2.0.4 on 2018-08-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0075_auto_20180823_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobtemplate',
            name='roaming_type',
            field=models.TextField(choices=[('all', 'All'), ('static', 'Static'), ('zone', 'Zone'), ('path', 'Path')], default='static'),
        ),
    ]
