# Generated by Django 2.0.4 on 2018-09-04 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0076_auto_20180826_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcheck',
            name='argument2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='worlds.World'),
        ),
    ]
