# Generated by Django 2.0.4 on 2018-09-07 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0077_auto_20180904_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobReactionCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('condition', models.TextField(choices=[('has_completed', 'Has_completed'), ('has_not_completed', 'Has_not_completed'), ('above_level', 'Above_level'), ('below_level', 'Below_level')])),
                ('argument', models.TextField()),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='builders.MobReaction')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
