# Generated by Django 2.0.4 on 2018-09-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0078_mobreactioncondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobreaction',
            name='event',
            field=models.TextField(choices=[('enter', 'Enter'), ('say', 'Say'), ('receive', 'Receive'), ('periodic', 'Periodic'), ('connect', 'Connect')]),
        ),
    ]
