# Generated by Django 2.0.4 on 2018-09-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0080_auto_20180921_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('transformation_type', models.TextField(choices=[('attribute', 'Attribute')])),
                ('arg1', models.TextField(blank=True, null=True)),
                ('arg2', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
