# Generated by Django 2.0.4 on 2018-10-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0022_auto_20180904_2252'),
        ('builders', '0081_transformationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='entry_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_for_paths', to='worlds.World'),
        ),
    ]
