# Generated by Django 2.0.4 on 2018-10-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0082_path_entry_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='path',
            name='entry_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_for_paths', to='worlds.Room'),
        ),
    ]
