# Generated by Django 2.0.4 on 2018-10-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0083_auto_20181012_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='roam_chance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
