# Generated by Django 2.0.4 on 2018-10-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0084_mobtemplate_roam_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loader',
            name='loader_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
