# Generated by Django 2.0.4 on 2018-10-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0085_loader_loader_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='control_flag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
