# Generated by Django 2.0.4 on 2018-10-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0086_mobtemplate_control_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobreaction',
            name='event',
            field=models.TextField(choices=[('enter', 'Enter'), ('say', 'Say'), ('receive', 'Receive'), ('periodic', 'Periodic'), ('connect', 'Connect'), ('load', 'Load')]),
        ),
    ]
