# Generated by Django 2.0.4 on 2018-10-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0087_auto_20181014_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobtemplate',
            name='is_general',
        ),
    ]
