# Generated by Django 2.0.4 on 2018-12-13 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0023_auto_20181012_2123'),
        ('builders', '0088_remove_mobtemplate_is_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='worlds.Zone'),
        ),
    ]
