# Generated by Django 2.0.4 on 2019-01-05 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0024_zone_center'),
        ('builders', '0089_path_zone'),
    ]

    operations = [
        # `Path.rooms` was introduced as a normal M2M in 0075, which already
        # creates `builders_path_rooms` in the database. Keep this migration as
        # a state transition only so fresh clones do not attempt to recreate
        # that table.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='PathRoom',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                    options={
                        'db_table': 'builders_path_rooms',
                        'managed': True,
                    },
                ),
                # migrations.AlterField(
                #     model_name='path',
                #     name='rooms',
                #     field=models.ManyToManyField(through='builders.PathRoom', to='worlds.Room'),
                # ),
                migrations.AddField(
                    model_name='pathroom',
                    name='path',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_rooms', to='builders.Path'),
                ),
                migrations.AddField(
                    model_name='pathroom',
                    name='room',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_paths', to='worlds.Room'),
                ),
                migrations.AlterUniqueTogether(
                    name='pathroom',
                    unique_together={('path', 'room')},
                ),
            ],
        ),
    ]
