# Generated by Django 2.0.4 on 2019-01-30 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0024_zone_center'),
        ('builders', '0090_auto_20190105_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_quests', to='worlds.Zone'),
        ),
    ]
