# Generated by Django 2.0.4 on 2019-02-04 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0091_quest_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randomitemprofile',
            options={'ordering': ['created_ts']},
        ),
        migrations.AddField(
            model_name='randomitemprofile',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randomitemprofile',
            name='modified_ts',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
