# Generated by Django 2.0.4 on 2019-02-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0092_auto_20190204_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldbuilder',
            name='read_only',
            field=models.BooleanField(default=True),
        ),
    ]
