# Generated by Django 2.0.4 on 2019-02-28 22:06

from django.db import migrations, models
import django.db.models.deletion


def set_transformation_templates_world(apps, schema_editor):
    TransformationTemplate = apps.get_model('builders', 'TransformationTemplate')
    TransformationTemplate.objects.all().update(world_id=1)


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0024_zone_center'),
        ('builders', '0093_worldbuilder_read_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformationtemplate',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transformation_templates', to='worlds.World'),
        ),
        migrations.RunPython(set_transformation_templates_world),
    ]
