# Generated by Django 2.0.4 on 2019-02-28 23:29

from django.db import migrations, models
import django.db.models.deletion


def set_random_item_profiles_world(apps, schema_editor):
    RandomItemProfile = apps.get_model('builders', 'RandomItemProfile')
    RandomItemProfile.objects.all().update(world_id=1)



class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0024_zone_center'),
        ('builders', '0094_transformationtemplate_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomitemprofile',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='random_item_profiles', to='worlds.World'),
        ),
        migrations.RunPython(set_random_item_profiles_world),
    ]
