# Generated by Django 2.0.4 on 2019-03-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0095_randomitemprofile_world'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantinventory',
            old_name='random_profile',
            new_name='random_item_profile',
        ),
    ]
