# Generated by Django 2.0.4 on 2019-03-04 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worlds', '0024_zone_center'),
        ('builders', '0096_auto_20190301_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldbuilder',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='worldbuilder',
            unique_together={('world', 'user')},
        ),
    ]
