# Generated by Django 2.0.4 on 2019-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0097_auto_20190304_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='is_elite',
            field=models.BooleanField(default=False),
        ),
    ]
