# Generated by Django 2.0.4 on 2019-04-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0041_playerfeat'),
        ('builders', '0098_mobtemplate_is_elite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_blocks', to='spawns.Player')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
