# Generated by Django 2.0.4 on 2019-04-17 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spawns', '0041_playerfeat'),
        ('builders', '0099_housingblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingLease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_leases', to='spawns.Player')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_leases', to='spawns.Player')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='housingblock',
            name='purchase_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
