# Generated by Django 2.0.4 on 2019-04-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0100_auto_20190417_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinglease',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_leases', to='builders.HousingBlock'),
        ),
    ]
