# Generated by Django 2.0.4 on 2019-06-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0101_auto_20190417_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='is_persistent',
            field=models.BooleanField(default=False),
        ),
    ]
