# Generated by Django 2.0.4 on 2019-07-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0103_itemtemplate_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobtemplate',
            name='type',
            field=models.TextField(choices=[('aberration', 'Aberration'), ('beast', 'Beast'), ('celestial', 'Celestial'), ('construct', 'Construct'), ('dragon', 'Dragon'), ('elemental', 'Elemental'), ('fey', 'Fey'), ('fiend', 'Fiend'), ('giant', 'Giant'), ('humanoid', 'Humanoid'), ('monstrosity', 'Monstrosity'), ('ooze', 'Ooze'), ('plant', 'Plant'), ('undead', 'Undead')], default='beast'),
        ),
    ]
