# Generated by Django 2.0.4 on 2019-07-15 16:41

from django.db import migrations, models
from config.game_settings import ILF

def set_mob_gold(apps, schema_editor):
    MobTemplate = apps.get_model('builders', 'MobTemplate')
    for mob_template in MobTemplate.objects.all():
        if mob_template.type == 'humanoid' and mob_template.gold == 0:
            mob_template.gold = ILF(mob_template.level)
            mob_template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0104_auto_20190715_1519'),
    ]

    operations = [
        migrations.RunPython(set_mob_gold),
    ]
