# Generated by Django 2.0.4 on 2019-08-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0105_auto_20190715_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loader',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaders', to='worlds.Zone'),
        ),
    ]
