# Generated by Django 2.0.4 on 2019-09-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0031_worldconfig_can_select_faction'),
        ('builders', '0106_auto_20190829_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='starting_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_room_for_factions', to='worlds.Room'),
        ),
    ]
