# Generated by Django 2.0.4 on 2019-09-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0107_faction_starting_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='type',
            field=models.TextField(blank=True, choices=[('fetch', 'Fetch'), ('deliver', 'Deliver')], null=True),
        ),
    ]
