# Generated by Django 2.0.4 on 2019-09-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0108_quest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='type',
            field=models.TextField(choices=[('item', 'Item'), ('mob', 'Mob'), ('gold', 'Gold'), ('glory', 'Glory')]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.TextField(choices=[('item', 'Item'), ('exp', 'Exp'), ('gold', 'Gold'), ('faction', 'Faction'), ('glory', 'Glory')]),
        ),
    ]
