# Generated by Django 2.0.4 on 2019-10-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0109_auto_20190926_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faction',
            name='is_selectable',
            field=models.BooleanField(default=True),
        ),
    ]
