# Generated by Django 2.0.4 on 2019-10-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0110_auto_20191001_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcheck',
            name='check',
            field=models.TextField(choices=[('equipped', 'Equipped'), ('not_equipped', 'Not_equipped'), ('in_inv', 'In_inv'), ('not_in_inv', 'Not_in_inv'), ('mob_is_present', 'Mob_is_present'), ('faction_below', 'Faction_below'), ('health_below', 'Health_below'), ('quest_complete', 'Quest_complete'), ('quest_incomplete', 'Quest_incomplete')]),
        ),
    ]
