# Generated by Django 2.0.4 on 2019-10-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0111_auto_20191003_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='is_invisible',
            field=models.BooleanField(default=False),
        ),
    ]
