# Generated by Django 2.0.4 on 2019-10-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0034_roomdetail_is_hidden'),
        ('builders', '0112_mobtemplate_is_invisible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_processions', to='builders.Faction')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_processions', to='worlds.Room')),
            ],
        ),
        migrations.AddField(
            model_name='faction',
            name='death_rooms',
            field=models.ManyToManyField(through='builders.Procession', to='worlds.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='procession',
            unique_together={('faction', 'room')},
        ),
    ]
