# Generated by Django 2.0.4 on 2019-10-22 12:01

from django.db import migrations


def migrate_get_triggers(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    if not World.objects.filter(id=1).exists():
        return

    RoomGetTrigger = apps.get_model('builders', 'RoomGetTrigger')
    rgt = RoomGetTrigger.objects.get(pk=3)
    rgt.action_argument = 'room.10056'
    rgt.save()

def migrate_quest_completion_cmds(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    if not World.objects.filter(id=1).exists():
        return

    Quest = apps.get_model('builders', 'Quest')
    quest = Quest.objects.get(pk=135)
    quest.completion_cmds = (
        'echo You catch several fireflies into a jar, and the remainder of the swarm flits away.\njump 20965')
    quest.save()

    quest = Quest.objects.get(pk=34)
    quest.completion_cmds = (
        'echo You slice the webbed cocoon, and a boy drops from the gash in the silk covered in slime. && winvis && load mob 203\r\nforce scared emote looks around, eyes wide with fear.\r\nforce scared say Where did it go? That horrible monster... I thought I was going to die...\r\nforce scared say Please, I just want to go home.\r\nforce scared emote looks south and trembles. It might be best to come back get him once the giant spider has been killed.\r\njump room.10056')
    quest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0113_auto_20191018_1648'),
    ]

    operations = [
        migrations.RunPython(migrate_get_triggers)
    ]
