# Generated by Django 2.0.4 on 2019-10-23 19:20

from django.db import migrations


def faction_death_rooms(apps, schema_editor):
    Faction = apps.get_model('builders', 'Faction')
    Procession = apps.get_model('builders', 'Procession')

    factions_with_death_rooms = Faction.objects.filter(
        death_room__isnull=False)

    for faction in factions_with_death_rooms:
        Procession.objects.create(
            faction=faction,
            room=faction.death_room)


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0114_dm_migrate_get_triggers'),
    ]

    operations = [
        migrations.RunPython(faction_death_rooms)
    ]
