# Generated by Django 2.0.4 on 2019-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0115_dm_migrate_faction_death_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='weapon_type',
            field=models.TextField(blank=True, choices=[('sword', 'Sword'), ('axe', 'Axe'), ('club', 'Club'), ('spear', 'Spear'), ('staff', 'Staff')], null=True),
        ),
    ]
