# Generated by Django 2.0.4 on 2019-12-08 21:36

from django.db import migrations, models
import django.db.models.deletion


def add_faction_ranks(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    if not World.objects.filter(id=1).exists():
        return

    FactionRank = apps.get_model('builders', 'FactionRank')

    # 4 - mountaineers
    # 5 - khell
    # 7 - army

    FactionRank.objects.create(
        faction_id=5,
        standing=100,
        name='Footman')

    FactionRank.objects.create(
        faction_id=7,
        standing=100,
        name='Private')

    FactionRank.objects.create(
        faction_id=7,
        standing=300,
        name='Sergeant')

    FactionRank.objects.create(
        faction_id=7,
        standing=600,
        name='Lieutenant')

    FactionRank.objects.create(
        faction_id=7,
        standing=1000,
        name='Captain')

    FactionRank.objects.create(
        faction_id=7,
        standing=10000,
        name='Colonel')

    FactionRank.objects.create(
        faction_id=7,
        standing=50000,
        name='General')

    FactionRank.objects.create(
        faction_id=4,
        standing=100,
        name='Tenderfoot')

    FactionRank.objects.create(
        faction_id=4,
        standing=300,
        name='Runner')

    FactionRank.objects.create(
        faction_id=4,
        standing=600,
        name='Tracker')

    FactionRank.objects.create(
        faction_id=4,
        standing=1000,
        name='Ranger')

    FactionRank.objects.create(
        faction_id=4,
        standing=10000,
        name='Shepherd')

    FactionRank.objects.create(
        faction_id=4,
        standing=50000,
        name='Mountain Lord')


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0117_auto_20191121_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('standing', models.IntegerField()),
                ('name', models.TextField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='builders.Faction')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.RunPython(add_faction_ranks),
    ]
