# Generated by Django 2.0.4 on 2019-12-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0118_factionrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobtemplate',
            name='archetype',
            field=models.TextField(blank=True, choices=[('warrior', 'Warrior'), ('assassin', 'Assassin'), ('mage', 'Mage'), ('cleric', 'Cleric')], default='warrior', null=True),
        ),
    ]
