# Generated by Django 2.0.4 on 2019-12-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0119_auto_20191209_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobtemplate',
            name='load_specification',
            field=models.TextField(blank=True, choices=[('armor_only', 'Armor_only'), ('weapon_only', 'Weapon_only'), ('weapon_1h_only', 'Weapon_1h_only'), ('weapon_2h_only', 'Weapon_2h_only'), ('shield_only', 'Shield_only'), ('weapon_or_shield', 'Weapon_or_shield'), ('armor_heavy_only', 'Armor_heavy_only'), ('armor_light_only', 'Armor_light_only'), ('armor_light_head', 'Armor_light_head'), ('armor_light_body', 'Armor_light_body'), ('armor_light_arms', 'Armor_light_arms'), ('armor_light_hands', 'Armor_light_hands'), ('armor_light_waist', 'Armor_light_waist'), ('armor_light_legs', 'Armor_light_legs'), ('armor_light_feet', 'Armor_light_feet'), ('armor_heavy_head', 'Armor_heavy_head'), ('armor_heavy_body', 'Armor_heavy_body'), ('armor_heavy_arms', 'Armor_heavy_arms'), ('armor_heavy_hands', 'Armor_heavy_hands'), ('armor_heavy_waist', 'Armor_heavy_waist'), ('armor_heavy_legs', 'Armor_heavy_legs'), ('armor_heavy_feet', 'Armor_heavy_feet')], null=True),
        ),
        migrations.AlterField(
            model_name='randomitemprofile',
            name='restriction',
            field=models.TextField(blank=True, choices=[('armor_only', 'Armor_only'), ('weapon_only', 'Weapon_only'), ('weapon_1h_only', 'Weapon_1h_only'), ('weapon_2h_only', 'Weapon_2h_only'), ('shield_only', 'Shield_only'), ('weapon_or_shield', 'Weapon_or_shield'), ('armor_heavy_only', 'Armor_heavy_only'), ('armor_light_only', 'Armor_light_only'), ('armor_light_head', 'Armor_light_head'), ('armor_light_body', 'Armor_light_body'), ('armor_light_arms', 'Armor_light_arms'), ('armor_light_hands', 'Armor_light_hands'), ('armor_light_waist', 'Armor_light_waist'), ('armor_light_legs', 'Armor_light_legs'), ('armor_light_feet', 'Armor_light_feet'), ('armor_heavy_head', 'Armor_heavy_head'), ('armor_heavy_body', 'Armor_heavy_body'), ('armor_heavy_arms', 'Armor_heavy_arms'), ('armor_heavy_hands', 'Armor_heavy_hands'), ('armor_heavy_waist', 'Armor_heavy_waist'), ('armor_heavy_legs', 'Armor_heavy_legs'), ('armor_heavy_feet', 'Armor_heavy_feet')], null=True),
        ),
    ]
