# Generated by Django 2.0.4 on 2020-01-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0120_auto_20191229_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='max_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
