# Generated by Django 2.0.4 on 2020-01-29 19:27

from django.db import migrations, models


def set_food_items_to_stamina_food_items(apps, schema_editor):
    ItemTemplate = apps.get_model('builders', 'ItemTemplate')

    ItemTemplate.objects.filter(
        type='food'
    ).update(food_type='stamina')

class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0121_auto_20200116_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='food_type',
            field=models.TextField(blank=True, choices=[('stamina', 'Stamina'), ('mana', 'Mana'), ('health', 'Health')], null=True),
        ),
        migrations.RunPython(set_food_items_to_stamina_food_items),
    ]
