# Generated by Django 2.0.4 on 2020-03-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0122_itemtemplate_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='currency',
            field=models.TextField(choices=[('gold', 'Gold'), ('medals', 'Medals')], default='gold'),
        ),
    ]
