# Generated by Django 2.0.4 on 2020-03-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0123_itemtemplate_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='loader',
            name='inherit_zone_wait',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loader',
            name='respawn_wait',
            field=models.IntegerField(default=300),
        ),
    ]
