# Generated by Django 2.0.4 on 2020-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0124_auto_20200330_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loader',
            name='inherit_zone_wait',
            field=models.BooleanField(default=True),
        ),
    ]
