# Generated by Django 2.0.4 on 2020-04-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0044_auto_20200405_0035'),
        ('builders', '0125_auto_20200331_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('actions', models.TextField()),
                ('commands', models.TextField()),
                ('conditions', models.TextField(blank=True, null=True)),
                ('show_details_on_failure', models.BooleanField(default=False)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('display_action_in_room', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_actions', to='worlds.Room')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
