# Generated by Django 2.0.4 on 2020-04-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0126_roomaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomaction',
            name='gate_delay',
            field=models.IntegerField(default=10),
        ),
    ]
