# Generated by Django 3.0.6 on 2020-05-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0127_roomaction_gate_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='is_crafter',
            field=models.BooleanField(default=False),
        ),
    ]
