# Generated by Django 3.0.6 on 2020-05-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0128_mobtemplate_is_crafter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentslot',
            name='slot_name',
            field=models.TextField(choices=[('weapon', 'Weapon'), ('offhand', 'Offhand'), ('head', 'Head'), ('body', 'Body'), ('arms', 'Arms'), ('hands', 'Hands'), ('waist', 'Waist'), ('legs', 'Legs'), ('feet', 'Feet')]),
        ),
    ]
