# Generated by Django 3.0.6 on 2020-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0129_auto_20200513_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='craft_enchanted',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='craft_multiplier',
            field=models.FloatField(default=3),
        ),
    ]
