# Generated by Django 3.0.6 on 2020-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0130_auto_20200514_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcheck',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
