# Generated by Django 3.0.6 on 2020-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0131_roomcheck_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobtemplate',
            name='gender',
            field=models.TextField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non_binary')], default='female', null=True),
        ),
    ]
