# Generated by Django 3.0.6 on 2020-06-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0132_auto_20200530_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='combat_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
