# Generated by Django 3.0.6 on 2020-06-15 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0133_mobtemplate_combat_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobreactioncondition',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_conditions', to='builders.MobReaction'),
        ),
    ]
