# Generated by Django 3.0.6 on 2020-06-15 01:09

from django.db import migrations, models


def migrate_old_reaction_conditions(apps, schema_editor):
    MobReaction = apps.get_model('builders', 'MobReaction')

    # Elder connect reaction
    MobReaction.objects.filter(
        pk=63
    ).update(
        conditions='level_below 6 and not has_completed 3'
    )

    # Elder entrance reaction
    MobReaction.objects.filter(
        pk=64
    ).update(
        conditions='level_below 6 and not has_completed 3'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0134_auto_20200615_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobreaction',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_old_reaction_conditions)
    ]
