# Generated by Django 3.0.6 on 2020-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0135_mobreaction_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
