# Generated by Django 3.0.6 on 2020-06-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0136_faction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
