# Generated by Django 3.0.6 on 2020-07-01 14:49

from django.db import migrations

karn_id = 580
akinos_id = 2642
arkoren_id = 2508
mokdin_id = 2615
hokra_id = 2614

items = {
    "shaman": {
        "armor_type": "light",
        "mob_id": arkoren_id,
        "large": {
            "items": {
                "head": "a light hood marked with an acacia tree",
                "body": "a long shroud marked with an acacia tree",
                "legs": "a pair of breeches marked with an acacia tree",
            },
            "stats": {
                "intelligence": 25,
                "constitution": 50,
                "spell_power": 50,
            },
        },
        "small": {
            "items": {
                "arms": "a pair of green bracelets trimmed with gold",
                "hands": "a pair of green gloves trimmed with gold",
                "waist": "a green cord trimmed with gold",
                "feet": "a pair of green slippers trimmed with gold",
            },
            "stats": {
                "intelligence": 20,
                "constitution": 40,
                "spell_power": 40,
            }
        }
    },
    "legion": {
        "armor_type": "heavy",
        "mob_id": hokra_id,
        "large": {
            "items": {
                "head": "a steel helm marked with a clenched fist",
                "body": "a steel breastplate marked with a clenched fist",
                "legs": "a pair of steel greaves marked with a clenched fist",
            },
            "stats": {
                "strength": 25,
                "constitution": 50,
                "attack_power": 50,
            },
        },
        "small": {
            "items": {
                "arms": "a pair of of brown vambraces trimmed with red",
                "hands": "a pair of brown gauntlets trimmed with red",
                "waist": "a brown girdle trimmed with red",
                "feet": "a pair of brown boots trimmed with red",
            },
            "stats": {
                "strength": 20,
                "constitution": 40,
                "attack_power": 40,
            }
        }
    },
    "shapers": {
        "armor_type": "light",
        "mob_id": mokdin_id,
        "large": {
            "items": {
                "head": "a thin tiara marked with two overlapped circles",
                "body": "a long cloak marked with two overlapped circles",
                "legs": "a pair of leggings marked with two overlapped circles",
            },
            "stats": {
                "intelligence": 25,
                "constitution": 50,
                "spell_power": 50,
            },
        },
        "small": {
            "items": {
                "arms": "a pair of orange armbands trimmed with gold",
                "hands": "a pair of orange gloves trimmed with gold",
                "waist": "an orange sash trimmed with gold",
                "feet": "a pair of orange treads trimmed with gold",
            },
            "stats": {
                "intelligence": 20,
                "constitution": 40,
                "spell_power": 40,
            }
        }
    },
    "reavers": {
        "armor_type": "light",
        "mob_id": akinos_id,
        "large": {
            "items": {
                "head": "a supple mask marked with a jagged line through an X",
                "body": "a leather jerkin marked with a jagged line through an X",
                "legs": "a pair of leggings marked with a jagged line through an X",
            },
            "stats": {
                "intelligence": 25,
                "constitution": 50,
                "resilience": 50,
            },
        },
        "small": {
            "items": {
                "arms": "a pair of black cuffs trimmed with red",
                "hands": "a pair of black grips trimmed with red",
                "waist": "a black belt trimmed with red",
                "feet": "a pair of black boots trimmed with red",
            },
            "stats": {
                "intelligence": 20,
                "constitution": 40,
                "resilience": 40,
            }
        }
    },
    "army_heavy": {
        "armor_type": "heavy",
        "mob_id": karn_id,
        "large": {
            "items": {
                "head": "a steel faceguard marked with a pair of antlers",
                "body": "a steel chestplate marked with a pair of antlers",
                "legs": "a pair of steel legguards marked with a pair of antlers",
            },
            "stats": {
                "crit": 35,
                "constitution": 65,
                "health_max": 40,
            },
        },
        "small": {
            "items": {
                "arms": "a pair of red vambraces trimmed with gold",
                "hands": "a pair of red handguards trimmed with gold",
                "waist": "a red, plated belt trimmed with gold ",
                "feet": "a pair of red, plated boots trimmed with gold",
            },
            "stats": {
                "crit": 30,
                "constitution": 50,
                "health_max": 35,
            }
        }
    },
    "army_light": {
        "armor_type": "light",
        "mob_id": karn_id,
        "large": {
            "items": {
                "head": "a light helmet marked with a pair of antlers",
                "body": "a light tunic marked with a pair of antlers",
                "legs": "a pair leggings marked with a pair of antlers",
            },
            "stats": {
                "crit": 35,
                "constitution": 65,
                "health_max": 40,
            },
        },
        "small": {
            "items": {
                "arms": "a pair of red coverings trimmed with gold",
                "hands": "a pair of red gauntlets trimmed with gold",
                "waist": "a red belt trimmed with gold",
                "feet": "a pair of red boots trimmed with gold",
            },
            "stats": {
                "crit": 30,
                "constitution": 50,
                "health_max": 35,
            }
        }
    },
}


def create_shaman_eq(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    if not World.objects.filter(id=1).exists():
        return

    MobTemplate = apps.get_model('builders', 'MobTemplate')
    MerchantInventory = apps.get_model('builders', 'MerchantInventory')

    ItemTemplate = apps.get_model('builders', 'ItemTemplate')

    for items_data in items.values():
        for armor_type in ['large', 'small']:
            if armor_type == 'large':
                cost = 3
            else:
                cost = 2
            stats = items_data[armor_type]['stats']
            for eq_type, item_name in items_data[armor_type]['items'].items():
                item_template = ItemTemplate.objects.create(
                    world_id=1,
                    level=20,
                    name=item_name,
                    type='equippable',
                    equipment_type=eq_type,
                    currency='medal',
                    cost=cost,
                    armor_class=items_data['armor_type'],
                    **items_data[armor_type]['stats'])

                MerchantInventory.objects.create(
                    item_template=item_template,
                    mob_id=items_data['mob_id'])



class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0137_quest_conditions'),
    ]

    operations = [
        migrations.RunPython(create_shaman_eq)
    ]
