# Generated by Django 3.0.6 on 2020-07-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0137_quest_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='flags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
