# Generated by Django 3.0.6 on 2020-07-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0139_auto_20200702_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='merchant_profit',
            field=models.FloatField(default=2),
        ),
    ]
