# Generated by Django 3.0.6 on 2020-07-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0140_mobtemplate_merchant_profit'),
        ('builders', '0138_mobtemplate_flags'),
    ]

    operations = [
    ]
