# Generated by Django 3.0.6 on 2020-07-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0141_merge_20200724_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='type',
            field=models.TextField(choices=[('item', 'Item'), ('mob', 'Mob'), ('gold', 'Gold'), ('glory', 'Glory'), ('medals', 'Medals')]),
        ),
    ]
