# Generated by Django 3.0.6 on 2020-07-24 17:58

from django.db import migrations

data = {}
data['akinos'] = {
    'mob_id': 2642,
    'faction_code': 'reaver',
    'faction_name': 'Reavers',
    'mob_name': 'Doombringer Akinos',
}
data['arkoren'] = {
    'mob_id': 2508,
    'faction_code': 'shaman',
    'faction_name': 'Shaman',
    'mob_name': "Oracle Ar'Koren",
}
data['mokdin'] = {
    'mob_id': 2615,
    'faction_code': 'shaper',
    'faction_name': 'Shapers',
    'mob_name': "Harbinger Mok'Din",
}
data['hokra'] = {
    'mob_id': 2614,
    'faction_code': 'legion',
    'faction_name': 'Legion',
    'mob_name': "General Hok'Ra",
}

ZONE_ID = 998

BANNER_ENQUIRES = """say There are two ways you can advance within the ranks of the {faction}.
say The first is to bring me two human war banners from the Finham war zone, which will earn you 5 standing. Use PRESENT BANNERS to turn them in.
say The second is to bring me a medal, which will earn you 25 standing. Use PRESENT MEDAL to turn one in.
"""

def create_orc_quests(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    if not World.objects.filter(id=1).exists():
        return

    MobTemplate = apps.get_model('builders', 'MobTemplate')
    ItemTemplate = apps.get_model('builders', 'ItemTemplate')
    MerchantInventory = apps.get_model('builders', 'MerchantInventory')
    Quest = apps.get_model('builders', 'Quest')
    Objective = apps.get_model('builders', 'Objective')
    Reward = apps.get_model('builders', 'Reward')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Faction = apps.get_model('builders', 'Faction')

    # Update the merchant profit on the 4 head mobs to be 1.0
    mob_ids = [ d['mob_id'] for d in data.values() ]
    MobTemplate.objects.filter(pk__in=mob_ids).update(
        merchant_profit=1.0)

    # Make faction eq enchanted
    mobs = [2642, 2508, 2615, 2614, 580]
    item_template_ids = MerchantInventory.objects.filter(
        mob_id__in=mobs
    ).values_list('item_template_id', flat=True)
    ItemTemplate.objects.filter(
        id__in=item_template_ids
    ).update(quality='enchanted')

    for mob_id in mobs:
        MerchantInventory.objects.create(
            mob_id=mob_id,
            item_template_id=2440)
        MerchantInventory.objects.create(
            mob_id=mob_id,
            item_template_id=2441)

    for mob_data in data.values():
        faction_name = mob_data['faction_name']
        mob_name = mob_data['mob_name']
        faction = Faction.objects.get(
            code=mob_data['faction_code'],
            world_id=1)

        # Add the banner quest
        banner_quest = Quest.objects.create(
            name=f'{faction_name} Standing',
            zone_id=ZONE_ID,
            world_id=1,
            mob_template_id=mob_data['mob_id'],
            summary=f'Present 2 human war banners [PRESENT BANNERS] or 1 medal [PRESENT MEDAL] to {mob_name}.',
            level=20,
            enquire_cmds=BANNER_ENQUIRES.format(faction=mob_data['faction_name']),
            completion_cmds="emote nods in approval.",
            completion_action="present heads")

        Objective.objects.create(
            quest=banner_quest,
            type='item',
            qty=2,
            template_type=ContentType.objects.get_for_model(ItemTemplate),
            template_id=2438, # human banner
            )

        Reward.objects.create(
            quest=banner_quest,
            type='faction',
            qty=5,
            profile_type=ContentType.objects.get_for_model(Faction),
            profile_id=faction.id)

        # Add the potion quest
        potion_quest = Quest.objects.create(
            name=f'Medals {faction_name} quest',
            zone_id=ZONE_ID,
            world_id=1,
            mob_template_id=mob_data['mob_id'],
            level=20,
            completion_action="present medal",
            completion_cmds="emote nods in approval.")

        Objective.objects.create(
            quest=potion_quest,
            type='medals',
            qty=1)

        Reward.objects.create(
            quest=potion_quest,
            type='faction',
            qty=25,
            profile_type=ContentType.objects.get_for_model(Faction),
            profile_id=faction.id)

class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0142_auto_20200724_1756'),
    ]

    operations = [
        migrations.RunPython(create_orc_quests)
    ]
