# Generated by Django 3.0.6 on 2020-08-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0143_orc_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='skill_modifier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
