# Generated by Django 3.0.6 on 2020-08-05 01:19

from django.db import migrations


items = [
    {
        "name": "Thune's Hammer",
        "weapon_type": "club",
        "equipment_type": "weapon_2h",
        "ground_description": "An enormous hammer lies here, grip wrapped in leather.",
        "description": "A massive rectangular head sits on a thick handle, wrapped in leather at the grip.",
        "skill_modifier": "bash duration 0.5",
        "health_max": 200,
        "strength": 150,
        "health_regen": 20,
    },
    {
        "name": "Arkosh's Scepter",
        "weapon_type": "staff",
        "equipment_type": "weapon_2h",
        "ground_description": "A wooden scepter lies here, wrapped in green vines that twist along its length.",
        "description": "Long vines twist around the length of the wooden staff, in a green color that almost seems to glow.'",
        "skill_modifier": "avatar cooldown 20",
        "health_max": 200,
        "intelligence": 150,
        "mana_regen": 20,
    },
    {
        "name": "The Staff of Neredae",
        "weapon_type": "staff",
        "equipment_type": "weapon_2h",
        "ground_description": "A staff lies here, runes carved along its length glowing in a soft light.",
        "description": "Twisted and long, the staff is carved along its length with runes that glow in a soft, pulsing light.",
        "skill_modifier": "freeze cooldown 18",
        "health_max": 200,
        "intelligence": 150,
        "spell_power": 100,
        "crit": 100,
    },
    {
        "name": "The Sunken Blade",
        "weapon_type": "dagger",
        "equipment_type": "weapon_1h",
        "ground_description": "A long dagger lies here, blade curved and transluscent.",
        "description": "The dagger's crystal blade is long and transluscent, curved with serrated indents on the short side.",
        "skill_modifier": "backstab multiplier 3.5",
        "health_max": 100,
        "dexterity": 75,
        "crit": 100,
    },
]

def create_uniques(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    if not World.objects.filter(id=1).exists():
        return

    ItemTemplate = apps.get_model('builders', 'ItemTemplate')

    for item_data in items:
        ItemTemplate.objects.create(
            world_id=1,
            level=20,
            type='equippable',
            cost=0,
            quality='enchanted',
            **item_data)


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0144_itemtemplate_skill_modifier'),
    ]

    operations = [
        migrations.RunPython(create_uniques)
    ]
