# Generated by Django 3.0.6 on 2020-08-28 19:00

from django.db import migrations, models


def migrate_setup_quests(apps, schema_editor):
    Quest = apps.get_model('builders', 'Quest')
    Quest.objects.filter(type='deliver').update(is_setup=True, type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0145_unique_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_setup_quests)
    ]
