# Generated by Django 3.0.6 on 2020-09-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0146_quest_is_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobreaction',
            name='event',
            field=models.TextField(choices=[('enter', 'Enter'), ('say', 'Say'), ('receive', 'Receive'), ('periodic', 'Periodic'), ('connect', 'Connect'), ('load', 'Load'), ('death', 'Death')]),
        ),
    ]
