# Generated by Django 3.1.1 on 2020-11-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0050_world_facts'),
        ('builders', '0147_auto_20200907_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('selection', models.TextField(choices=[('default', 'Default'), ('cycle', 'Cycle'), ('random', 'Random')], default='default')),
                ('fact', models.TextField()),
                ('value', models.TextField()),
                ('schedule', models.TextField()),
                ('schedule_type', models.TextField(choices=[('interval', 'Interval'), ('cron', 'Cron')], default='interval')),
                ('change_msg', models.TextField(default='')),
                ('next_run_ts', models.DateTimeField(blank=True, null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_schedules', to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
