# Generated by Django 3.1.1 on 2021-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0149_auto_20210112_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
