# Generated by Django 3.1.1 on 2021-01-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0151_auto_20210115_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='teaches',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='teaching_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
