# Generated by Django 3.1.1 on 2021-01-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0052_auto_20210115_1546'),
        ('builders', '0152_auto_20210125_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('cost_type', models.TextField(choices=[('health', 'Health'), ('stamina', 'Stamina'), ('mana', 'Mana')], default='mana')),
                ('cost_calc', models.TextField(choices=[('fixed', 'Fixed'), ('perc_base', 'Perc_base'), ('perc_max', 'Perc_max')], default='perc_base')),
                ('damage', models.FloatField(default=0)),
                ('damage_type', models.TextField(choices=[('physical', 'Physical'), ('magical', 'Magical')], default='physical')),
                ('damage_calc', models.TextField(choices=[('normal', 'Normal'), ('fixed', 'Fixed')], default='normal')),
                ('cast_time', models.FloatField(default=0)),
                ('cooldown', models.FloatField(default=0)),
                ('effect', models.TextField(blank=True, choices=[('dot', 'Dot'), ('hot', 'Hot'), ('stun', 'Stun'), ('sleep', 'Sleep')], null=True)),
                ('effect_damage', models.FloatField(default=0)),
                ('effect_duration', models.FloatField(default=0)),
                ('effect_damage_type', models.TextField(choices=[('physical', 'Physical'), ('magical', 'Magical')], default='magical')),
                ('requires', models.TextField(blank=True, null=True)),
                ('consumes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumers', to='builders.itemtemplate')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
