# Generated by Django 3.1.1 on 2021-02-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0153_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='effect_damage_calc',
            field=models.TextField(choices=[('normal', 'Normal'), ('fixed', 'Fixed')], default='normal'),
        ),
    ]
