# Generated by Django 3.1.1 on 2021-02-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0154_skill_effect_damage_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='intent',
            field=models.TextField(choices=[('damage', 'Damage'), ('healing', 'Healing')], default='damage'),
        ),
    ]
