# Generated by Django 3.1.1 on 2021-02-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0052_auto_20210115_1546'),
        ('builders', '0155_skill_intent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('world_id', 'code')},
        ),
    ]
