# Generated by Django 3.1.1 on 2021-02-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0156_auto_20210209_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='help',
            field=models.TextField(blank=True, null=True),
        ),
    ]
