# Generated by Django 3.1.1 on 2021-02-20 20:36

from django.contrib.contenttypes.models import ContentType
from django.db import migrations

def set_default_core_factions(apps, schema_editor):
    Faction = apps.get_model('builders', 'Faction')
    FactionAssignment = apps.get_model('builders', 'FactionAssignment')
    MobTemplate = apps.get_model('builders', 'MobTemplate')

    mob_ct = ContentType.objects.get_for_model(MobTemplate)

    core_factions = Faction.objects.filter(is_core=True, is_default=True)
    for core_faction in core_factions:
        for mob_template in core_faction.world.mob_templates.filter(
            type='humanoid'):
            try:
                existing_core_faction_assignment = FactionAssignment.objects.get(
                    member_id=mob_template.id,
                    member_type_id=mob_ct.id,
                    faction__is_core=True)
            except FactionAssignment.DoesNotExist:
                FactionAssignment.objects.create(
                    faction=core_faction,
                    member_id=mob_template.id,
                    member_type_id=mob_ct.id,
                    value=1)
            print("%s - assigned %s core faction to %s" % (
                core_faction.world.name,
                core_faction.name,
                mob_template.name))

    print('done')

class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0157_skill_help'),
    ]

    operations = [
        migrations.RunPython(set_default_core_factions),
    ]
