# Generated by Django 3.1.1 on 2021-04-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0159_auto_20210324_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='completion_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
