# Generated by Django 3.1.1 on 2021-04-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0160_quest_completion_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_logged',
            field=models.BooleanField(default=True),
        ),
    ]
