# Generated by Django 3.1.1 on 2021-09-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0161_quest_is_logged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomaction',
            options={},
        ),
    ]
