# Generated by Django 3.1.1 on 2021-09-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0162_auto_20210901_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('actions', models.TextField()),
                ('commands', models.TextField()),
                ('conditions', models.TextField(blank=True, null=True)),
                ('show_details_on_failure', models.BooleanField(default=False)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('display_action_in_room', models.BooleanField(default=True)),
                ('gate_delay', models.IntegerField(default=10)),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_actions', to='builders.itemtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
