# Generated by Django 3.2.10 on 2023-04-15 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0062_worldurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builders', '0164_auto_20211228_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('reviewed', 'Reviewed')], default='submitted')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_reviews', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_reviews', to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
