# Generated by Django 3.2.10 on 2023-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0165_worldreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobtemplate',
            name='aggression',
            field=models.TextField(choices=[('passive', 'Passive'), ('all', 'All'), ('players', 'Players'), ('normal', 'Normal'), ('friendly', 'Friendly')], default='passive'),
        ),
    ]
