# Generated by Django 3.2.10 on 2023-08-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0062_worldurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builders', '0166_alter_mobtemplate_aggression'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('action', models.TextField(choices=[('world_start', 'World_start'), ('world_stop', 'World_stop'), ('world_kill', 'World_kill')])),
                ('outcome', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builder_user_actions', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builder_world_actions', to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
