# Generated by Django 3.2.10 on 2023-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0167_builderaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='unlearn_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='unlearns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
