# Generated by Django 3.2.10 on 2023-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0168_auto_20230807_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='loader',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
