# Generated by Django 3.2.10 on 2023-09-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0169_loader_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcheck',
            name='check',
            field=models.TextField(blank=True, choices=[('equipped', 'Equipped'), ('not_equipped', 'Not_equipped'), ('in_inv', 'In_inv'), ('not_in_inv', 'Not_in_inv'), ('mob_is_present', 'Mob_is_present'), ('faction_below', 'Faction_below'), ('health_below', 'Health_below'), ('quest_complete', 'Quest_complete'), ('quest_incomplete', 'Quest_incomplete')], null=True),
        ),
    ]
