# Generated by Django 3.2.10 on 2023-10-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0170_alter_roomcheck_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldreview',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
