# Generated by Django 3.2.25 on 2024-06-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0173_alter_path_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='intent',
            field=models.TextField(choices=[('damage', 'Damage'), ('healing', 'Healing'), ('self_healing', 'Self_healing')], default='damage'),
        ),
    ]
