# Generated by Django 3.2.25 on 2024-07-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0174_alter_skill_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='arguments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
