# Generated by Django 3.2.25 on 2024-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0175_skill_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='effect',
            field=models.TextField(blank=True, choices=[('dot', 'Dot'), ('hot', 'Hot'), ('stun', 'Stun'), ('sleep', 'Sleep'), ('absorb', 'Absorb'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('haste', 'Haste')], null=True),
        ),
    ]
