# Generated by Django 3.2.25 on 2024-09-06 03:12

from django.db import migrations, models
import django.db.models.deletion


def migrate_builders(apps, schema_editor):
    WorldBuilder = apps.get_model('builders', 'WorldBuilder')
    for builder in WorldBuilder.objects.all():
        if builder.read_only:
            builder.builder_rank = 2
        else:
            builder.builder_rank = 3
        builder.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('builders', '0176_alter_skill_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldbuilder',
            name='builder_rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BuilderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('assignment_id', models.PositiveIntegerField()),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_types', to='contenttypes.contenttype')),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_builder_assignments', to='builders.worldbuilder')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_builders),
    ]
