# Generated by Django 3.2.25 on 2024-09-09 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0177_auto_20240906_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builderassignment',
            name='builder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builder_assignments', to='builders.worldbuilder'),
        ),
        migrations.AlterField(
            model_name='mobreaction',
            name='event',
            field=models.TextField(choices=[('enter', 'Enter'), ('say', 'Say'), ('receive', 'Receive'), ('periodic', 'Periodic'), ('connect', 'Connect'), ('load', 'Load'), ('death', 'Death'), ('health', 'Health')]),
        ),
    ]
