# Generated by Django 3.2.25 on 2024-09-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0178_auto_20240909_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='traits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
