# Generated by Django 3.2.25 on 2024-09-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0179_mobtemplate_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='is_upgrader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='upgrade_cost_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='upgrade_success_chance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='upgrade_success_cmd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
