# Generated by Django 3.2.25 on 2024-09-17 18:14

from django.db import migrations, models

def add_upgraders(apps, schema_editor):
    MobTemplate = apps.get_model('builders', 'MobTemplate')
    RoomFlag = apps.get_model('worlds', 'RoomFlag')
    Room = apps.get_model('worlds', 'Room')
    Loader = apps.get_model('builders', 'Loader')
    Rule = apps.get_model('builders', 'Rule')
    World = apps.get_model('worlds', 'World')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    room_flags_qs = RoomFlag.objects.filter(code='workshop')
    world_ids = set(room_flags_qs.values_list('room__world_id', flat=True))

    for world in World.objects.filter(id__in=world_ids):
        mob_template = MobTemplate.objects.create(
            world=world,
            name="an expert upgrader",
            room_description="A tinkerer stands here, ready to upgrade your equipment.",
            keywords="expert upgrader tinkerer",
            description="Heavy, soot-streaked robes hang loosely over a middle age man's muscular frame. His face is lined and weathered, with deep-set eyes that seem to constantly squint, likely from years of working near intense heat. His hands are rough and scarred, and from his face grows a short graying beard flecked with ash.",
            is_upgrader=True)
        for room in Room.objects.filter(world=world, flags__in=room_flags_qs):
            loader = Loader.objects.create(
                world=world,
                name='Upgrader load for %s' % room.name,
                zone=room.zone)
            Rule.objects.create(
                loader=loader,
                template_type=ContentType.objects.get_for_model(MobTemplate),
                template_id=mob_template.id,
                target_type=ContentType.objects.get_for_model(Room),
                target_id=room.id,
                num_copies=1)


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0180_auto_20240912_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobtemplate',
            name='upgrade_success_chance',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.RunPython(add_upgraders),
    ]
