# Generated by Django 3.2.25 on 2024-09-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0181_alter_mobtemplate_upgrade_success_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobtemplate',
            name='upgrade_failure_cmd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
