# Generated by Django 3.2.25 on 2024-09-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0078_alter_worldconfig_death_mode'),
        ('builders', '0182_mobtemplate_upgrade_failure_cmd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('cmd', models.TextField()),
                ('priority', models.PositiveIntegerField(default=0)),
                ('msg_targetless_self', models.TextField(blank=True, null=True)),
                ('msg_targetless_other', models.TextField(blank=True, null=True)),
                ('msg_targeted_self', models.TextField(blank=True, null=True)),
                ('msg_targeted_target', models.TextField(blank=True, null=True)),
                ('msg_targeted_other', models.TextField(blank=True, null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
    ]
