# Generated by Django 3.2.25 on 2024-09-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0078_alter_worldconfig_death_mode'),
        ('builders', '0183_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('world', 'cmd')},
        ),
    ]
