# Generated by Django 3.2.25 on 2024-09-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0184_auto_20240919_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='on_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='type',
            field=models.TextField(choices=[('equippable', 'Equippable'), ('consumable', 'Consumable'), ('food', 'Food'), ('light', 'Light'), ('container', 'Container'), ('key', 'Key'), ('inert', 'Inert'), ('corpse', 'Corpse'), ('trash', 'Trash'), ('quest', 'Quest'), ('ammunition', 'Ammunition'), ('augment', 'Augment')], default='inert'),
        ),
    ]
