# Generated by Django 3.2.25 on 2024-09-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0186_auto_20240922_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentslot',
            name='slot_name',
            field=models.TextField(choices=[('weapon', 'Weapon'), ('offhand', 'Offhand'), ('head', 'Head'), ('body', 'Body'), ('arms', 'Arms'), ('hands', 'Hands'), ('waist', 'Waist'), ('legs', 'Legs'), ('feet', 'Feet'), ('accessory', 'Accessory')]),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='equipment_type',
            field=models.TextField(blank=True, choices=[('weapon_1h', 'Weapon_1h'), ('weapon_2h', 'Weapon_2h'), ('shield', 'Shield'), ('head', 'Head'), ('body', 'Body'), ('arms', 'Arms'), ('hands', 'Hands'), ('waist', 'Waist'), ('legs', 'Legs'), ('feet', 'Feet'), ('accessory', 'Accessory')], null=True),
        ),
    ]
