# Generated by Django 3.2.25 on 2024-09-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0187_auto_20240922_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='effect',
            field=models.TextField(blank=True, choices=[('dot', 'Dot'), ('hot', 'Hot'), ('stun', 'Stun'), ('sleep', 'Sleep'), ('absorb', 'Absorb'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('haste', 'Haste'), ('invisibility', 'Invisibility')], null=True),
        ),
    ]
