# Generated by Django 3.2.25 on 2024-09-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0188_alter_skill_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobreaction',
            name='event',
            field=models.TextField(choices=[('enter', 'Enter'), ('say', 'Say'), ('receive', 'Receive'), ('periodic', 'Periodic'), ('connect', 'Connect'), ('load', 'Load'), ('death', 'Death'), ('health', 'Health'), ('social', 'Social')]),
        ),
    ]
