# Generated by Django 3.2.25 on 2024-09-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0189_alter_mobreaction_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='effect',
            field=models.TextField(blank=True, choices=[('dot', 'Dot'), ('hot', 'Hot'), ('stun', 'Stun'), ('sleep', 'Sleep'), ('absorb', 'Absorb'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('haste', 'Haste'), ('invisibility', 'Invisibility'), ('thorns', 'Thorns'), ('summon', 'Summon')], null=True),
        ),
    ]
