# Generated by Django 3.2.25 on 2024-10-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0190_alter_skill_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='learn_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
