# Generated by Django 3.2.25 on 2024-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0191_skill_learn_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobreaction',
            name='event',
            field=models.TextField(choices=[('enter', 'Enter'), ('say', 'Say'), ('receive', 'Receive'), ('periodic', 'Periodic'), ('connect', 'Connect'), ('load', 'Load'), ('death', 'Death'), ('health', 'Health'), ('social', 'Social'), ('combat_enter', 'Combat_enter'), ('combat_exit', 'Combat_exit')]),
        ),
    ]
