# Generated by Django 3.2.25 on 2024-11-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0193_alter_mobreaction_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='on_use_equipped',
            field=models.BooleanField(default=False),
        ),
    ]
