# Generated by Django 3.2.25 on 2024-11-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0080_worldconfig_cross_race_cooldown'),
        ('builders', '0194_itemtemplate_on_use_equipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='worlds.world')),
            ],
            options={
                'unique_together': {('world', 'code')},
            },
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='currency_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builders.currency'),
        ),
    ]
