# Generated by Django 3.2.25 on 2024-11-22 19:30

from django.db import migrations

def initial_currencies_migration(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    Currency = apps.get_model('builders', 'Currency')
    ItemTemplate = apps.get_model('builders', 'ItemTemplate')

    worlds = World.objects.filter(context__isnull=True,
                                  instance_of__isnull=True)

    for world in worlds:
        gold = Currency.objects.create(world=world,
                                       code='gold',
                                       name='Gold',
                                       is_default=True, )
        medals = Currency.objects.create(world=world,
                                         code='medals',
                                         name='Medals',
                                         is_default=False, )
        for item_template in ItemTemplate.objects.filter(world=world):
            if item_template.currency == 'gold':
                item_template.currency_fk = gold
            elif item_template.currency == 'medals':
                item_template.currency_fk = medals
            elif item_template.currency == 'medal':
                item_template.currency_fk = medals
            item_template.save()

class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0195_auto_20241122_1929'),
    ]

    operations = [
        migrations.RunPython(initial_currencies_migration),
    ]
