# Generated by Django 3.2.25 on 2024-11-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0196_initial_currencies_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtemplate',
            name='currency',
        ),
    ]
