# Generated by Django 3.2.25 on 2024-11-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0197_remove_itemtemplate_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtemplate',
            old_name='currency_fk',
            new_name='currency',
        ),
    ]
