# Generated by Django 3.2.25 on 2024-11-25 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0198_rename_currency_fk_itemtemplate_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_objectives', to='builders.currency'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='type',
            field=models.TextField(choices=[('item', 'Item'), ('mob', 'Mob'), ('gold', 'Gold'), ('glory', 'Glory'), ('medals', 'Medals'), ('currency', 'Currency')]),
        ),
    ]
