# Generated by Django 3.2.25 on 2024-11-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0199_auto_20241125_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_rewards', to='builders.currency'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.TextField(choices=[('item', 'Item'), ('exp', 'Exp'), ('gold', 'Gold'), ('faction', 'Faction'), ('glory', 'Glory'), ('currency', 'Currency')]),
        ),
    ]
