# Generated by Django 3.2.25 on 2025-06-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0203_auto_20250611_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='effect',
            field=models.TextField(blank=True, choices=[('dot', 'Dot'), ('hot', 'Hot'), ('stun', 'Stun'), ('sleep', 'Sleep'), ('absorb', 'Absorb'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('haste', 'Haste'), ('invisibility', 'Invisibility'), ('stealth', 'Stealth'), ('thorns', 'Thorns'), ('summon', 'Summon'), ('dispel', 'Dispel'), ('purge', 'Purge')], null=True),
        ),
    ]
