# Generated by Django 2.0.4 on 2026-01-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0204_alter_skill_effect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomcommandcheck',
            old_name='check',
            new_name='check_type',
        ),
        migrations.RenameField(
            model_name='roomcheck',
            old_name='check',
            new_name='check_type',
        ),
    ]
