# Generated by Django 2.0.4 on 2026-01-30 00:00

from django.db import migrations, models

from config import constants as adv_consts
from core.db import list_to_choice


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0205_rename_room_check_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='path',
                    name='rooms',
                    field=models.ManyToManyField(through='builders.PathRoom', to='worlds.Room'),
                ),
                migrations.AlterField(
                    model_name='roomcommandcheck',
                    name='check_type',
                    field=models.TextField(
                        choices=list_to_choice(adv_consts.CMD_CHECKS),
                        db_column='check',
                    ),
                ),
                migrations.AlterField(
                    model_name='roomcheck',
                    name='check_type',
                    field=models.TextField(
                        blank=True,
                        null=True,
                        choices=list_to_choice(adv_consts.ROOM_CHECKS),
                        db_column='check',
                    ),
                ),
            ],
        ),
    ]
