# Generated by Django 2.0.4 on 2026-01-30 00:00

from django.db import migrations, models

from core.db import list_to_choice


LEGACY_CMD_CHECKS = [
    'in_inv',
    'cmd_issued',
]

LEGACY_ROOM_CHECKS = [
    'equipped',
    'not_equipped',
    'in_inv',
    'not_in_inv',
    'mob_is_present',
    'faction_below',
    'health_below',
    'quest_complete',
    'quest_incomplete',
]


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0205_rename_room_check_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='path',
                    name='rooms',
                    field=models.ManyToManyField(through='builders.PathRoom', to='worlds.Room'),
                ),
                migrations.AlterField(
                    model_name='roomcommandcheck',
                    name='check_type',
                    field=models.TextField(
                        choices=list_to_choice(LEGACY_CMD_CHECKS),
                        db_column='check',
                    ),
                ),
                migrations.AlterField(
                    model_name='roomcheck',
                    name='check_type',
                    field=models.TextField(
                        blank=True,
                        null=True,
                        choices=list_to_choice(LEGACY_ROOM_CHECKS),
                        db_column='check',
                    ),
                ),
            ],
        ),
    ]
