# Generated by Django 2.0.4 on 2026-02-12 00:00

from django.db import migrations, models
from django.db.models import Count


def dedupe_faction_assignments(apps, schema_editor):
    FactionAssignment = apps.get_model('builders', 'FactionAssignment')

    # Keep one row per (member, faction), preferring the most recently updated.
    duplicate_member_faction_groups = (
        FactionAssignment.objects
        .filter(
            member_type_id__isnull=False,
            member_id__isnull=False,
            faction_id__isnull=False,
        )
        .values('member_type_id', 'member_id', 'faction_id')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    for group in duplicate_member_faction_groups.iterator():
        assignments = FactionAssignment.objects.filter(
            member_type_id=group['member_type_id'],
            member_id=group['member_id'],
            faction_id=group['faction_id'],
        ).order_by('-modified_ts', '-created_ts', '-id')
        keeper = assignments.first()
        if keeper:
            assignments.exclude(id=keeper.id).delete()

    # Keep a single core assignment per member, preferring the world default,
    # then the most recently updated assignment.
    duplicate_core_groups = (
        FactionAssignment.objects
        .filter(
            member_type_id__isnull=False,
            member_id__isnull=False,
            faction__is_core=True,
        )
        .values('member_type_id', 'member_id')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    for group in duplicate_core_groups.iterator():
        assignments = FactionAssignment.objects.filter(
            member_type_id=group['member_type_id'],
            member_id=group['member_id'],
            faction__is_core=True,
        ).order_by('-faction__is_default', '-modified_ts', '-created_ts', '-id')
        keeper = assignments.first()
        if keeper:
            assignments.exclude(id=keeper.id).delete()


def add_single_core_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION builders_enforce_single_core_faction_assignment()
        RETURNS trigger
        AS $$
        BEGIN
            IF NEW.member_type_id IS NULL OR NEW.member_id IS NULL OR NEW.faction_id IS NULL THEN
                RETURN NEW;
            END IF;

            IF EXISTS (
                SELECT 1
                FROM builders_faction f
                WHERE f.id = NEW.faction_id
                  AND f.is_core = TRUE
            ) THEN
                IF EXISTS (
                    SELECT 1
                    FROM builders_factionassignment fa
                    INNER JOIN builders_faction cf ON cf.id = fa.faction_id
                    WHERE fa.member_type_id = NEW.member_type_id
                      AND fa.member_id = NEW.member_id
                      AND cf.is_core = TRUE
                      AND fa.id <> COALESCE(NEW.id, -1)
                ) THEN
                    RAISE EXCEPTION 'Member already has a core faction assignment'
                        USING ERRCODE = '23514';
                END IF;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS builders_factionassignment_single_core_assignment_trg
        ON builders_factionassignment;
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER builders_factionassignment_single_core_assignment_trg
        BEFORE INSERT OR UPDATE OF faction_id, member_type_id, member_id
        ON builders_factionassignment
        FOR EACH ROW
        EXECUTE FUNCTION builders_enforce_single_core_faction_assignment();
        """
    )


def remove_single_core_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS builders_factionassignment_single_core_assignment_trg
        ON builders_factionassignment;
        """
    )
    schema_editor.execute(
        """
        DROP FUNCTION IF EXISTS builders_enforce_single_core_faction_assignment();
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0206_state_only_room_checks_and_paths'),
    ]

    operations = [
        migrations.RunPython(
            dedupe_faction_assignments,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='factionassignment',
            constraint=models.UniqueConstraint(
                fields=('member_type', 'member_id', 'faction'),
                name='builders_member_faction_assignment_unique',
            ),
        ),
        migrations.RunPython(
            add_single_core_trigger,
            remove_single_core_trigger,
        ),
    ]
