# Generated by Django 3.2.25 on 2026-02-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('builders', '0207_factionassignment_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('scope', models.TextField(choices=[('room', 'Room'), ('zone', 'Zone'), ('world', 'World')], default='room')),
                ('kind', models.TextField(choices=[('command_fallback', 'Command_fallback')], default='command_fallback')),
                ('name', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('show_details_on_failure', models.BooleanField(default=False)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('display_action_in_room', models.BooleanField(default=True)),
                ('gate_delay', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_target_types', to='contenttypes.contenttype')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
            },
        ),
    ]
