# Generated by Django 3.2.25 on 2026-02-17 00:00

from django.db import migrations, models


def migrate_trigger_kind_to_command(apps, schema_editor):
    Trigger = apps.get_model("builders", "Trigger")
    Trigger.objects.filter(kind="command_fallback").update(kind="command")

class Migration(migrations.Migration):

    dependencies = [
        ("builders", "0208_trigger_definition"),
    ]

    operations = [
        migrations.RunPython(
            migrate_trigger_kind_to_command,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="trigger",
            name="kind",
            field=models.TextField(
                choices=[
                    ("command", "Command"),
                ],
                default="command",
            ),
        ),
    ]
