# Generated by Django 3.2.25 on 2026-02-20

from django.db import migrations, models


def migrate_mob_reactions_to_triggers(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    MobReaction = apps.get_model("builders", "MobReaction")
    Trigger = apps.get_model("builders", "Trigger")

    mob_template_ct = ContentType.objects.get(
        app_label="builders",
        model="mobtemplate",
    )

    for reaction in MobReaction.objects.select_related("template").all().iterator():
        template = reaction.template
        if template is None:
            continue

        lookup = {
            "world_id": template.world_id,
            "target_type_id": mob_template_ct.id,
            "target_id": template.id,
            "scope": "world",
            "kind": "event",
            "script": reaction.reaction,
            "event": reaction.event,
            "option": reaction.option,
        }
        defaults = {
            "name": "",
            "actions": "",
            "conditions": reaction.conditions,
            "display_action_in_room": False,
            "gate_delay": 10,
            "order": 0,
            "is_active": True,
        }
        Trigger.objects.get_or_create(
            **lookup,
            defaults=defaults,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("builders", "0209_trigger_kind_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="event",
            field=models.TextField(
                blank=True,
                choices=[
                    ("enter", "Enter"),
                    ("say", "Say"),
                    ("receive", "Receive"),
                    ("periodic", "Periodic"),
                    ("connect", "Connect"),
                    ("load", "Load"),
                    ("death", "Death"),
                    ("health", "Health"),
                    ("social", "Social"),
                    ("combat_enter", "Combat_enter"),
                    ("combat_exit", "Combat_exit"),
                    ("new_room", "New_room"),
                    ("notify", "Notify"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trigger",
            name="option",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(
            migrate_mob_reactions_to_triggers,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="trigger",
            name="kind",
            field=models.TextField(
                choices=[
                    ("command", "Command"),
                    ("event", "Event"),
                ],
                default="command",
            ),
        ),
    ]
