# Generated by Django 3.2.25 on 2026-02-21

from django.db import migrations, models


def migrate_trigger_match_values(apps, schema_editor):
    Trigger = apps.get_model("builders", "Trigger")

    for trigger in Trigger.objects.all().iterator():
        if trigger.kind == "event":
            trigger.match = trigger.option or trigger.actions or ""
        else:
            trigger.match = trigger.actions or trigger.option or ""
        trigger.save(update_fields=["match"])


class Migration(migrations.Migration):

    dependencies = [
        ("builders", "0210_trigger_event_mob_reactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="match",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(
            migrate_trigger_match_values,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="trigger",
            name="actions",
        ),
        migrations.RemoveField(
            model_name="trigger",
            name="option",
        ),
    ]
