# Generated by Django 5.2.12 on 2026-03-25 03:09

from django.db import migrations, models
from django.utils.text import slugify


def _backfill_template_slugs(apps, schema_editor):
    for model_name, fallback_prefix in (
        ("ItemTemplate", "item-template"),
        ("MobTemplate", "mob-template"),
    ):
        model_cls = apps.get_model("builders", model_name)
        used_slugs_by_world = {}

        queryset = model_cls.objects.order_by("world_id", "created_ts", "id")
        for template in queryset.iterator():
            world_used_slugs = used_slugs_by_world.setdefault(template.world_id, set())
            if template.slug:
                world_used_slugs.add(template.slug)
                continue

            base_slug = slugify(template.name or "") or fallback_prefix
            slug = base_slug
            counter = 2
            while slug in world_used_slugs:
                slug = f"{base_slug}-{counter}"
                counter += 1

            world_used_slugs.add(slug)
            model_cls.objects.filter(pk=template.pk).update(slug=slug)


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0211_trigger_match_field'),
        ('worlds', '0090_state_only_worldconfig_starting_eq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtemplate',
            options={'ordering': ['created_ts']},
        ),
        migrations.AlterModelOptions(
            name='mobtemplate',
            options={'ordering': ['created_ts']},
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='mobtemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(
            _backfill_template_slugs,
            _noop_reverse,
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='mobtemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='itemtemplate',
            unique_together={('world', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='mobtemplate',
            unique_together={('world', 'slug')},
        ),
    ]
