# Generated by Django 5.2.13 on 2026-05-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0214_abilitydefinition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skill',
            name='consumes',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='world',
        ),
        migrations.RemoveField(
            model_name='itemtemplate',
            name='skill_modifier',
        ),
        migrations.RemoveField(
            model_name='mobtemplate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='mobtemplate',
            name='teaches',
        ),
        migrations.RemoveField(
            model_name='mobtemplate',
            name='teaching_conditions',
        ),
        migrations.RemoveField(
            model_name='mobtemplate',
            name='unlearn_cost',
        ),
        migrations.RemoveField(
            model_name='mobtemplate',
            name='unlearns',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
