# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builders", "0221_merchant_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="kind",
            field=models.TextField(
                choices=[
                    ("command", "Command"),
                    ("event", "Event"),
                    ("policy", "Policy"),
                ],
                default="command",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="event",
            field=models.TextField(
                blank=True,
                choices=[
                    ("enter", "Enter"),
                    ("say", "Say"),
                    ("receive", "Receive"),
                    ("periodic", "Periodic"),
                    ("connect", "Connect"),
                    ("load", "Load"),
                    ("death", "Death"),
                    ("health", "Health"),
                    ("social", "Social"),
                    ("combat_enter", "Combat_enter"),
                    ("combat_exit", "Combat_exit"),
                    ("new_room", "New_room"),
                    ("notify", "Notify"),
                    ("before_move_exit", "Before_move_exit"),
                    ("before_move_enter", "Before_move_enter"),
                    ("after_move_exit", "After_move_exit"),
                    ("after_move_enter", "After_move_enter"),
                ],
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="trigger",
            index=models.Index(
                fields=[
                    "world",
                    "kind",
                    "event",
                    "scope",
                    "target_type",
                    "target_id",
                    "is_active",
                    "order",
                ],
                name="trigger_hook_lookup_idx",
            ),
        ),
    ]
