# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builders", "0222_trigger_policy_hooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobdefinition",
            name="trainer",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
