# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builders", "0224_abilitydefinition_cast_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="event",
            field=models.TextField(
                blank=True,
                choices=[
                    ("enter", "Enter"),
                    ("say", "Say"),
                    ("receive", "Receive"),
                    ("periodic", "Periodic"),
                    ("connect", "Connect"),
                    ("load", "Load"),
                    ("death", "Death"),
                    ("health", "Health"),
                    ("social", "Social"),
                    ("combat_enter", "Combat_enter"),
                    ("combat_exit", "Combat_exit"),
                    ("new_room", "New_room"),
                    ("notify", "Notify"),
                    ("before_move_exit", "Before_move_exit"),
                    ("before_move_enter", "Before_move_enter"),
                    ("after_move_exit", "After_move_exit"),
                    ("after_move_enter", "After_move_enter"),
                    ("after_death_room_enter", "After_death_room_enter"),
                ],
                null=True,
            ),
        ),
    ]
