# Generated by Django 5.2.14 on 2026-07-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0234_loot_tables'),
        ('spawns', '0134_remove_playerenquire_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='template_type',
        ),
        migrations.AlterUniqueTogether(
            name='quest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quest',
            name='mob_template',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='requires_quest',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='world',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='profile_type',
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
