# Generated by Django 5.2.14 on 2026-07-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0235_remove_objective_currency_remove_objective_quest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtemplateinventory',
            name='container',
        ),
        migrations.RemoveField(
            model_name='itemtemplateinventory',
            name='item_template',
        ),
        migrations.RemoveField(
            model_name='mobtemplateinventory',
            name='container',
        ),
        migrations.RemoveField(
            model_name='mobtemplateinventory',
            name='item_bundle',
        ),
        migrations.RemoveField(
            model_name='mobtemplateinventory',
            name='item_definition',
        ),
        migrations.RemoveField(
            model_name='mobtemplateinventory',
            name='item_template',
        ),
        migrations.DeleteModel(
            name='ItemTemplateInventory',
        ),
        migrations.DeleteModel(
            name='MobTemplateInventory',
        ),
    ]
