# Generated by Django 5.2.14 on 2026-07-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0236_remove_itemtemplateinventory_container_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobequipmentprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='equipmentslot',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='equipmentslot',
            name='item_template',
        ),
        migrations.RemoveField(
            model_name='itemaction',
            name='item_template',
        ),
        migrations.AlterUniqueTogether(
            name='itemtemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itemtemplate',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='itemtemplate',
            name='world',
        ),
        migrations.RemoveField(
            model_name='merchantinventory',
            name='item_template',
        ),
        migrations.RemoveField(
            model_name='loader',
            name='world',
        ),
        migrations.RemoveField(
            model_name='loader',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='loader',
        ),
        migrations.RemoveField(
            model_name='merchantinventory',
            name='item_bundle',
        ),
        migrations.RemoveField(
            model_name='merchantinventory',
            name='item_definition',
        ),
        migrations.RemoveField(
            model_name='merchantinventory',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='merchantinventory',
            name='random_item_profile',
        ),
        migrations.RemoveField(
            model_name='mobequipmentprofile',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='mobreaction',
            name='template',
        ),
        migrations.RemoveField(
            model_name='mobreactioncondition',
            name='reaction',
        ),
        migrations.AlterUniqueTogether(
            name='mobtemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mobtemplate',
            name='world',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='template_type',
        ),
        migrations.DeleteModel(
            name='EquipmentProfile',
        ),
        migrations.DeleteModel(
            name='EquipmentSlot',
        ),
        migrations.DeleteModel(
            name='ItemAction',
        ),
    ]
