# Generated by Django 5.2.14 on 2026-07-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0237_remove_legacy_template_model_fks'),
        ('spawns', '0135_remove_runtime_template_rule_fks'),
        ('worlds', '0108_alter_door_key_itemdefinition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemTemplate',
        ),
        migrations.DeleteModel(
            name='Loader',
        ),
        migrations.DeleteModel(
            name='MerchantInventory',
        ),
        migrations.DeleteModel(
            name='MobEquipmentProfile',
        ),
        migrations.DeleteModel(
            name='MobReaction',
        ),
        migrations.DeleteModel(
            name='MobReactionCondition',
        ),
        migrations.DeleteModel(
            name='MobTemplate',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
