# Generated by Django 5.2.16 on 2026-07-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0243_delete_roomcheck_roomcommandcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilitydefinition',
            options={},
        ),
        migrations.RenameIndex(
            model_name='abilitydefinition',
            new_name='builders_ab_world_i_efd7fe_idx',
            old_name='builders_ab_world_i_21ea11_idx',
        ),
        migrations.RenameIndex(
            model_name='abilitydefinition',
            new_name='builders_ab_world_i_1714a4_idx',
            old_name='builders_ab_world_i_1af96b_idx',
        ),
        migrations.RenameIndex(
            model_name='abilitydefinition',
            new_name='builders_ab_command_d4c9c2_gin',
            old_name='builders_ab_cmdverbs_gin',
        ),
        migrations.RenameIndex(
            model_name='spawnplacement',
            new_name='builders_sp_run_id_697bf8_idx',
            old_name='builders_sp_run_id_eb70f2_idx',
        ),
        migrations.RenameIndex(
            model_name='spawnplanrun',
            new_name='builders_sp_spawn_w_778b5a_idx',
            old_name='builders_sp_spawn__a4bb09_idx',
        ),
        migrations.AlterField(
            model_name='faction',
            name='type',
            field=models.TextField(choices=[('core', 'Core'), ('reputation', 'Reputation')], default='reputation'),
        ),
        migrations.AlterField(
            model_name='spawnentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spawnplacement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spawnplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spawnplanrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
