# Generated by Django 5.2.16 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0244_alter_abilitydefinition_options_and_more'),
        ('worlds', '0113_rename_worlds_inst_player__289221_idx_worlds_inst_player__f8ff2e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdefinition',
            name='salvage_only',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CraftMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('name', models.TextField(default='Unnamed Material')),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craft_materials', to='worlds.world')),
            ],
            options={
                'ordering': ['order', 'name', 'id'],
                'unique_together': {('world', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CraftingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('name', models.TextField(default='Unnamed Workshop')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafting_profiles', to='worlds.world')),
            ],
            options={
                'ordering': ['created_ts'],
                'unique_together': {('world', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CraftingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('group', models.SlugField(blank=True, db_index=True, max_length=120)),
                ('order', models.IntegerField(default=0)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('output_item_definition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='crafting_recipes', to='builders.itemdefinition')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafting_recipes', to='worlds.world')),
            ],
            options={
                'ordering': ['group', 'order', 'slug', 'id'],
                'unique_together': {('world', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CraftingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recipe_ingredients', to='builders.craftmaterial')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='builders.craftingrecipe')),
            ],
            options={
                'ordering': ['created_ts', 'id'],
                'unique_together': {('recipe', 'material')},
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='builders_crafting_ingredient_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='CraftingProfileRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_entries', to='builders.craftingprofile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_entries', to='builders.craftingrecipe')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('profile', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='craftingprofile',
            name='recipes',
            field=models.ManyToManyField(related_name='crafting_profiles', through='builders.CraftingProfileRecipe', to='builders.craftingrecipe'),
        ),
        migrations.CreateModel(
            name='ItemSalvageYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('item_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvage_yields', to='builders.itemdefinition')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_salvage_yields', to='builders.craftmaterial')),
            ],
            options={
                'ordering': ['created_ts', 'id'],
                'unique_together': {('item_definition', 'material')},
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='builders_item_salvage_yield_quantity_positive')],
            },
        ),
        migrations.AddField(
            model_name='mobdefinition',
            name='crafting_availability',
            field=models.TextField(blank=True, default='present'),
        ),
        migrations.AddField(
            model_name='mobdefinition',
            name='crafting_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mob_definitions', to='builders.craftingprofile'),
        ),
        migrations.AddIndex(
            model_name='craftmaterial',
            index=models.Index(fields=['world', 'order', 'name'], name='builders_cr_world_i_e19d06_idx'),
        ),
        migrations.AddIndex(
            model_name='craftingrecipe',
            index=models.Index(fields=['world', 'group', 'order'], name='builders_cr_world_i_bee5c6_idx'),
        ),
    ]
