# Generated by Django 5.2.16 on 2026-07-17 20:29

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0245_crafting'),
        ('worlds', '0114_room_crafting_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobCurrencyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.BigIntegerField()),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldStartingCurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['created_ts'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='funds_currency',
        ),
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='plural_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemdefinition',
            name='cost',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemdefinition',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item_definitions', to='builders.currency'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='settlement_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='merchant_profiles', to='builders.currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_-]{0,63}$')]),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='purchase_budget',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(models.F('world'), django.db.models.functions.text.Lower('code'), name='builders_currency_world_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[a-z][a-z0-9_-]{0,63}$')), name='builders_currency_code_valid'),
        ),
        migrations.AddField(
            model_name='mobcurrencyreward',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mob_rewards', to='builders.currency'),
        ),
        migrations.AddField(
            model_name='mobcurrencyreward',
            name='mob_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_rewards', to='builders.mobdefinition'),
        ),
        migrations.AddField(
            model_name='worldstartingcurrencybalance',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='starting_balance_rules', to='builders.currency'),
        ),
        migrations.AddField(
            model_name='worldstartingcurrencybalance',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_currency_balances', to='worlds.world'),
        ),
        migrations.RemoveField(
            model_name='currency',
            name='is_default',
        ),
        migrations.AddConstraint(
            model_name='mobcurrencyreward',
            constraint=models.UniqueConstraint(fields=('mob_definition', 'currency'), name='builders_mob_currency_reward_unique'),
        ),
        migrations.AddConstraint(
            model_name='mobcurrencyreward',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='builders_mob_currency_reward_positive'),
        ),
        migrations.AddConstraint(
            model_name='mobcurrencyreward',
            constraint=models.CheckConstraint(condition=models.Q(('amount__lte', 9007199254740991)), name='builders_mob_currency_reward_safe_integer'),
        ),
        migrations.AddConstraint(
            model_name='worldstartingcurrencybalance',
            constraint=models.UniqueConstraint(fields=('world', 'currency'), name='builders_starting_currency_balance_unique'),
        ),
        migrations.AddConstraint(
            model_name='worldstartingcurrencybalance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='builders_starting_currency_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='worldstartingcurrencybalance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__lte', 9007199254740991)), name='builders_starting_currency_balance_safe_integer'),
        ),
        migrations.AddConstraint(
            model_name='itemdefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cost__isnull', True), ('currency__isnull', True)), models.Q(('cost__gte', 0), ('cost__lte', 9007199254740991), ('currency__isnull', False)), _connector='OR'), name='builders_item_definition_money_pair'),
        ),
        migrations.AddConstraint(
            model_name='merchantprofile',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_budget__gte', 0), ('purchase_budget__lte', 9007199254740991)), name='builders_merchant_purchase_budget_safe'),
        ),
    ]
