# Generated by Django 5.2.16 on 2026-07-18

from django.db import migrations


def remove_legacy_content_types(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(
        app_label='builders',
        model__in=('randomitemprofile', 'transformationtemplate'),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0246_mobcurrencyreward_worldstartingcurrencybalance_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('spawns', '0145_remove_item_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomItemProfile',
        ),
        migrations.DeleteModel(
            name='TransformationTemplate',
        ),
        migrations.RunPython(
            remove_legacy_content_types,
            migrations.RunPython.noop,
        ),
    ]
