# Generated by Django 5.2.16 on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0247_delete_legacy_world_config_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftingrecipe',
            name='cost',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='craftingrecipe',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='crafting_recipes',
                to='builders.currency',
            ),
        ),
        migrations.AddConstraint(
            model_name='craftingrecipe',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('cost__isnull', True), ('currency__isnull', True)),
                    models.Q(
                        ('cost__gte', 0),
                        ('cost__lte', 9007199254740991),
                        ('currency__isnull', False),
                    ),
                    _connector='OR',
                ),
                name='builders_crafting_recipe_money_pair',
            ),
        ),
    ]
