# Generated by Django 5.2.16 on 2026-07-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0248_craftingrecipe_cost_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilitydefinition',
            name='action_type',
        ),
    ]
