# Generated by Django 5.2.16 on 2026-07-18 21:56

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0249_remove_abilitydefinition_action_type'),
        ('worlds', '0115_remove_worldconfig_death_gold_penalty_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='social',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='social',
            name='cmd',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_-]{0,63}$')]),
        ),
        migrations.AddConstraint(
            model_name='social',
            constraint=models.UniqueConstraint(models.F('world'), django.db.models.functions.text.Lower('cmd'), name='builders_social_world_cmd_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='social',
            constraint=models.CheckConstraint(condition=models.Q(('cmd__regex', '^[a-z][a-z0-9_-]{0,63}$')), name='builders_social_cmd_valid'),
        ),
        migrations.AddConstraint(
            model_name='social',
            constraint=models.CheckConstraint(condition=models.Q(('priority__lte', 1000000)), name='builders_social_priority_bounded'),
        ),
    ]
