# Generated by Django 5.2.16 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0250_alter_social_unique_together_alter_social_cmd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='on_step_error',
            field=models.TextField(default='cancel'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='steps',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
    ]
