# Generated by Django 5.2.17 on 2026-09-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0259_spawnplan_default_roam_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobdefinition',
            name='combat_assist',
            field=models.CharField(default='none', max_length=24),
        ),
        migrations.AddField(
            model_name='mobdefinition',
            name='combat_engage_when',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
