# Generated by Django 5.2.17 on 2026-09-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0260_participant_combat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobdefinition',
            name='combat_assist',
            field=models.CharField(choices=[('none', 'None'), ('same_spawn_cohort', 'Same_spawn_cohort'), ('allies', 'Allies')], default='none', max_length=24),
        ),
    ]
