# Generated by Django 5.2.17 on 2026-09-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0262_trigger_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobdefinition',
            name='rip_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
