# Generated by Django 5.2.18 on 2026-10-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0265_spawnentry_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantstockslot',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
