# Generated by Django 5.2.18 on 2026-10-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0266_unlimited_merchant_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldReview',
        ),
    ]
